// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/LimaTeixeiraTecnologia/mecontrola/internal/budgets/application/usecases"
	mock "github.com/stretchr/testify/mock"
)

// newNotifyThresholdAlertUseCase creates a new instance of notifyThresholdAlertUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newNotifyThresholdAlertUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *notifyThresholdAlertUseCase {
	mock := &notifyThresholdAlertUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// notifyThresholdAlertUseCase is an autogenerated mock type for the notifyThresholdAlertUseCase type
type notifyThresholdAlertUseCase struct {
	mock.Mock
}

type notifyThresholdAlertUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *notifyThresholdAlertUseCase) EXPECT() *notifyThresholdAlertUseCase_Expecter {
	return &notifyThresholdAlertUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type notifyThresholdAlertUseCase
func (_mock *notifyThresholdAlertUseCase) Execute(ctx context.Context, in usecases.NotifyThresholdAlertInput) (usecases.NotifyThresholdAlertResult, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 usecases.NotifyThresholdAlertResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, usecases.NotifyThresholdAlertInput) (usecases.NotifyThresholdAlertResult, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, usecases.NotifyThresholdAlertInput) usecases.NotifyThresholdAlertResult); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(usecases.NotifyThresholdAlertResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, usecases.NotifyThresholdAlertInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// notifyThresholdAlertUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type notifyThresholdAlertUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - in usecases.NotifyThresholdAlertInput
func (_e *notifyThresholdAlertUseCase_Expecter) Execute(ctx any, in any) *notifyThresholdAlertUseCase_Execute_Call {
	return &notifyThresholdAlertUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, in)}
}

func (_c *notifyThresholdAlertUseCase_Execute_Call) Run(run func(ctx context.Context, in usecases.NotifyThresholdAlertInput)) *notifyThresholdAlertUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 usecases.NotifyThresholdAlertInput
		if args[1] != nil {
			arg1 = args[1].(usecases.NotifyThresholdAlertInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *notifyThresholdAlertUseCase_Execute_Call) Return(notifyThresholdAlertResult usecases.NotifyThresholdAlertResult, err error) *notifyThresholdAlertUseCase_Execute_Call {
	_c.Call.Return(notifyThresholdAlertResult, err)
	return _c
}

func (_c *notifyThresholdAlertUseCase_Execute_Call) RunAndReturn(run func(ctx context.Context, in usecases.NotifyThresholdAlertInput) (usecases.NotifyThresholdAlertResult, error)) *notifyThresholdAlertUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
