// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entities "github.com/LimaTeixeiraTecnologia/mecontrola/internal/identity/domain/entities"

	mock "github.com/stretchr/testify/mock"

	output "github.com/LimaTeixeiraTecnologia/mecontrola/internal/billing/application/dtos/output"

	time "time"
)

// EntitlementCache is an autogenerated mock type for the EntitlementCache type
type EntitlementCache struct {
	mock.Mock
}

type EntitlementCache_Expecter struct {
	mock *mock.Mock
}

func (_m *EntitlementCache) EXPECT() *EntitlementCache_Expecter {
	return &EntitlementCache_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: userID
func (_m *EntitlementCache) Get(userID entities.UserID) (output.EntitlementDecision, bool) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 output.EntitlementDecision
	var r1 bool
	if rf, ok := ret.Get(0).(func(entities.UserID) (output.EntitlementDecision, bool)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(entities.UserID) output.EntitlementDecision); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(output.EntitlementDecision)
	}

	if rf, ok := ret.Get(1).(func(entities.UserID) bool); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// EntitlementCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type EntitlementCache_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - userID entities.UserID
func (_e *EntitlementCache_Expecter) Get(userID interface{}) *EntitlementCache_Get_Call {
	return &EntitlementCache_Get_Call{Call: _e.mock.On("Get", userID)}
}

func (_c *EntitlementCache_Get_Call) Run(run func(userID entities.UserID)) *EntitlementCache_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(entities.UserID))
	})
	return _c
}

func (_c *EntitlementCache_Get_Call) Return(_a0 output.EntitlementDecision, _a1 bool) *EntitlementCache_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EntitlementCache_Get_Call) RunAndReturn(run func(entities.UserID) (output.EntitlementDecision, bool)) *EntitlementCache_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Invalidate provides a mock function with given fields: userID
func (_m *EntitlementCache) Invalidate(userID entities.UserID) {
	_m.Called(userID)
}

// EntitlementCache_Invalidate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invalidate'
type EntitlementCache_Invalidate_Call struct {
	*mock.Call
}

// Invalidate is a helper method to define mock.On call
//   - userID entities.UserID
func (_e *EntitlementCache_Expecter) Invalidate(userID interface{}) *EntitlementCache_Invalidate_Call {
	return &EntitlementCache_Invalidate_Call{Call: _e.mock.On("Invalidate", userID)}
}

func (_c *EntitlementCache_Invalidate_Call) Run(run func(userID entities.UserID)) *EntitlementCache_Invalidate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(entities.UserID))
	})
	return _c
}

func (_c *EntitlementCache_Invalidate_Call) Return() *EntitlementCache_Invalidate_Call {
	_c.Call.Return()
	return _c
}

func (_c *EntitlementCache_Invalidate_Call) RunAndReturn(run func(entities.UserID)) *EntitlementCache_Invalidate_Call {
	_c.Run(run)
	return _c
}

// Set provides a mock function with given fields: userID, decision, ttl
func (_m *EntitlementCache) Set(userID entities.UserID, decision output.EntitlementDecision, ttl time.Duration) {
	_m.Called(userID, decision, ttl)
}

// EntitlementCache_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type EntitlementCache_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - userID entities.UserID
//   - decision output.EntitlementDecision
//   - ttl time.Duration
func (_e *EntitlementCache_Expecter) Set(userID interface{}, decision interface{}, ttl interface{}) *EntitlementCache_Set_Call {
	return &EntitlementCache_Set_Call{Call: _e.mock.On("Set", userID, decision, ttl)}
}

func (_c *EntitlementCache_Set_Call) Run(run func(userID entities.UserID, decision output.EntitlementDecision, ttl time.Duration)) *EntitlementCache_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(entities.UserID), args[1].(output.EntitlementDecision), args[2].(time.Duration))
	})
	return _c
}

func (_c *EntitlementCache_Set_Call) Return() *EntitlementCache_Set_Call {
	_c.Call.Return()
	return _c
}

func (_c *EntitlementCache_Set_Call) RunAndReturn(run func(entities.UserID, output.EntitlementDecision, time.Duration)) *EntitlementCache_Set_Call {
	_c.Run(run)
	return _c
}

// NewEntitlementCache creates a new instance of EntitlementCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEntitlementCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *EntitlementCache {
	mock := &EntitlementCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
