// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domainentities "github.com/LimaTeixeiraTecnologia/mecontrola/internal/billing/domain/entities"
	entities "github.com/LimaTeixeiraTecnologia/mecontrola/internal/identity/domain/entities"

	mock "github.com/stretchr/testify/mock"

	time "time"

	valueobjects "github.com/LimaTeixeiraTecnologia/mecontrola/internal/billing/domain/valueobjects"
)

// SubscriptionRepository is an autogenerated mock type for the SubscriptionRepository type
type SubscriptionRepository struct {
	mock.Mock
}

type SubscriptionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *SubscriptionRepository) EXPECT() *SubscriptionRepository_Expecter {
	return &SubscriptionRepository_Expecter{mock: &_m.Mock}
}

// FindActiveByUserID provides a mock function with given fields: ctx, userID
func (_m *SubscriptionRepository) FindActiveByUserID(ctx context.Context, userID entities.UserID) (*domainentities.Subscription, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindActiveByUserID")
	}

	var r0 *domainentities.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.UserID) (*domainentities.Subscription, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entities.UserID) *domainentities.Subscription); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domainentities.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entities.UserID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SubscriptionRepository_FindActiveByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindActiveByUserID'
type SubscriptionRepository_FindActiveByUserID_Call struct {
	*mock.Call
}

// FindActiveByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID entities.UserID
func (_e *SubscriptionRepository_Expecter) FindActiveByUserID(ctx interface{}, userID interface{}) *SubscriptionRepository_FindActiveByUserID_Call {
	return &SubscriptionRepository_FindActiveByUserID_Call{Call: _e.mock.On("FindActiveByUserID", ctx, userID)}
}

func (_c *SubscriptionRepository_FindActiveByUserID_Call) Run(run func(ctx context.Context, userID entities.UserID)) *SubscriptionRepository_FindActiveByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entities.UserID))
	})
	return _c
}

func (_c *SubscriptionRepository_FindActiveByUserID_Call) Return(_a0 *domainentities.Subscription, _a1 error) *SubscriptionRepository_FindActiveByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SubscriptionRepository_FindActiveByUserID_Call) RunAndReturn(run func(context.Context, entities.UserID) (*domainentities.Subscription, error)) *SubscriptionRepository_FindActiveByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// FindActiveByUserIDForUpdate provides a mock function with given fields: ctx, userID
func (_m *SubscriptionRepository) FindActiveByUserIDForUpdate(ctx context.Context, userID entities.UserID) (*domainentities.Subscription, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindActiveByUserIDForUpdate")
	}

	var r0 *domainentities.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.UserID) (*domainentities.Subscription, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entities.UserID) *domainentities.Subscription); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domainentities.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entities.UserID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SubscriptionRepository_FindActiveByUserIDForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindActiveByUserIDForUpdate'
type SubscriptionRepository_FindActiveByUserIDForUpdate_Call struct {
	*mock.Call
}

// FindActiveByUserIDForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - userID entities.UserID
func (_e *SubscriptionRepository_Expecter) FindActiveByUserIDForUpdate(ctx interface{}, userID interface{}) *SubscriptionRepository_FindActiveByUserIDForUpdate_Call {
	return &SubscriptionRepository_FindActiveByUserIDForUpdate_Call{Call: _e.mock.On("FindActiveByUserIDForUpdate", ctx, userID)}
}

func (_c *SubscriptionRepository_FindActiveByUserIDForUpdate_Call) Run(run func(ctx context.Context, userID entities.UserID)) *SubscriptionRepository_FindActiveByUserIDForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entities.UserID))
	})
	return _c
}

func (_c *SubscriptionRepository_FindActiveByUserIDForUpdate_Call) Return(_a0 *domainentities.Subscription, _a1 error) *SubscriptionRepository_FindActiveByUserIDForUpdate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SubscriptionRepository_FindActiveByUserIDForUpdate_Call) RunAndReturn(run func(context.Context, entities.UserID) (*domainentities.Subscription, error)) *SubscriptionRepository_FindActiveByUserIDForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// FindByExternalID provides a mock function with given fields: ctx, provider, externalID
func (_m *SubscriptionRepository) FindByExternalID(ctx context.Context, provider string, externalID valueobjects.ExternalSubscriptionID) (*domainentities.Subscription, error) {
	ret := _m.Called(ctx, provider, externalID)

	if len(ret) == 0 {
		panic("no return value specified for FindByExternalID")
	}

	var r0 *domainentities.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, valueobjects.ExternalSubscriptionID) (*domainentities.Subscription, error)); ok {
		return rf(ctx, provider, externalID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, valueobjects.ExternalSubscriptionID) *domainentities.Subscription); ok {
		r0 = rf(ctx, provider, externalID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domainentities.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, valueobjects.ExternalSubscriptionID) error); ok {
		r1 = rf(ctx, provider, externalID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SubscriptionRepository_FindByExternalID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByExternalID'
type SubscriptionRepository_FindByExternalID_Call struct {
	*mock.Call
}

// FindByExternalID is a helper method to define mock.On call
//   - ctx context.Context
//   - provider string
//   - externalID valueobjects.ExternalSubscriptionID
func (_e *SubscriptionRepository_Expecter) FindByExternalID(ctx interface{}, provider interface{}, externalID interface{}) *SubscriptionRepository_FindByExternalID_Call {
	return &SubscriptionRepository_FindByExternalID_Call{Call: _e.mock.On("FindByExternalID", ctx, provider, externalID)}
}

func (_c *SubscriptionRepository_FindByExternalID_Call) Run(run func(ctx context.Context, provider string, externalID valueobjects.ExternalSubscriptionID)) *SubscriptionRepository_FindByExternalID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(valueobjects.ExternalSubscriptionID))
	})
	return _c
}

func (_c *SubscriptionRepository_FindByExternalID_Call) Return(_a0 *domainentities.Subscription, _a1 error) *SubscriptionRepository_FindByExternalID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SubscriptionRepository_FindByExternalID_Call) RunAndReturn(run func(context.Context, string, valueobjects.ExternalSubscriptionID) (*domainentities.Subscription, error)) *SubscriptionRepository_FindByExternalID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByStatusInBatch provides a mock function with given fields: ctx, statuses, cursorCreatedAt, cursorID, limit
func (_m *SubscriptionRepository) ListByStatusInBatch(ctx context.Context, statuses []valueobjects.SubscriptionStatus, cursorCreatedAt time.Time, cursorID domainentities.SubscriptionID, limit int) ([]*domainentities.Subscription, error) {
	ret := _m.Called(ctx, statuses, cursorCreatedAt, cursorID, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListByStatusInBatch")
	}

	var r0 []*domainentities.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []valueobjects.SubscriptionStatus, time.Time, domainentities.SubscriptionID, int) ([]*domainentities.Subscription, error)); ok {
		return rf(ctx, statuses, cursorCreatedAt, cursorID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []valueobjects.SubscriptionStatus, time.Time, domainentities.SubscriptionID, int) []*domainentities.Subscription); ok {
		r0 = rf(ctx, statuses, cursorCreatedAt, cursorID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domainentities.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []valueobjects.SubscriptionStatus, time.Time, domainentities.SubscriptionID, int) error); ok {
		r1 = rf(ctx, statuses, cursorCreatedAt, cursorID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SubscriptionRepository_ListByStatusInBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByStatusInBatch'
type SubscriptionRepository_ListByStatusInBatch_Call struct {
	*mock.Call
}

// ListByStatusInBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - statuses []valueobjects.SubscriptionStatus
//   - cursorCreatedAt time.Time
//   - cursorID domainentities.SubscriptionID
//   - limit int
func (_e *SubscriptionRepository_Expecter) ListByStatusInBatch(ctx interface{}, statuses interface{}, cursorCreatedAt interface{}, cursorID interface{}, limit interface{}) *SubscriptionRepository_ListByStatusInBatch_Call {
	return &SubscriptionRepository_ListByStatusInBatch_Call{Call: _e.mock.On("ListByStatusInBatch", ctx, statuses, cursorCreatedAt, cursorID, limit)}
}

func (_c *SubscriptionRepository_ListByStatusInBatch_Call) Run(run func(ctx context.Context, statuses []valueobjects.SubscriptionStatus, cursorCreatedAt time.Time, cursorID domainentities.SubscriptionID, limit int)) *SubscriptionRepository_ListByStatusInBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]valueobjects.SubscriptionStatus), args[2].(time.Time), args[3].(domainentities.SubscriptionID), args[4].(int))
	})
	return _c
}

func (_c *SubscriptionRepository_ListByStatusInBatch_Call) Return(_a0 []*domainentities.Subscription, _a1 error) *SubscriptionRepository_ListByStatusInBatch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SubscriptionRepository_ListByStatusInBatch_Call) RunAndReturn(run func(context.Context, []valueobjects.SubscriptionStatus, time.Time, domainentities.SubscriptionID, int) ([]*domainentities.Subscription, error)) *SubscriptionRepository_ListByStatusInBatch_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function with given fields: ctx, sub
func (_m *SubscriptionRepository) Upsert(ctx context.Context, sub *domainentities.Subscription) error {
	ret := _m.Called(ctx, sub)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domainentities.Subscription) error); ok {
		r0 = rf(ctx, sub)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SubscriptionRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type SubscriptionRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - sub *domainentities.Subscription
func (_e *SubscriptionRepository_Expecter) Upsert(ctx interface{}, sub interface{}) *SubscriptionRepository_Upsert_Call {
	return &SubscriptionRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, sub)}
}

func (_c *SubscriptionRepository_Upsert_Call) Run(run func(ctx context.Context, sub *domainentities.Subscription)) *SubscriptionRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domainentities.Subscription))
	})
	return _c
}

func (_c *SubscriptionRepository_Upsert_Call) Return(_a0 error) *SubscriptionRepository_Upsert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SubscriptionRepository_Upsert_Call) RunAndReturn(run func(context.Context, *domainentities.Subscription) error) *SubscriptionRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewSubscriptionRepository creates a new instance of SubscriptionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSubscriptionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SubscriptionRepository {
	mock := &SubscriptionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
