// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/LimaTeixeiraTecnologia/mecontrola/internal/identity/domain/entities"

	mock "github.com/stretchr/testify/mock"

	valueobjects "github.com/LimaTeixeiraTecnologia/mecontrola/internal/identity/domain/valueobjects"
)

// UserResolver is an autogenerated mock type for the UserResolver type
type UserResolver struct {
	mock.Mock
}

type UserResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *UserResolver) EXPECT() *UserResolver_Expecter {
	return &UserResolver_Expecter{mock: &_m.Mock}
}

// UpsertByWhatsAppNumber provides a mock function with given fields: ctx, number
func (_m *UserResolver) UpsertByWhatsAppNumber(ctx context.Context, number valueobjects.WhatsAppNumber) (*entities.User, error) {
	ret := _m.Called(ctx, number)

	if len(ret) == 0 {
		panic("no return value specified for UpsertByWhatsAppNumber")
	}

	var r0 *entities.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobjects.WhatsAppNumber) (*entities.User, error)); ok {
		return rf(ctx, number)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobjects.WhatsAppNumber) *entities.User); ok {
		r0 = rf(ctx, number)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobjects.WhatsAppNumber) error); ok {
		r1 = rf(ctx, number)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserResolver_UpsertByWhatsAppNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertByWhatsAppNumber'
type UserResolver_UpsertByWhatsAppNumber_Call struct {
	*mock.Call
}

// UpsertByWhatsAppNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - number valueobjects.WhatsAppNumber
func (_e *UserResolver_Expecter) UpsertByWhatsAppNumber(ctx interface{}, number interface{}) *UserResolver_UpsertByWhatsAppNumber_Call {
	return &UserResolver_UpsertByWhatsAppNumber_Call{Call: _e.mock.On("UpsertByWhatsAppNumber", ctx, number)}
}

func (_c *UserResolver_UpsertByWhatsAppNumber_Call) Run(run func(ctx context.Context, number valueobjects.WhatsAppNumber)) *UserResolver_UpsertByWhatsAppNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobjects.WhatsAppNumber))
	})
	return _c
}

func (_c *UserResolver_UpsertByWhatsAppNumber_Call) Return(_a0 *entities.User, _a1 error) *UserResolver_UpsertByWhatsAppNumber_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserResolver_UpsertByWhatsAppNumber_Call) RunAndReturn(run func(context.Context, valueobjects.WhatsAppNumber) (*entities.User, error)) *UserResolver_UpsertByWhatsAppNumber_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserResolver creates a new instance of UserResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserResolver {
	mock := &UserResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
