// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/LimaTeixeiraTecnologia/mecontrola/internal/billing/domain/entities"

	json "encoding/json"

	mock "github.com/stretchr/testify/mock"

	time "time"

	valueobjects "github.com/LimaTeixeiraTecnologia/mecontrola/internal/billing/domain/valueobjects"
)

// WebhookEventRepository is an autogenerated mock type for the WebhookEventRepository type
type WebhookEventRepository struct {
	mock.Mock
}

type WebhookEventRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *WebhookEventRepository) EXPECT() *WebhookEventRepository_Expecter {
	return &WebhookEventRepository_Expecter{mock: &_m.Mock}
}

// Anonymize provides a mock function with given fields: ctx, id, redacted, at
func (_m *WebhookEventRepository) Anonymize(ctx context.Context, id valueobjects.WebhookEventID, redacted json.RawMessage, at time.Time) error {
	ret := _m.Called(ctx, id, redacted, at)

	if len(ret) == 0 {
		panic("no return value specified for Anonymize")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobjects.WebhookEventID, json.RawMessage, time.Time) error); ok {
		r0 = rf(ctx, id, redacted, at)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WebhookEventRepository_Anonymize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Anonymize'
type WebhookEventRepository_Anonymize_Call struct {
	*mock.Call
}

// Anonymize is a helper method to define mock.On call
//   - ctx context.Context
//   - id valueobjects.WebhookEventID
//   - redacted json.RawMessage
//   - at time.Time
func (_e *WebhookEventRepository_Expecter) Anonymize(ctx interface{}, id interface{}, redacted interface{}, at interface{}) *WebhookEventRepository_Anonymize_Call {
	return &WebhookEventRepository_Anonymize_Call{Call: _e.mock.On("Anonymize", ctx, id, redacted, at)}
}

func (_c *WebhookEventRepository_Anonymize_Call) Run(run func(ctx context.Context, id valueobjects.WebhookEventID, redacted json.RawMessage, at time.Time)) *WebhookEventRepository_Anonymize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobjects.WebhookEventID), args[2].(json.RawMessage), args[3].(time.Time))
	})
	return _c
}

func (_c *WebhookEventRepository_Anonymize_Call) Return(_a0 error) *WebhookEventRepository_Anonymize_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WebhookEventRepository_Anonymize_Call) RunAndReturn(run func(context.Context, valueobjects.WebhookEventID, json.RawMessage, time.Time) error) *WebhookEventRepository_Anonymize_Call {
	_c.Call.Return(run)
	return _c
}

// FindRawPayload provides a mock function with given fields: ctx, id
func (_m *WebhookEventRepository) FindRawPayload(ctx context.Context, id valueobjects.WebhookEventID) (json.RawMessage, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindRawPayload")
	}

	var r0 json.RawMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobjects.WebhookEventID) (json.RawMessage, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobjects.WebhookEventID) json.RawMessage); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobjects.WebhookEventID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WebhookEventRepository_FindRawPayload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindRawPayload'
type WebhookEventRepository_FindRawPayload_Call struct {
	*mock.Call
}

// FindRawPayload is a helper method to define mock.On call
//   - ctx context.Context
//   - id valueobjects.WebhookEventID
func (_e *WebhookEventRepository_Expecter) FindRawPayload(ctx interface{}, id interface{}) *WebhookEventRepository_FindRawPayload_Call {
	return &WebhookEventRepository_FindRawPayload_Call{Call: _e.mock.On("FindRawPayload", ctx, id)}
}

func (_c *WebhookEventRepository_FindRawPayload_Call) Run(run func(ctx context.Context, id valueobjects.WebhookEventID)) *WebhookEventRepository_FindRawPayload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobjects.WebhookEventID))
	})
	return _c
}

func (_c *WebhookEventRepository_FindRawPayload_Call) Return(_a0 json.RawMessage, _a1 error) *WebhookEventRepository_FindRawPayload_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WebhookEventRepository_FindRawPayload_Call) RunAndReturn(run func(context.Context, valueobjects.WebhookEventID) (json.RawMessage, error)) *WebhookEventRepository_FindRawPayload_Call {
	_c.Call.Return(run)
	return _c
}

// InsertIfNew provides a mock function with given fields: ctx, event
func (_m *WebhookEventRepository) InsertIfNew(ctx context.Context, event entities.WebhookEvent) (bool, error) {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for InsertIfNew")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.WebhookEvent) (bool, error)); ok {
		return rf(ctx, event)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entities.WebhookEvent) bool); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entities.WebhookEvent) error); ok {
		r1 = rf(ctx, event)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WebhookEventRepository_InsertIfNew_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertIfNew'
type WebhookEventRepository_InsertIfNew_Call struct {
	*mock.Call
}

// InsertIfNew is a helper method to define mock.On call
//   - ctx context.Context
//   - event entities.WebhookEvent
func (_e *WebhookEventRepository_Expecter) InsertIfNew(ctx interface{}, event interface{}) *WebhookEventRepository_InsertIfNew_Call {
	return &WebhookEventRepository_InsertIfNew_Call{Call: _e.mock.On("InsertIfNew", ctx, event)}
}

func (_c *WebhookEventRepository_InsertIfNew_Call) Run(run func(ctx context.Context, event entities.WebhookEvent)) *WebhookEventRepository_InsertIfNew_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entities.WebhookEvent))
	})
	return _c
}

func (_c *WebhookEventRepository_InsertIfNew_Call) Return(inserted bool, err error) *WebhookEventRepository_InsertIfNew_Call {
	_c.Call.Return(inserted, err)
	return _c
}

func (_c *WebhookEventRepository_InsertIfNew_Call) RunAndReturn(run func(context.Context, entities.WebhookEvent) (bool, error)) *WebhookEventRepository_InsertIfNew_Call {
	_c.Call.Return(run)
	return _c
}

// ListPendingAnonymization provides a mock function with given fields: ctx, olderThan, limit
func (_m *WebhookEventRepository) ListPendingAnonymization(ctx context.Context, olderThan time.Time, limit int) ([]entities.WebhookEvent, error) {
	ret := _m.Called(ctx, olderThan, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListPendingAnonymization")
	}

	var r0 []entities.WebhookEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, int) ([]entities.WebhookEvent, error)); ok {
		return rf(ctx, olderThan, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, int) []entities.WebhookEvent); ok {
		r0 = rf(ctx, olderThan, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.WebhookEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, int) error); ok {
		r1 = rf(ctx, olderThan, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WebhookEventRepository_ListPendingAnonymization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPendingAnonymization'
type WebhookEventRepository_ListPendingAnonymization_Call struct {
	*mock.Call
}

// ListPendingAnonymization is a helper method to define mock.On call
//   - ctx context.Context
//   - olderThan time.Time
//   - limit int
func (_e *WebhookEventRepository_Expecter) ListPendingAnonymization(ctx interface{}, olderThan interface{}, limit interface{}) *WebhookEventRepository_ListPendingAnonymization_Call {
	return &WebhookEventRepository_ListPendingAnonymization_Call{Call: _e.mock.On("ListPendingAnonymization", ctx, olderThan, limit)}
}

func (_c *WebhookEventRepository_ListPendingAnonymization_Call) Run(run func(ctx context.Context, olderThan time.Time, limit int)) *WebhookEventRepository_ListPendingAnonymization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time), args[2].(int))
	})
	return _c
}

func (_c *WebhookEventRepository_ListPendingAnonymization_Call) Return(_a0 []entities.WebhookEvent, _a1 error) *WebhookEventRepository_ListPendingAnonymization_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WebhookEventRepository_ListPendingAnonymization_Call) RunAndReturn(run func(context.Context, time.Time, int) ([]entities.WebhookEvent, error)) *WebhookEventRepository_ListPendingAnonymization_Call {
	_c.Call.Return(run)
	return _c
}

// MarkProcessed provides a mock function with given fields: ctx, id, at
func (_m *WebhookEventRepository) MarkProcessed(ctx context.Context, id valueobjects.WebhookEventID, at time.Time) error {
	ret := _m.Called(ctx, id, at)

	if len(ret) == 0 {
		panic("no return value specified for MarkProcessed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobjects.WebhookEventID, time.Time) error); ok {
		r0 = rf(ctx, id, at)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WebhookEventRepository_MarkProcessed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkProcessed'
type WebhookEventRepository_MarkProcessed_Call struct {
	*mock.Call
}

// MarkProcessed is a helper method to define mock.On call
//   - ctx context.Context
//   - id valueobjects.WebhookEventID
//   - at time.Time
func (_e *WebhookEventRepository_Expecter) MarkProcessed(ctx interface{}, id interface{}, at interface{}) *WebhookEventRepository_MarkProcessed_Call {
	return &WebhookEventRepository_MarkProcessed_Call{Call: _e.mock.On("MarkProcessed", ctx, id, at)}
}

func (_c *WebhookEventRepository_MarkProcessed_Call) Run(run func(ctx context.Context, id valueobjects.WebhookEventID, at time.Time)) *WebhookEventRepository_MarkProcessed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobjects.WebhookEventID), args[2].(time.Time))
	})
	return _c
}

func (_c *WebhookEventRepository_MarkProcessed_Call) Return(_a0 error) *WebhookEventRepository_MarkProcessed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WebhookEventRepository_MarkProcessed_Call) RunAndReturn(run func(context.Context, valueobjects.WebhookEventID, time.Time) error) *WebhookEventRepository_MarkProcessed_Call {
	_c.Call.Return(run)
	return _c
}

// RecordApplication provides a mock function with given fields: ctx, eventID, subID, at
func (_m *WebhookEventRepository) RecordApplication(ctx context.Context, eventID valueobjects.WebhookEventID, subID entities.SubscriptionID, at time.Time) (bool, error) {
	ret := _m.Called(ctx, eventID, subID, at)

	if len(ret) == 0 {
		panic("no return value specified for RecordApplication")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobjects.WebhookEventID, entities.SubscriptionID, time.Time) (bool, error)); ok {
		return rf(ctx, eventID, subID, at)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobjects.WebhookEventID, entities.SubscriptionID, time.Time) bool); ok {
		r0 = rf(ctx, eventID, subID, at)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobjects.WebhookEventID, entities.SubscriptionID, time.Time) error); ok {
		r1 = rf(ctx, eventID, subID, at)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WebhookEventRepository_RecordApplication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordApplication'
type WebhookEventRepository_RecordApplication_Call struct {
	*mock.Call
}

// RecordApplication is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID valueobjects.WebhookEventID
//   - subID entities.SubscriptionID
//   - at time.Time
func (_e *WebhookEventRepository_Expecter) RecordApplication(ctx interface{}, eventID interface{}, subID interface{}, at interface{}) *WebhookEventRepository_RecordApplication_Call {
	return &WebhookEventRepository_RecordApplication_Call{Call: _e.mock.On("RecordApplication", ctx, eventID, subID, at)}
}

func (_c *WebhookEventRepository_RecordApplication_Call) Run(run func(ctx context.Context, eventID valueobjects.WebhookEventID, subID entities.SubscriptionID, at time.Time)) *WebhookEventRepository_RecordApplication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobjects.WebhookEventID), args[2].(entities.SubscriptionID), args[3].(time.Time))
	})
	return _c
}

func (_c *WebhookEventRepository_RecordApplication_Call) Return(recorded bool, err error) *WebhookEventRepository_RecordApplication_Call {
	_c.Call.Return(recorded, err)
	return _c
}

func (_c *WebhookEventRepository_RecordApplication_Call) RunAndReturn(run func(context.Context, valueobjects.WebhookEventID, entities.SubscriptionID, time.Time) (bool, error)) *WebhookEventRepository_RecordApplication_Call {
	_c.Call.Return(run)
	return _c
}

// NewWebhookEventRepository creates a new instance of WebhookEventRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWebhookEventRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *WebhookEventRepository {
	mock := &WebhookEventRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
