// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewKiwifyEventRepository creates a new instance of KiwifyEventRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKiwifyEventRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *KiwifyEventRepository {
	mock := &KiwifyEventRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// KiwifyEventRepository is an autogenerated mock type for the KiwifyEventRepository type
type KiwifyEventRepository struct {
	mock.Mock
}

type KiwifyEventRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *KiwifyEventRepository) EXPECT() *KiwifyEventRepository_Expecter {
	return &KiwifyEventRepository_Expecter{mock: &_m.Mock}
}

// DeleteOlderThan provides a mock function for the type KiwifyEventRepository
func (_mock *KiwifyEventRepository) DeleteOlderThan(ctx context.Context, before time.Time, limit int) (int64, error) {
	ret := _mock.Called(ctx, before, limit)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOlderThan")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, int) (int64, error)); ok {
		return returnFunc(ctx, before, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, int) int64); ok {
		r0 = returnFunc(ctx, before, limit)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time, int) error); ok {
		r1 = returnFunc(ctx, before, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// KiwifyEventRepository_DeleteOlderThan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOlderThan'
type KiwifyEventRepository_DeleteOlderThan_Call struct {
	*mock.Call
}

// DeleteOlderThan is a helper method to define mock.On call
//   - ctx context.Context
//   - before time.Time
//   - limit int
func (_e *KiwifyEventRepository_Expecter) DeleteOlderThan(ctx interface{}, before interface{}, limit interface{}) *KiwifyEventRepository_DeleteOlderThan_Call {
	return &KiwifyEventRepository_DeleteOlderThan_Call{Call: _e.mock.On("DeleteOlderThan", ctx, before, limit)}
}

func (_c *KiwifyEventRepository_DeleteOlderThan_Call) Run(run func(ctx context.Context, before time.Time, limit int)) *KiwifyEventRepository_DeleteOlderThan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *KiwifyEventRepository_DeleteOlderThan_Call) Return(n int64, err error) *KiwifyEventRepository_DeleteOlderThan_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *KiwifyEventRepository_DeleteOlderThan_Call) RunAndReturn(run func(ctx context.Context, before time.Time, limit int) (int64, error)) *KiwifyEventRepository_DeleteOlderThan_Call {
	_c.Call.Return(run)
	return _c
}

// MarkProcessed provides a mock function for the type KiwifyEventRepository
func (_mock *KiwifyEventRepository) MarkProcessed(ctx context.Context, envelopeID string, processedAt time.Time) error {
	ret := _mock.Called(ctx, envelopeID, processedAt)

	if len(ret) == 0 {
		panic("no return value specified for MarkProcessed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = returnFunc(ctx, envelopeID, processedAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// KiwifyEventRepository_MarkProcessed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkProcessed'
type KiwifyEventRepository_MarkProcessed_Call struct {
	*mock.Call
}

// MarkProcessed is a helper method to define mock.On call
//   - ctx context.Context
//   - envelopeID string
//   - processedAt time.Time
func (_e *KiwifyEventRepository_Expecter) MarkProcessed(ctx interface{}, envelopeID interface{}, processedAt interface{}) *KiwifyEventRepository_MarkProcessed_Call {
	return &KiwifyEventRepository_MarkProcessed_Call{Call: _e.mock.On("MarkProcessed", ctx, envelopeID, processedAt)}
}

func (_c *KiwifyEventRepository_MarkProcessed_Call) Run(run func(ctx context.Context, envelopeID string, processedAt time.Time)) *KiwifyEventRepository_MarkProcessed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *KiwifyEventRepository_MarkProcessed_Call) Return(err error) *KiwifyEventRepository_MarkProcessed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *KiwifyEventRepository_MarkProcessed_Call) RunAndReturn(run func(ctx context.Context, envelopeID string, processedAt time.Time) error) *KiwifyEventRepository_MarkProcessed_Call {
	_c.Call.Return(run)
	return _c
}

// Persist provides a mock function for the type KiwifyEventRepository
func (_mock *KiwifyEventRepository) Persist(ctx context.Context, envelopeID string, trigger string, rawBody []byte, signatureStatus string) error {
	ret := _mock.Called(ctx, envelopeID, trigger, rawBody, signatureStatus)

	if len(ret) == 0 {
		panic("no return value specified for Persist")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []byte, string) error); ok {
		r0 = returnFunc(ctx, envelopeID, trigger, rawBody, signatureStatus)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// KiwifyEventRepository_Persist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Persist'
type KiwifyEventRepository_Persist_Call struct {
	*mock.Call
}

// Persist is a helper method to define mock.On call
//   - ctx context.Context
//   - envelopeID string
//   - trigger string
//   - rawBody []byte
//   - signatureStatus string
func (_e *KiwifyEventRepository_Expecter) Persist(ctx interface{}, envelopeID interface{}, trigger interface{}, rawBody interface{}, signatureStatus interface{}) *KiwifyEventRepository_Persist_Call {
	return &KiwifyEventRepository_Persist_Call{Call: _e.mock.On("Persist", ctx, envelopeID, trigger, rawBody, signatureStatus)}
}

func (_c *KiwifyEventRepository_Persist_Call) Run(run func(ctx context.Context, envelopeID string, trigger string, rawBody []byte, signatureStatus string)) *KiwifyEventRepository_Persist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *KiwifyEventRepository_Persist_Call) Return(err error) *KiwifyEventRepository_Persist_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *KiwifyEventRepository_Persist_Call) RunAndReturn(run func(ctx context.Context, envelopeID string, trigger string, rawBody []byte, signatureStatus string) error) *KiwifyEventRepository_Persist_Call {
	_c.Call.Return(run)
	return _c
}
