// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	interfaces "github.com/LimaTeixeiraTecnologia/mecontrola/internal/billing/application/interfaces"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// KiwifyClient is an autogenerated mock type for the KiwifyClient type
type KiwifyClient struct {
	mock.Mock
}

type KiwifyClient_Expecter struct {
	mock *mock.Mock
}

func (_m *KiwifyClient) EXPECT() *KiwifyClient_Expecter {
	return &KiwifyClient_Expecter{mock: &_m.Mock}
}

// GetSale provides a mock function with given fields: ctx, saleID
func (_m *KiwifyClient) GetSale(ctx context.Context, saleID string) (interfaces.KiwifySale, error) {
	ret := _m.Called(ctx, saleID)

	if len(ret) == 0 {
		panic("no return value specified for GetSale")
	}

	var r0 interfaces.KiwifySale
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (interfaces.KiwifySale, error)); ok {
		return rf(ctx, saleID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) interfaces.KiwifySale); ok {
		r0 = rf(ctx, saleID)
	} else {
		r0 = ret.Get(0).(interfaces.KiwifySale)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, saleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// KiwifyClient_GetSale_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSale'
type KiwifyClient_GetSale_Call struct {
	*mock.Call
}

// GetSale is a helper method to define mock.On call
//   - ctx context.Context
//   - saleID string
func (_e *KiwifyClient_Expecter) GetSale(ctx interface{}, saleID interface{}) *KiwifyClient_GetSale_Call {
	return &KiwifyClient_GetSale_Call{Call: _e.mock.On("GetSale", ctx, saleID)}
}

func (_c *KiwifyClient_GetSale_Call) Run(run func(ctx context.Context, saleID string)) *KiwifyClient_GetSale_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *KiwifyClient_GetSale_Call) Return(_a0 interfaces.KiwifySale, _a1 error) *KiwifyClient_GetSale_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *KiwifyClient_GetSale_Call) RunAndReturn(run func(context.Context, string) (interfaces.KiwifySale, error)) *KiwifyClient_GetSale_Call {
	_c.Call.Return(run)
	return _c
}

// ListSalesUpdatedSince provides a mock function with given fields: ctx, windowStart, windowEnd, page
func (_m *KiwifyClient) ListSalesUpdatedSince(ctx context.Context, windowStart time.Time, windowEnd time.Time, page int) (interfaces.KiwifySalePage, error) {
	ret := _m.Called(ctx, windowStart, windowEnd, page)

	if len(ret) == 0 {
		panic("no return value specified for ListSalesUpdatedSince")
	}

	var r0 interfaces.KiwifySalePage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, int) (interfaces.KiwifySalePage, error)); ok {
		return rf(ctx, windowStart, windowEnd, page)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, int) interfaces.KiwifySalePage); ok {
		r0 = rf(ctx, windowStart, windowEnd, page)
	} else {
		r0 = ret.Get(0).(interfaces.KiwifySalePage)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time, int) error); ok {
		r1 = rf(ctx, windowStart, windowEnd, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// KiwifyClient_ListSalesUpdatedSince_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSalesUpdatedSince'
type KiwifyClient_ListSalesUpdatedSince_Call struct {
	*mock.Call
}

// ListSalesUpdatedSince is a helper method to define mock.On call
//   - ctx context.Context
//   - windowStart time.Time
//   - windowEnd time.Time
//   - page int
func (_e *KiwifyClient_Expecter) ListSalesUpdatedSince(ctx interface{}, windowStart interface{}, windowEnd interface{}, page interface{}) *KiwifyClient_ListSalesUpdatedSince_Call {
	return &KiwifyClient_ListSalesUpdatedSince_Call{Call: _e.mock.On("ListSalesUpdatedSince", ctx, windowStart, windowEnd, page)}
}

func (_c *KiwifyClient_ListSalesUpdatedSince_Call) Run(run func(ctx context.Context, windowStart time.Time, windowEnd time.Time, page int)) *KiwifyClient_ListSalesUpdatedSince_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time), args[2].(time.Time), args[3].(int))
	})
	return _c
}

func (_c *KiwifyClient_ListSalesUpdatedSince_Call) Return(_a0 interfaces.KiwifySalePage, _a1 error) *KiwifyClient_ListSalesUpdatedSince_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *KiwifyClient_ListSalesUpdatedSince_Call) RunAndReturn(run func(context.Context, time.Time, time.Time, int) (interfaces.KiwifySalePage, error)) *KiwifyClient_ListSalesUpdatedSince_Call {
	_c.Call.Return(run)
	return _c
}

// NewKiwifyClient creates a new instance of KiwifyClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKiwifyClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *KiwifyClient {
	mock := &KiwifyClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
