// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	input "github.com/LimaTeixeiraTecnologia/mecontrola/internal/billing/application/dtos/input"
	mock "github.com/stretchr/testify/mock"
)

// ProcessSubscriptionLate is an autogenerated mock type for the processSubscriptionLate type
type ProcessSubscriptionLate struct {
	mock.Mock
}

type ProcessSubscriptionLate_Expecter struct {
	mock *mock.Mock
}

func (_m *ProcessSubscriptionLate) EXPECT() *ProcessSubscriptionLate_Expecter {
	return &ProcessSubscriptionLate_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, in
func (_m *ProcessSubscriptionLate) Execute(ctx context.Context, in input.ProcessSubscriptionLateInput) error {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, input.ProcessSubscriptionLateInput) error); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProcessSubscriptionLate_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ProcessSubscriptionLate_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - in input.ProcessSubscriptionLateInput
func (_e *ProcessSubscriptionLate_Expecter) Execute(ctx interface{}, in interface{}) *ProcessSubscriptionLate_Execute_Call {
	return &ProcessSubscriptionLate_Execute_Call{Call: _e.mock.On("Execute", ctx, in)}
}

func (_c *ProcessSubscriptionLate_Execute_Call) Run(run func(ctx context.Context, in input.ProcessSubscriptionLateInput)) *ProcessSubscriptionLate_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(input.ProcessSubscriptionLateInput))
	})
	return _c
}

func (_c *ProcessSubscriptionLate_Execute_Call) Return(_a0 error) *ProcessSubscriptionLate_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProcessSubscriptionLate_Execute_Call) RunAndReturn(run func(context.Context, input.ProcessSubscriptionLateInput) error) *ProcessSubscriptionLate_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewProcessSubscriptionLate creates a new instance of ProcessSubscriptionLate. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProcessSubscriptionLate(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProcessSubscriptionLate {
	mock := &ProcessSubscriptionLate{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
