// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	input "github.com/LimaTeixeiraTecnologia/mecontrola/internal/billing/application/dtos/input"
	mock "github.com/stretchr/testify/mock"
)

// ProcessSubscriptionCanceled is an autogenerated mock type for the processSubscriptionCanceled type
type ProcessSubscriptionCanceled struct {
	mock.Mock
}

type ProcessSubscriptionCanceled_Expecter struct {
	mock *mock.Mock
}

func (_m *ProcessSubscriptionCanceled) EXPECT() *ProcessSubscriptionCanceled_Expecter {
	return &ProcessSubscriptionCanceled_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, in
func (_m *ProcessSubscriptionCanceled) Execute(ctx context.Context, in input.ProcessSubscriptionCanceledInput) error {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, input.ProcessSubscriptionCanceledInput) error); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProcessSubscriptionCanceled_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ProcessSubscriptionCanceled_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - in input.ProcessSubscriptionCanceledInput
func (_e *ProcessSubscriptionCanceled_Expecter) Execute(ctx interface{}, in interface{}) *ProcessSubscriptionCanceled_Execute_Call {
	return &ProcessSubscriptionCanceled_Execute_Call{Call: _e.mock.On("Execute", ctx, in)}
}

func (_c *ProcessSubscriptionCanceled_Execute_Call) Run(run func(ctx context.Context, in input.ProcessSubscriptionCanceledInput)) *ProcessSubscriptionCanceled_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(input.ProcessSubscriptionCanceledInput))
	})
	return _c
}

func (_c *ProcessSubscriptionCanceled_Execute_Call) Return(_a0 error) *ProcessSubscriptionCanceled_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProcessSubscriptionCanceled_Execute_Call) RunAndReturn(run func(context.Context, input.ProcessSubscriptionCanceledInput) error) *ProcessSubscriptionCanceled_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewProcessSubscriptionCanceled creates a new instance of ProcessSubscriptionCanceled. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProcessSubscriptionCanceled(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProcessSubscriptionCanceled {
	mock := &ProcessSubscriptionCanceled{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
