// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// ProcessedEventRepository is an autogenerated mock type for the ProcessedEventRepository type
type ProcessedEventRepository struct {
	mock.Mock
}

type ProcessedEventRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ProcessedEventRepository) EXPECT() *ProcessedEventRepository_Expecter {
	return &ProcessedEventRepository_Expecter{mock: &_m.Mock}
}

// MarkApplied provides a mock function with given fields: ctx, eventKey, trigger, recursoID, occurredAt
func (_m *ProcessedEventRepository) MarkApplied(ctx context.Context, eventKey string, trigger string, recursoID string, occurredAt time.Time) error {
	ret := _m.Called(ctx, eventKey, trigger, recursoID, occurredAt)

	if len(ret) == 0 {
		panic("no return value specified for MarkApplied")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, time.Time) error); ok {
		r0 = rf(ctx, eventKey, trigger, recursoID, occurredAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProcessedEventRepository_MarkApplied_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkApplied'
type ProcessedEventRepository_MarkApplied_Call struct {
	*mock.Call
}

// MarkApplied is a helper method to define mock.On call
//   - ctx context.Context
//   - eventKey string
//   - trigger string
//   - recursoID string
//   - occurredAt time.Time
func (_e *ProcessedEventRepository_Expecter) MarkApplied(ctx interface{}, eventKey interface{}, trigger interface{}, recursoID interface{}, occurredAt interface{}) *ProcessedEventRepository_MarkApplied_Call {
	return &ProcessedEventRepository_MarkApplied_Call{Call: _e.mock.On("MarkApplied", ctx, eventKey, trigger, recursoID, occurredAt)}
}

func (_c *ProcessedEventRepository_MarkApplied_Call) Run(run func(ctx context.Context, eventKey string, trigger string, recursoID string, occurredAt time.Time)) *ProcessedEventRepository_MarkApplied_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(time.Time))
	})
	return _c
}

func (_c *ProcessedEventRepository_MarkApplied_Call) Return(_a0 error) *ProcessedEventRepository_MarkApplied_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProcessedEventRepository_MarkApplied_Call) RunAndReturn(run func(context.Context, string, string, string, time.Time) error) *ProcessedEventRepository_MarkApplied_Call {
	_c.Call.Return(run)
	return _c
}

// MarkSuperseded provides a mock function with given fields: ctx, eventKey
func (_m *ProcessedEventRepository) MarkSuperseded(ctx context.Context, eventKey string) error {
	ret := _m.Called(ctx, eventKey)

	if len(ret) == 0 {
		panic("no return value specified for MarkSuperseded")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, eventKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProcessedEventRepository_MarkSuperseded_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkSuperseded'
type ProcessedEventRepository_MarkSuperseded_Call struct {
	*mock.Call
}

// MarkSuperseded is a helper method to define mock.On call
//   - ctx context.Context
//   - eventKey string
func (_e *ProcessedEventRepository_Expecter) MarkSuperseded(ctx interface{}, eventKey interface{}) *ProcessedEventRepository_MarkSuperseded_Call {
	return &ProcessedEventRepository_MarkSuperseded_Call{Call: _e.mock.On("MarkSuperseded", ctx, eventKey)}
}

func (_c *ProcessedEventRepository_MarkSuperseded_Call) Run(run func(ctx context.Context, eventKey string)) *ProcessedEventRepository_MarkSuperseded_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ProcessedEventRepository_MarkSuperseded_Call) Return(_a0 error) *ProcessedEventRepository_MarkSuperseded_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProcessedEventRepository_MarkSuperseded_Call) RunAndReturn(run func(context.Context, string) error) *ProcessedEventRepository_MarkSuperseded_Call {
	_c.Call.Return(run)
	return _c
}

// NewProcessedEventRepository creates a new instance of ProcessedEventRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProcessedEventRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProcessedEventRepository {
	mock := &ProcessedEventRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
