// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	input "github.com/LimaTeixeiraTecnologia/mecontrola/internal/billing/application/dtos/input"
	mock "github.com/stretchr/testify/mock"
)

// ProcessSaleApproved is an autogenerated mock type for the processSaleApproved type
type ProcessSaleApproved struct {
	mock.Mock
}

type ProcessSaleApproved_Expecter struct {
	mock *mock.Mock
}

func (_m *ProcessSaleApproved) EXPECT() *ProcessSaleApproved_Expecter {
	return &ProcessSaleApproved_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, in
func (_m *ProcessSaleApproved) Execute(ctx context.Context, in input.ProcessSaleApprovedInput) error {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, input.ProcessSaleApprovedInput) error); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProcessSaleApproved_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ProcessSaleApproved_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - in input.ProcessSaleApprovedInput
func (_e *ProcessSaleApproved_Expecter) Execute(ctx interface{}, in interface{}) *ProcessSaleApproved_Execute_Call {
	return &ProcessSaleApproved_Execute_Call{Call: _e.mock.On("Execute", ctx, in)}
}

func (_c *ProcessSaleApproved_Execute_Call) Run(run func(ctx context.Context, in input.ProcessSaleApprovedInput)) *ProcessSaleApproved_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(input.ProcessSaleApprovedInput))
	})
	return _c
}

func (_c *ProcessSaleApproved_Execute_Call) Return(_a0 error) *ProcessSaleApproved_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProcessSaleApproved_Execute_Call) RunAndReturn(run func(context.Context, input.ProcessSaleApprovedInput) error) *ProcessSaleApproved_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewProcessSaleApproved creates a new instance of ProcessSaleApproved. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProcessSaleApproved(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProcessSaleApproved {
	mock := &ProcessSaleApproved{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
