// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/LimaTeixeiraTecnologia/mecontrola/internal/billing/application/dtos/input"
	mock "github.com/stretchr/testify/mock"
)

// newProcessRefundOrChargeback creates a new instance of processRefundOrChargeback. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newProcessRefundOrChargeback(t interface {
	mock.TestingT
	Cleanup(func())
}) *processRefundOrChargeback {
	mock := &processRefundOrChargeback{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// processRefundOrChargeback is an autogenerated mock type for the processRefundOrChargeback type
type processRefundOrChargeback struct {
	mock.Mock
}

type processRefundOrChargeback_Expecter struct {
	mock *mock.Mock
}

func (_m *processRefundOrChargeback) EXPECT() *processRefundOrChargeback_Expecter {
	return &processRefundOrChargeback_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type processRefundOrChargeback
func (_mock *processRefundOrChargeback) Execute(ctx context.Context, in input.ProcessRefundOrChargebackInput) error {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, input.ProcessRefundOrChargebackInput) error); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// processRefundOrChargeback_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type processRefundOrChargeback_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - in input.ProcessRefundOrChargebackInput
func (_e *processRefundOrChargeback_Expecter) Execute(ctx any, in any) *processRefundOrChargeback_Execute_Call {
	return &processRefundOrChargeback_Execute_Call{Call: _e.mock.On("Execute", ctx, in)}
}

func (_c *processRefundOrChargeback_Execute_Call) Run(run func(ctx context.Context, in input.ProcessRefundOrChargebackInput)) *processRefundOrChargeback_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 input.ProcessRefundOrChargebackInput
		if args[1] != nil {
			arg1 = args[1].(input.ProcessRefundOrChargebackInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *processRefundOrChargeback_Execute_Call) Return(err error) *processRefundOrChargeback_Execute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *processRefundOrChargeback_Execute_Call) RunAndReturn(run func(ctx context.Context, in input.ProcessRefundOrChargebackInput) error) *processRefundOrChargeback_Execute_Call {
	_c.Call.Return(run)
	return _c
}
