// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/LimaTeixeiraTecnologia/mecontrola/internal/billing/domain/entities"

	mock "github.com/stretchr/testify/mock"

	time "time"

	valueobjects "github.com/LimaTeixeiraTecnologia/mecontrola/internal/billing/domain/valueobjects"
)

// SubscriptionRepository is an autogenerated mock type for the SubscriptionRepository type
type SubscriptionRepository struct {
	mock.Mock
}

type SubscriptionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *SubscriptionRepository) EXPECT() *SubscriptionRepository_Expecter {
	return &SubscriptionRepository_Expecter{mock: &_m.Mock}
}

// ApplyTransition provides a mock function with given fields: ctx, subscriptionID, status, graceEnd, lastEventAt
func (_m *SubscriptionRepository) ApplyTransition(ctx context.Context, subscriptionID string, status valueobjects.Status, graceEnd time.Time, lastEventAt time.Time) error {
	ret := _m.Called(ctx, subscriptionID, status, graceEnd, lastEventAt)

	if len(ret) == 0 {
		panic("no return value specified for ApplyTransition")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, valueobjects.Status, time.Time, time.Time) error); ok {
		r0 = rf(ctx, subscriptionID, status, graceEnd, lastEventAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SubscriptionRepository_ApplyTransition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyTransition'
type SubscriptionRepository_ApplyTransition_Call struct {
	*mock.Call
}

// ApplyTransition is a helper method to define mock.On call
//   - ctx context.Context
//   - subscriptionID string
//   - status valueobjects.Status
//   - graceEnd time.Time
//   - lastEventAt time.Time
func (_e *SubscriptionRepository_Expecter) ApplyTransition(ctx interface{}, subscriptionID interface{}, status interface{}, graceEnd interface{}, lastEventAt interface{}) *SubscriptionRepository_ApplyTransition_Call {
	return &SubscriptionRepository_ApplyTransition_Call{Call: _e.mock.On("ApplyTransition", ctx, subscriptionID, status, graceEnd, lastEventAt)}
}

func (_c *SubscriptionRepository_ApplyTransition_Call) Run(run func(ctx context.Context, subscriptionID string, status valueobjects.Status, graceEnd time.Time, lastEventAt time.Time)) *SubscriptionRepository_ApplyTransition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(valueobjects.Status), args[3].(time.Time), args[4].(time.Time))
	})
	return _c
}

func (_c *SubscriptionRepository_ApplyTransition_Call) Return(_a0 error) *SubscriptionRepository_ApplyTransition_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SubscriptionRepository_ApplyTransition_Call) RunAndReturn(run func(context.Context, string, valueobjects.Status, time.Time, time.Time) error) *SubscriptionRepository_ApplyTransition_Call {
	_c.Call.Return(run)
	return _c
}

// BindUser provides a mock function with given fields: ctx, subscriptionID, userID
func (_m *SubscriptionRepository) BindUser(ctx context.Context, subscriptionID string, userID string) error {
	ret := _m.Called(ctx, subscriptionID, userID)

	if len(ret) == 0 {
		panic("no return value specified for BindUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, subscriptionID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SubscriptionRepository_BindUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BindUser'
type SubscriptionRepository_BindUser_Call struct {
	*mock.Call
}

// BindUser is a helper method to define mock.On call
//   - ctx context.Context
//   - subscriptionID string
//   - userID string
func (_e *SubscriptionRepository_Expecter) BindUser(ctx interface{}, subscriptionID interface{}, userID interface{}) *SubscriptionRepository_BindUser_Call {
	return &SubscriptionRepository_BindUser_Call{Call: _e.mock.On("BindUser", ctx, subscriptionID, userID)}
}

func (_c *SubscriptionRepository_BindUser_Call) Run(run func(ctx context.Context, subscriptionID string, userID string)) *SubscriptionRepository_BindUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *SubscriptionRepository_BindUser_Call) Return(_a0 error) *SubscriptionRepository_BindUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SubscriptionRepository_BindUser_Call) RunAndReturn(run func(context.Context, string, string) error) *SubscriptionRepository_BindUser_Call {
	_c.Call.Return(run)
	return _c
}

// ExtendPeriod provides a mock function with given fields: ctx, subscriptionID, newPeriodEnd, lastEventAt
func (_m *SubscriptionRepository) ExtendPeriod(ctx context.Context, subscriptionID string, newPeriodEnd time.Time, lastEventAt time.Time) error {
	ret := _m.Called(ctx, subscriptionID, newPeriodEnd, lastEventAt)

	if len(ret) == 0 {
		panic("no return value specified for ExtendPeriod")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) error); ok {
		r0 = rf(ctx, subscriptionID, newPeriodEnd, lastEventAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SubscriptionRepository_ExtendPeriod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtendPeriod'
type SubscriptionRepository_ExtendPeriod_Call struct {
	*mock.Call
}

// ExtendPeriod is a helper method to define mock.On call
//   - ctx context.Context
//   - subscriptionID string
//   - newPeriodEnd time.Time
//   - lastEventAt time.Time
func (_e *SubscriptionRepository_Expecter) ExtendPeriod(ctx interface{}, subscriptionID interface{}, newPeriodEnd interface{}, lastEventAt interface{}) *SubscriptionRepository_ExtendPeriod_Call {
	return &SubscriptionRepository_ExtendPeriod_Call{Call: _e.mock.On("ExtendPeriod", ctx, subscriptionID, newPeriodEnd, lastEventAt)}
}

func (_c *SubscriptionRepository_ExtendPeriod_Call) Run(run func(ctx context.Context, subscriptionID string, newPeriodEnd time.Time, lastEventAt time.Time)) *SubscriptionRepository_ExtendPeriod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *SubscriptionRepository_ExtendPeriod_Call) Return(_a0 error) *SubscriptionRepository_ExtendPeriod_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SubscriptionRepository_ExtendPeriod_Call) RunAndReturn(run func(context.Context, string, time.Time, time.Time) error) *SubscriptionRepository_ExtendPeriod_Call {
	_c.Call.Return(run)
	return _c
}

// FindByOrderID provides a mock function with given fields: ctx, orderID
func (_m *SubscriptionRepository) FindByOrderID(ctx context.Context, orderID string) (entities.Subscription, error) {
	ret := _m.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for FindByOrderID")
	}

	var r0 entities.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entities.Subscription, error)); ok {
		return rf(ctx, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entities.Subscription); ok {
		r0 = rf(ctx, orderID)
	} else {
		r0 = ret.Get(0).(entities.Subscription)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SubscriptionRepository_FindByOrderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByOrderID'
type SubscriptionRepository_FindByOrderID_Call struct {
	*mock.Call
}

// FindByOrderID is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
func (_e *SubscriptionRepository_Expecter) FindByOrderID(ctx interface{}, orderID interface{}) *SubscriptionRepository_FindByOrderID_Call {
	return &SubscriptionRepository_FindByOrderID_Call{Call: _e.mock.On("FindByOrderID", ctx, orderID)}
}

func (_c *SubscriptionRepository_FindByOrderID_Call) Run(run func(ctx context.Context, orderID string)) *SubscriptionRepository_FindByOrderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *SubscriptionRepository_FindByOrderID_Call) Return(_a0 entities.Subscription, _a1 error) *SubscriptionRepository_FindByOrderID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SubscriptionRepository_FindByOrderID_Call) RunAndReturn(run func(context.Context, string) (entities.Subscription, error)) *SubscriptionRepository_FindByOrderID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserID provides a mock function with given fields: ctx, userID
func (_m *SubscriptionRepository) FindByUserID(ctx context.Context, userID string) (entities.Subscription, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 entities.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entities.Subscription, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entities.Subscription); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(entities.Subscription)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SubscriptionRepository_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type SubscriptionRepository_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *SubscriptionRepository_Expecter) FindByUserID(ctx interface{}, userID interface{}) *SubscriptionRepository_FindByUserID_Call {
	return &SubscriptionRepository_FindByUserID_Call{Call: _e.mock.On("FindByUserID", ctx, userID)}
}

func (_c *SubscriptionRepository_FindByUserID_Call) Run(run func(ctx context.Context, userID string)) *SubscriptionRepository_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *SubscriptionRepository_FindByUserID_Call) Return(_a0 entities.Subscription, _a1 error) *SubscriptionRepository_FindByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SubscriptionRepository_FindByUserID_Call) RunAndReturn(run func(context.Context, string) (entities.Subscription, error)) *SubscriptionRepository_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertByOrder provides a mock function with given fields: ctx, orderID, sub, periodStart
func (_m *SubscriptionRepository) UpsertByOrder(ctx context.Context, orderID string, sub entities.Subscription, periodStart time.Time) error {
	ret := _m.Called(ctx, orderID, sub, periodStart)

	if len(ret) == 0 {
		panic("no return value specified for UpsertByOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, entities.Subscription, time.Time) error); ok {
		r0 = rf(ctx, orderID, sub, periodStart)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SubscriptionRepository_UpsertByOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertByOrder'
type SubscriptionRepository_UpsertByOrder_Call struct {
	*mock.Call
}

// UpsertByOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
//   - sub entities.Subscription
//   - periodStart time.Time
func (_e *SubscriptionRepository_Expecter) UpsertByOrder(ctx interface{}, orderID interface{}, sub interface{}, periodStart interface{}) *SubscriptionRepository_UpsertByOrder_Call {
	return &SubscriptionRepository_UpsertByOrder_Call{Call: _e.mock.On("UpsertByOrder", ctx, orderID, sub, periodStart)}
}

func (_c *SubscriptionRepository_UpsertByOrder_Call) Run(run func(ctx context.Context, orderID string, sub entities.Subscription, periodStart time.Time)) *SubscriptionRepository_UpsertByOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(entities.Subscription), args[3].(time.Time))
	})
	return _c
}

func (_c *SubscriptionRepository_UpsertByOrder_Call) Return(_a0 error) *SubscriptionRepository_UpsertByOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SubscriptionRepository_UpsertByOrder_Call) RunAndReturn(run func(context.Context, string, entities.Subscription, time.Time) error) *SubscriptionRepository_UpsertByOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewSubscriptionRepository creates a new instance of SubscriptionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSubscriptionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SubscriptionRepository {
	mock := &SubscriptionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
