// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/LimaTeixeiraTecnologia/mecontrola/internal/onboarding/application/interfaces"
	mock "github.com/stretchr/testify/mock"
)

// NewIdentityGateway creates a new instance of IdentityGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIdentityGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *IdentityGateway {
	mock := &IdentityGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// IdentityGateway is an autogenerated mock type for the IdentityGateway type
type IdentityGateway struct {
	mock.Mock
}

type IdentityGateway_Expecter struct {
	mock *mock.Mock
}

func (_m *IdentityGateway) EXPECT() *IdentityGateway_Expecter {
	return &IdentityGateway_Expecter{mock: &_m.Mock}
}

// UpsertUserByWhatsApp provides a mock function for the type IdentityGateway
func (_mock *IdentityGateway) UpsertUserByWhatsApp(ctx context.Context, mobileE164 string, email string) (interfaces.UpsertUserResult, error) {
	ret := _mock.Called(ctx, mobileE164, email)

	if len(ret) == 0 {
		panic("no return value specified for UpsertUserByWhatsApp")
	}

	var r0 interfaces.UpsertUserResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (interfaces.UpsertUserResult, error)); ok {
		return returnFunc(ctx, mobileE164, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) interfaces.UpsertUserResult); ok {
		r0 = returnFunc(ctx, mobileE164, email)
	} else {
		r0 = ret.Get(0).(interfaces.UpsertUserResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, mobileE164, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IdentityGateway_UpsertUserByWhatsApp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertUserByWhatsApp'
type IdentityGateway_UpsertUserByWhatsApp_Call struct {
	*mock.Call
}

// UpsertUserByWhatsApp is a helper method to define mock.On call
//   - ctx context.Context
//   - mobileE164 string
//   - email string
func (_e *IdentityGateway_Expecter) UpsertUserByWhatsApp(ctx interface{}, mobileE164 interface{}, email interface{}) *IdentityGateway_UpsertUserByWhatsApp_Call {
	return &IdentityGateway_UpsertUserByWhatsApp_Call{Call: _e.mock.On("UpsertUserByWhatsApp", ctx, mobileE164, email)}
}

func (_c *IdentityGateway_UpsertUserByWhatsApp_Call) Run(run func(ctx context.Context, mobileE164 string, email string)) *IdentityGateway_UpsertUserByWhatsApp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *IdentityGateway_UpsertUserByWhatsApp_Call) Return(upsertUserResult interfaces.UpsertUserResult, err error) *IdentityGateway_UpsertUserByWhatsApp_Call {
	_c.Call.Return(upsertUserResult, err)
	return _c
}

func (_c *IdentityGateway_UpsertUserByWhatsApp_Call) RunAndReturn(run func(ctx context.Context, mobileE164 string, email string) (interfaces.UpsertUserResult, error)) *IdentityGateway_UpsertUserByWhatsApp_Call {
	_c.Call.Return(run)
	return _c
}
