// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

func NewNoMatchThrottle(t interface {
	mock.TestingT
	Cleanup(func())
}) *NoMatchThrottle {
	m := &NoMatchThrottle{}
	m.Mock.Test(t)
	t.Cleanup(func() { m.AssertExpectations(t) })
	return m
}

type NoMatchThrottle struct {
	mock.Mock
}

type NoMatchThrottle_Expecter struct {
	mock *mock.Mock
}

func (_m *NoMatchThrottle) EXPECT() *NoMatchThrottle_Expecter {
	return &NoMatchThrottle_Expecter{mock: &_m.Mock}
}

func (_mock *NoMatchThrottle) AllowReply(ctx context.Context, mobileE164 string, windowStart time.Time) (bool, error) {
	ret := _mock.Called(ctx, mobileE164, windowStart)

	if len(ret) == 0 {
		panic("no return value specified for AllowReply")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) (bool, error)); ok {
		return returnFunc(ctx, mobileE164, windowStart)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) bool); ok {
		r0 = returnFunc(ctx, mobileE164, windowStart)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = returnFunc(ctx, mobileE164, windowStart)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type NoMatchThrottle_AllowReply_Call struct {
	*mock.Call
}

func (_e *NoMatchThrottle_Expecter) AllowReply(ctx any, mobileE164 any, windowStart any) *NoMatchThrottle_AllowReply_Call {
	return &NoMatchThrottle_AllowReply_Call{Call: _e.mock.On("AllowReply", ctx, mobileE164, windowStart)}
}

func (_c *NoMatchThrottle_AllowReply_Call) Run(run func(ctx context.Context, mobileE164 string, windowStart time.Time)) *NoMatchThrottle_AllowReply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(arg0, arg1, arg2)
	})
	return _c
}

func (_c *NoMatchThrottle_AllowReply_Call) Return(allowed bool, err error) *NoMatchThrottle_AllowReply_Call {
	_c.Call.Return(allowed, err)
	return _c
}

func (_c *NoMatchThrottle_AllowReply_Call) RunAndReturn(run func(ctx context.Context, mobileE164 string, windowStart time.Time) (bool, error)) *NoMatchThrottle_AllowReply_Call {
	_c.Call.Return(run)
	return _c
}

func (_mock *NoMatchThrottle) DeleteBefore(ctx context.Context, before time.Time, batchSize int) (int64, error) {
	ret := _mock.Called(ctx, before, batchSize)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBefore")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, int) (int64, error)); ok {
		return returnFunc(ctx, before, batchSize)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, int) int64); ok {
		r0 = returnFunc(ctx, before, batchSize)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time, int) error); ok {
		r1 = returnFunc(ctx, before, batchSize)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type NoMatchThrottle_DeleteBefore_Call struct {
	*mock.Call
}

func (_e *NoMatchThrottle_Expecter) DeleteBefore(ctx any, before any, batchSize any) *NoMatchThrottle_DeleteBefore_Call {
	return &NoMatchThrottle_DeleteBefore_Call{Call: _e.mock.On("DeleteBefore", ctx, before, batchSize)}
}

func (_c *NoMatchThrottle_DeleteBefore_Call) Run(run func(ctx context.Context, before time.Time, batchSize int)) *NoMatchThrottle_DeleteBefore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(arg0, arg1, arg2)
	})
	return _c
}

func (_c *NoMatchThrottle_DeleteBefore_Call) Return(n int64, err error) *NoMatchThrottle_DeleteBefore_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *NoMatchThrottle_DeleteBefore_Call) RunAndReturn(run func(ctx context.Context, before time.Time, batchSize int) (int64, error)) *NoMatchThrottle_DeleteBefore_Call {
	_c.Call.Return(run)
	return _c
}
