// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/JailtonJunior94/devkit-go/pkg/database"
	"github.com/LimaTeixeiraTecnologia/mecontrola/internal/onboarding/application/interfaces"
	mock "github.com/stretchr/testify/mock"
)

// NewOnboardingSessionRepositoryFactory creates a new instance of OnboardingSessionRepositoryFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOnboardingSessionRepositoryFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *OnboardingSessionRepositoryFactory {
	mock := &OnboardingSessionRepositoryFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OnboardingSessionRepositoryFactory is an autogenerated mock type for the OnboardingSessionRepositoryFactory type
type OnboardingSessionRepositoryFactory struct {
	mock.Mock
}

type OnboardingSessionRepositoryFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *OnboardingSessionRepositoryFactory) EXPECT() *OnboardingSessionRepositoryFactory_Expecter {
	return &OnboardingSessionRepositoryFactory_Expecter{mock: &_m.Mock}
}

// OnboardingSessionRepository provides a mock function for the type OnboardingSessionRepositoryFactory
func (_mock *OnboardingSessionRepositoryFactory) OnboardingSessionRepository(db database.DBTX) interfaces.OnboardingSessionRepository {
	ret := _mock.Called(db)

	if len(ret) == 0 {
		panic("no return value specified for OnboardingSessionRepository")
	}

	var r0 interfaces.OnboardingSessionRepository
	if returnFunc, ok := ret.Get(0).(func(database.DBTX) interfaces.OnboardingSessionRepository); ok {
		r0 = returnFunc(db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.OnboardingSessionRepository)
		}
	}
	return r0
}

// OnboardingSessionRepositoryFactory_OnboardingSessionRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnboardingSessionRepository'
type OnboardingSessionRepositoryFactory_OnboardingSessionRepository_Call struct {
	*mock.Call
}

// OnboardingSessionRepository is a helper method to define mock.On call
//   - db database.DBTX
func (_e *OnboardingSessionRepositoryFactory_Expecter) OnboardingSessionRepository(db any) *OnboardingSessionRepositoryFactory_OnboardingSessionRepository_Call {
	return &OnboardingSessionRepositoryFactory_OnboardingSessionRepository_Call{Call: _e.mock.On("OnboardingSessionRepository", db)}
}

func (_c *OnboardingSessionRepositoryFactory_OnboardingSessionRepository_Call) Run(run func(db database.DBTX)) *OnboardingSessionRepositoryFactory_OnboardingSessionRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 database.DBTX
		if args[0] != nil {
			arg0 = args[0].(database.DBTX)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *OnboardingSessionRepositoryFactory_OnboardingSessionRepository_Call) Return(onboardingSessionRepository interfaces.OnboardingSessionRepository) *OnboardingSessionRepositoryFactory_OnboardingSessionRepository_Call {
	_c.Call.Return(onboardingSessionRepository)
	return _c
}

func (_c *OnboardingSessionRepositoryFactory_OnboardingSessionRepository_Call) RunAndReturn(run func(db database.DBTX) interfaces.OnboardingSessionRepository) *OnboardingSessionRepositoryFactory_OnboardingSessionRepository_Call {
	_c.Call.Return(run)
	return _c
}
