// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/LimaTeixeiraTecnologia/mecontrola/internal/onboarding/domain/entities"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewOnboardingSessionRepository creates a new instance of OnboardingSessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOnboardingSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OnboardingSessionRepository {
	mock := &OnboardingSessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OnboardingSessionRepository is an autogenerated mock type for the OnboardingSessionRepository type
type OnboardingSessionRepository struct {
	mock.Mock
}

type OnboardingSessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *OnboardingSessionRepository) EXPECT() *OnboardingSessionRepository_Expecter {
	return &OnboardingSessionRepository_Expecter{mock: &_m.Mock}
}

// Find provides a mock function for the type OnboardingSessionRepository
func (_mock *OnboardingSessionRepository) Find(ctx context.Context, userID uuid.UUID) (entities.OnboardingSession, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 entities.OnboardingSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (entities.OnboardingSession, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) entities.OnboardingSession); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(entities.OnboardingSession)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OnboardingSessionRepository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type OnboardingSessionRepository_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *OnboardingSessionRepository_Expecter) Find(ctx any, userID any) *OnboardingSessionRepository_Find_Call {
	return &OnboardingSessionRepository_Find_Call{Call: _e.mock.On("Find", ctx, userID)}
}

func (_c *OnboardingSessionRepository_Find_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *OnboardingSessionRepository_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OnboardingSessionRepository_Find_Call) Return(onboardingSession entities.OnboardingSession, err error) *OnboardingSessionRepository_Find_Call {
	_c.Call.Return(onboardingSession, err)
	return _c
}

func (_c *OnboardingSessionRepository_Find_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (entities.OnboardingSession, error)) *OnboardingSessionRepository_Find_Call {
	_c.Call.Return(run)
	return _c
}

// MarkActive provides a mock function for the type OnboardingSessionRepository
func (_mock *OnboardingSessionRepository) MarkActive(ctx context.Context, userID uuid.UUID) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkActive")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OnboardingSessionRepository_MarkActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkActive'
type OnboardingSessionRepository_MarkActive_Call struct {
	*mock.Call
}

// MarkActive is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *OnboardingSessionRepository_Expecter) MarkActive(ctx any, userID any) *OnboardingSessionRepository_MarkActive_Call {
	return &OnboardingSessionRepository_MarkActive_Call{Call: _e.mock.On("MarkActive", ctx, userID)}
}

func (_c *OnboardingSessionRepository_MarkActive_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *OnboardingSessionRepository_MarkActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OnboardingSessionRepository_MarkActive_Call) Return(err error) *OnboardingSessionRepository_MarkActive_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OnboardingSessionRepository_MarkActive_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) error) *OnboardingSessionRepository_MarkActive_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type OnboardingSessionRepository
func (_mock *OnboardingSessionRepository) Upsert(ctx context.Context, session entities.OnboardingSession) error {
	ret := _mock.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.OnboardingSession) error); ok {
		r0 = returnFunc(ctx, session)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OnboardingSessionRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type OnboardingSessionRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - session entities.OnboardingSession
func (_e *OnboardingSessionRepository_Expecter) Upsert(ctx any, session any) *OnboardingSessionRepository_Upsert_Call {
	return &OnboardingSessionRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, session)}
}

func (_c *OnboardingSessionRepository_Upsert_Call) Run(run func(ctx context.Context, session entities.OnboardingSession)) *OnboardingSessionRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.OnboardingSession
		if args[1] != nil {
			arg1 = args[1].(entities.OnboardingSession)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OnboardingSessionRepository_Upsert_Call) Return(err error) *OnboardingSessionRepository_Upsert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OnboardingSessionRepository_Upsert_Call) RunAndReturn(run func(ctx context.Context, session entities.OnboardingSession) error) *OnboardingSessionRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}
