// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	database "github.com/JailtonJunior94/devkit-go/pkg/database"
	events "github.com/LimaTeixeiraTecnologia/mecontrola/internal/infrastructure/events"
	outbox "github.com/LimaTeixeiraTecnologia/mecontrola/internal/infrastructure/outbox"
	mock "github.com/stretchr/testify/mock"
)

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

type Storage_Expecter struct {
	mock *mock.Mock
}

func (_m *Storage) EXPECT() *Storage_Expecter {
	return &Storage_Expecter{mock: &_m.Mock}
}

// ClaimReady provides a mock function with given fields: ctx, batchSize, instanceID
func (_m *Storage) ClaimReady(ctx context.Context, batchSize int, instanceID string) ([]outbox.Claim, error) {
	ret := _m.Called(ctx, batchSize, instanceID)

	if len(ret) == 0 {
		panic("no return value specified for ClaimReady")
	}

	var r0 []outbox.Claim
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string) ([]outbox.Claim, error)); ok {
		return rf(ctx, batchSize, instanceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, string) []outbox.Claim); ok {
		r0 = rf(ctx, batchSize, instanceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]outbox.Claim)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, string) error); ok {
		r1 = rf(ctx, batchSize, instanceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storage_ClaimReady_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClaimReady'
type Storage_ClaimReady_Call struct {
	*mock.Call
}

// ClaimReady is a helper method to define mock.On call
//   - ctx context.Context
//   - batchSize int
//   - instanceID string
func (_e *Storage_Expecter) ClaimReady(ctx interface{}, batchSize interface{}, instanceID interface{}) *Storage_ClaimReady_Call {
	return &Storage_ClaimReady_Call{Call: _e.mock.On("ClaimReady", ctx, batchSize, instanceID)}
}

func (_c *Storage_ClaimReady_Call) Run(run func(ctx context.Context, batchSize int, instanceID string)) *Storage_ClaimReady_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string))
	})
	return _c
}

func (_c *Storage_ClaimReady_Call) Return(_a0 []outbox.Claim, _a1 error) *Storage_ClaimReady_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Storage_ClaimReady_Call) RunAndReturn(run func(context.Context, int, string) ([]outbox.Claim, error)) *Storage_ClaimReady_Call {
	_c.Call.Return(run)
	return _c
}

// InsertDeliveries provides a mock function with given fields: ctx, tx, evtID, subs
func (_m *Storage) InsertDeliveries(ctx context.Context, tx database.DBTX, evtID events.EventID, subs []outbox.SubscriptionName) error {
	ret := _m.Called(ctx, tx, evtID, subs)

	if len(ret) == 0 {
		panic("no return value specified for InsertDeliveries")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, database.DBTX, events.EventID, []outbox.SubscriptionName) error); ok {
		r0 = rf(ctx, tx, evtID, subs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storage_InsertDeliveries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertDeliveries'
type Storage_InsertDeliveries_Call struct {
	*mock.Call
}

// InsertDeliveries is a helper method to define mock.On call
//   - ctx context.Context
//   - tx database.DBTX
//   - evtID events.EventID
//   - subs []outbox.SubscriptionName
func (_e *Storage_Expecter) InsertDeliveries(ctx interface{}, tx interface{}, evtID interface{}, subs interface{}) *Storage_InsertDeliveries_Call {
	return &Storage_InsertDeliveries_Call{Call: _e.mock.On("InsertDeliveries", ctx, tx, evtID, subs)}
}

func (_c *Storage_InsertDeliveries_Call) Run(run func(ctx context.Context, tx database.DBTX, evtID events.EventID, subs []outbox.SubscriptionName)) *Storage_InsertDeliveries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(database.DBTX), args[2].(events.EventID), args[3].([]outbox.SubscriptionName))
	})
	return _c
}

func (_c *Storage_InsertDeliveries_Call) Return(_a0 error) *Storage_InsertDeliveries_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_InsertDeliveries_Call) RunAndReturn(run func(context.Context, database.DBTX, events.EventID, []outbox.SubscriptionName) error) *Storage_InsertDeliveries_Call {
	_c.Call.Return(run)
	return _c
}

// InsertEvent provides a mock function with given fields: ctx, tx, evt
func (_m *Storage) InsertEvent(ctx context.Context, tx database.DBTX, evt outbox.Event) error {
	ret := _m.Called(ctx, tx, evt)

	if len(ret) == 0 {
		panic("no return value specified for InsertEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, database.DBTX, outbox.Event) error); ok {
		r0 = rf(ctx, tx, evt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storage_InsertEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertEvent'
type Storage_InsertEvent_Call struct {
	*mock.Call
}

// InsertEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - tx database.DBTX
//   - evt outbox.Event
func (_e *Storage_Expecter) InsertEvent(ctx interface{}, tx interface{}, evt interface{}) *Storage_InsertEvent_Call {
	return &Storage_InsertEvent_Call{Call: _e.mock.On("InsertEvent", ctx, tx, evt)}
}

func (_c *Storage_InsertEvent_Call) Run(run func(ctx context.Context, tx database.DBTX, evt outbox.Event)) *Storage_InsertEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(database.DBTX), args[2].(outbox.Event))
	})
	return _c
}

func (_c *Storage_InsertEvent_Call) Return(_a0 error) *Storage_InsertEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_InsertEvent_Call) RunAndReturn(run func(context.Context, database.DBTX, outbox.Event) error) *Storage_InsertEvent_Call {
	_c.Call.Return(run)
	return _c
}

// MarkDLQ provides a mock function with given fields: ctx, id, lastErr, deadLetterAt
func (_m *Storage) MarkDLQ(ctx context.Context, id outbox.ClaimID, lastErr string, deadLetterAt time.Time) error {
	ret := _m.Called(ctx, id, lastErr, deadLetterAt)

	if len(ret) == 0 {
		panic("no return value specified for MarkDLQ")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, outbox.ClaimID, string, time.Time) error); ok {
		r0 = rf(ctx, id, lastErr, deadLetterAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storage_MarkDLQ_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkDLQ'
type Storage_MarkDLQ_Call struct {
	*mock.Call
}

// MarkDLQ is a helper method to define mock.On call
//   - ctx context.Context
//   - id outbox.ClaimID
//   - lastErr string
//   - deadLetterAt time.Time
func (_e *Storage_Expecter) MarkDLQ(ctx interface{}, id interface{}, lastErr interface{}, deadLetterAt interface{}) *Storage_MarkDLQ_Call {
	return &Storage_MarkDLQ_Call{Call: _e.mock.On("MarkDLQ", ctx, id, lastErr, deadLetterAt)}
}

func (_c *Storage_MarkDLQ_Call) Run(run func(ctx context.Context, id outbox.ClaimID, lastErr string, deadLetterAt time.Time)) *Storage_MarkDLQ_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(outbox.ClaimID), args[2].(string), args[3].(time.Time))
	})
	return _c
}

func (_c *Storage_MarkDLQ_Call) Return(_a0 error) *Storage_MarkDLQ_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_MarkDLQ_Call) RunAndReturn(run func(context.Context, outbox.ClaimID, string, time.Time) error) *Storage_MarkDLQ_Call {
	_c.Call.Return(run)
	return _c
}

// MarkFailed provides a mock function with given fields: ctx, id, lastErr, nextAttempt, nextRetryAt
func (_m *Storage) MarkFailed(ctx context.Context, id outbox.ClaimID, lastErr string, nextAttempt outbox.Attempt, nextRetryAt time.Time) error {
	ret := _m.Called(ctx, id, lastErr, nextAttempt, nextRetryAt)

	if len(ret) == 0 {
		panic("no return value specified for MarkFailed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, outbox.ClaimID, string, outbox.Attempt, time.Time) error); ok {
		r0 = rf(ctx, id, lastErr, nextAttempt, nextRetryAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storage_MarkFailed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkFailed'
type Storage_MarkFailed_Call struct {
	*mock.Call
}

// MarkFailed is a helper method to define mock.On call
//   - ctx context.Context
//   - id outbox.ClaimID
//   - lastErr string
//   - nextAttempt outbox.Attempt
//   - nextRetryAt time.Time
func (_e *Storage_Expecter) MarkFailed(ctx interface{}, id interface{}, lastErr interface{}, nextAttempt interface{}, nextRetryAt interface{}) *Storage_MarkFailed_Call {
	return &Storage_MarkFailed_Call{Call: _e.mock.On("MarkFailed", ctx, id, lastErr, nextAttempt, nextRetryAt)}
}

func (_c *Storage_MarkFailed_Call) Run(run func(ctx context.Context, id outbox.ClaimID, lastErr string, nextAttempt outbox.Attempt, nextRetryAt time.Time)) *Storage_MarkFailed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(outbox.ClaimID), args[2].(string), args[3].(outbox.Attempt), args[4].(time.Time))
	})
	return _c
}

func (_c *Storage_MarkFailed_Call) Return(_a0 error) *Storage_MarkFailed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_MarkFailed_Call) RunAndReturn(run func(context.Context, outbox.ClaimID, string, outbox.Attempt, time.Time) error) *Storage_MarkFailed_Call {
	_c.Call.Return(run)
	return _c
}

// MarkProcessed provides a mock function with given fields: ctx, id, processedAt
func (_m *Storage) MarkProcessed(ctx context.Context, id outbox.ClaimID, processedAt time.Time) error {
	ret := _m.Called(ctx, id, processedAt)

	if len(ret) == 0 {
		panic("no return value specified for MarkProcessed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, outbox.ClaimID, time.Time) error); ok {
		r0 = rf(ctx, id, processedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storage_MarkProcessed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkProcessed'
type Storage_MarkProcessed_Call struct {
	*mock.Call
}

// MarkProcessed is a helper method to define mock.On call
//   - ctx context.Context
//   - id outbox.ClaimID
//   - processedAt time.Time
func (_e *Storage_Expecter) MarkProcessed(ctx interface{}, id interface{}, processedAt interface{}) *Storage_MarkProcessed_Call {
	return &Storage_MarkProcessed_Call{Call: _e.mock.On("MarkProcessed", ctx, id, processedAt)}
}

func (_c *Storage_MarkProcessed_Call) Run(run func(ctx context.Context, id outbox.ClaimID, processedAt time.Time)) *Storage_MarkProcessed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(outbox.ClaimID), args[2].(time.Time))
	})
	return _c
}

func (_c *Storage_MarkProcessed_Call) Return(_a0 error) *Storage_MarkProcessed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_MarkProcessed_Call) RunAndReturn(run func(context.Context, outbox.ClaimID, time.Time) error) *Storage_MarkProcessed_Call {
	_c.Call.Return(run)
	return _c
}

// PurgeOlderThan provides a mock function with given fields: ctx, olderThan
func (_m *Storage) PurgeOlderThan(ctx context.Context, olderThan time.Time) (int64, error) {
	ret := _m.Called(ctx, olderThan)

	if len(ret) == 0 {
		panic("no return value specified for PurgeOlderThan")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) (int64, error)); ok {
		return rf(ctx, olderThan)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) int64); ok {
		r0 = rf(ctx, olderThan)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, olderThan)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storage_PurgeOlderThan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PurgeOlderThan'
type Storage_PurgeOlderThan_Call struct {
	*mock.Call
}

// PurgeOlderThan is a helper method to define mock.On call
//   - ctx context.Context
//   - olderThan time.Time
func (_e *Storage_Expecter) PurgeOlderThan(ctx interface{}, olderThan interface{}) *Storage_PurgeOlderThan_Call {
	return &Storage_PurgeOlderThan_Call{Call: _e.mock.On("PurgeOlderThan", ctx, olderThan)}
}

func (_c *Storage_PurgeOlderThan_Call) Run(run func(ctx context.Context, olderThan time.Time)) *Storage_PurgeOlderThan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *Storage_PurgeOlderThan_Call) Return(_a0 int64, _a1 error) *Storage_PurgeOlderThan_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Storage_PurgeOlderThan_Call) RunAndReturn(run func(context.Context, time.Time) (int64, error)) *Storage_PurgeOlderThan_Call {
	_c.Call.Return(run)
	return _c
}

// ReleaseStuck provides a mock function with given fields: ctx, olderThan
func (_m *Storage) ReleaseStuck(ctx context.Context, olderThan time.Time) (int64, error) {
	ret := _m.Called(ctx, olderThan)

	if len(ret) == 0 {
		panic("no return value specified for ReleaseStuck")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) (int64, error)); ok {
		return rf(ctx, olderThan)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) int64); ok {
		r0 = rf(ctx, olderThan)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, olderThan)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storage_ReleaseStuck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReleaseStuck'
type Storage_ReleaseStuck_Call struct {
	*mock.Call
}

// ReleaseStuck is a helper method to define mock.On call
//   - ctx context.Context
//   - olderThan time.Time
func (_e *Storage_Expecter) ReleaseStuck(ctx interface{}, olderThan interface{}) *Storage_ReleaseStuck_Call {
	return &Storage_ReleaseStuck_Call{Call: _e.mock.On("ReleaseStuck", ctx, olderThan)}
}

func (_c *Storage_ReleaseStuck_Call) Run(run func(ctx context.Context, olderThan time.Time)) *Storage_ReleaseStuck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *Storage_ReleaseStuck_Call) Return(_a0 int64, _a1 error) *Storage_ReleaseStuck_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Storage_ReleaseStuck_Call) RunAndReturn(run func(context.Context, time.Time) (int64, error)) *Storage_ReleaseStuck_Call {
	_c.Call.Return(run)
	return _c
}

// Stats provides a mock function with given fields: ctx
func (_m *Storage) Stats(ctx context.Context) (outbox.Stats, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Stats")
	}

	var r0 outbox.Stats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (outbox.Stats, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) outbox.Stats); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(outbox.Stats)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storage_Stats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stats'
type Storage_Stats_Call struct {
	*mock.Call
}

// Stats is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Storage_Expecter) Stats(ctx interface{}) *Storage_Stats_Call {
	return &Storage_Stats_Call{Call: _e.mock.On("Stats", ctx)}
}

func (_c *Storage_Stats_Call) Run(run func(ctx context.Context)) *Storage_Stats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Storage_Stats_Call) Return(_a0 outbox.Stats, _a1 error) *Storage_Stats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Storage_Stats_Call) RunAndReturn(run func(context.Context) (outbox.Stats, error)) *Storage_Stats_Call {
	_c.Call.Return(run)
	return _c
}

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
