// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/LimaTeixeiraTecnologia/mecontrola/internal/platform/memory"
)

func NewThreadGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *ThreadGateway {
	mock := &ThreadGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

type ThreadGateway struct {
	mock.Mock
}

type ThreadGateway_Expecter struct {
	mock *mock.Mock
}

func (_m *ThreadGateway) EXPECT() *ThreadGateway_Expecter {
	return &ThreadGateway_Expecter{mock: &_m.Mock}
}

func (_mock *ThreadGateway) GetOrCreate(ctx context.Context, resourceID string, threadID string) (memory.Thread, error) {
	ret := _mock.Called(ctx, resourceID, threadID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrCreate")
	}

	var r0 memory.Thread
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (memory.Thread, error)); ok {
		return returnFunc(ctx, resourceID, threadID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) memory.Thread); ok {
		r0 = returnFunc(ctx, resourceID, threadID)
	} else {
		r0 = ret.Get(0).(memory.Thread)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, resourceID, threadID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type ThreadGateway_GetOrCreate_Call struct {
	*mock.Call
}

func (_e *ThreadGateway_Expecter) GetOrCreate(ctx any, resourceID any, threadID any) *ThreadGateway_GetOrCreate_Call {
	return &ThreadGateway_GetOrCreate_Call{Call: _e.mock.On("GetOrCreate", ctx, resourceID, threadID)}
}

func (_c *ThreadGateway_GetOrCreate_Call) Run(run func(ctx context.Context, resourceID string, threadID string)) *ThreadGateway_GetOrCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(arg0, arg1, arg2)
	})
	return _c
}

func (_c *ThreadGateway_GetOrCreate_Call) Return(thread memory.Thread, err error) *ThreadGateway_GetOrCreate_Call {
	_c.Call.Return(thread, err)
	return _c
}

func (_c *ThreadGateway_GetOrCreate_Call) RunAndReturn(run func(context.Context, string, string) (memory.Thread, error)) *ThreadGateway_GetOrCreate_Call {
	_c.Call.Return(run)
	return _c
}
