// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/LimaTeixeiraTecnologia/mecontrola/internal/onboarding/application/dtos/input"
	"github.com/LimaTeixeiraTecnologia/mecontrola/internal/onboarding/application/usecases"
	mock "github.com/stretchr/testify/mock"
)

// newConsumeMagicTokenUseCase creates a new instance of consumeMagicTokenUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newConsumeMagicTokenUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *consumeMagicTokenUseCase {
	mock := &consumeMagicTokenUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// consumeMagicTokenUseCase is an autogenerated mock type for the consumeMagicTokenUseCase type
type consumeMagicTokenUseCase struct {
	mock.Mock
}

type consumeMagicTokenUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *consumeMagicTokenUseCase) EXPECT() *consumeMagicTokenUseCase_Expecter {
	return &consumeMagicTokenUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type consumeMagicTokenUseCase
func (_mock *consumeMagicTokenUseCase) Execute(ctx context.Context, in input.ConsumeMagicTokenInput) (usecases.ConsumeResult, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 usecases.ConsumeResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, input.ConsumeMagicTokenInput) (usecases.ConsumeResult, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, input.ConsumeMagicTokenInput) usecases.ConsumeResult); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(usecases.ConsumeResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, input.ConsumeMagicTokenInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// consumeMagicTokenUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type consumeMagicTokenUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - in input.ConsumeMagicTokenInput
func (_e *consumeMagicTokenUseCase_Expecter) Execute(ctx interface{}, in interface{}) *consumeMagicTokenUseCase_Execute_Call {
	return &consumeMagicTokenUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, in)}
}

func (_c *consumeMagicTokenUseCase_Execute_Call) Run(run func(ctx context.Context, in input.ConsumeMagicTokenInput)) *consumeMagicTokenUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 input.ConsumeMagicTokenInput
		if args[1] != nil {
			arg1 = args[1].(input.ConsumeMagicTokenInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *consumeMagicTokenUseCase_Execute_Call) Return(consumeResult usecases.ConsumeResult, err error) *consumeMagicTokenUseCase_Execute_Call {
	_c.Call.Return(consumeResult, err)
	return _c
}

func (_c *consumeMagicTokenUseCase_Execute_Call) RunAndReturn(run func(ctx context.Context, in input.ConsumeMagicTokenInput) (usecases.ConsumeResult, error)) *consumeMagicTokenUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
