// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/LimaTeixeiraTecnologia/mecontrola/internal/onboarding/application/usecases"
	mock "github.com/stretchr/testify/mock"
)

// newGetTokenStateUseCase creates a new instance of getTokenStateUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newGetTokenStateUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *getTokenStateUseCase {
	mock := &getTokenStateUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// getTokenStateUseCase is an autogenerated mock type for the getTokenStateUseCase type
type getTokenStateUseCase struct {
	mock.Mock
}

type getTokenStateUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *getTokenStateUseCase) EXPECT() *getTokenStateUseCase_Expecter {
	return &getTokenStateUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type getTokenStateUseCase
func (_mock *getTokenStateUseCase) Execute(ctx context.Context, clearToken string) (usecases.GetTokenStateResult, error) {
	ret := _mock.Called(ctx, clearToken)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 usecases.GetTokenStateResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (usecases.GetTokenStateResult, error)); ok {
		return returnFunc(ctx, clearToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) usecases.GetTokenStateResult); ok {
		r0 = returnFunc(ctx, clearToken)
	} else {
		r0 = ret.Get(0).(usecases.GetTokenStateResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, clearToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// getTokenStateUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type getTokenStateUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - clearToken string
func (_e *getTokenStateUseCase_Expecter) Execute(ctx interface{}, clearToken interface{}) *getTokenStateUseCase_Execute_Call {
	return &getTokenStateUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, clearToken)}
}

func (_c *getTokenStateUseCase_Execute_Call) Run(run func(ctx context.Context, clearToken string)) *getTokenStateUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *getTokenStateUseCase_Execute_Call) Return(getTokenStateResult usecases.GetTokenStateResult, err error) *getTokenStateUseCase_Execute_Call {
	_c.Call.Return(getTokenStateResult, err)
	return _c
}

func (_c *getTokenStateUseCase_Execute_Call) RunAndReturn(run func(ctx context.Context, clearToken string) (usecases.GetTokenStateResult, error)) *getTokenStateUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
