// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/LimaTeixeiraTecnologia/mecontrola/internal/onboarding/application/usecases"
	mock "github.com/stretchr/testify/mock"
)

// newTryFallbackActivationUseCase creates a new instance of tryFallbackActivationUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newTryFallbackActivationUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *tryFallbackActivationUseCase {
	mock := &tryFallbackActivationUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// tryFallbackActivationUseCase is an autogenerated mock type for the tryFallbackActivationUseCase type
type tryFallbackActivationUseCase struct {
	mock.Mock
}

type tryFallbackActivationUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *tryFallbackActivationUseCase) EXPECT() *tryFallbackActivationUseCase_Expecter {
	return &tryFallbackActivationUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type tryFallbackActivationUseCase
func (_mock *tryFallbackActivationUseCase) Execute(ctx context.Context, fromE164 string) (usecases.FallbackResult, error) {
	ret := _mock.Called(ctx, fromE164)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 usecases.FallbackResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (usecases.FallbackResult, error)); ok {
		return returnFunc(ctx, fromE164)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) usecases.FallbackResult); ok {
		r0 = returnFunc(ctx, fromE164)
	} else {
		r0 = ret.Get(0).(usecases.FallbackResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, fromE164)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// tryFallbackActivationUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type tryFallbackActivationUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - fromE164 string
func (_e *tryFallbackActivationUseCase_Expecter) Execute(ctx interface{}, fromE164 interface{}) *tryFallbackActivationUseCase_Execute_Call {
	return &tryFallbackActivationUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, fromE164)}
}

func (_c *tryFallbackActivationUseCase_Execute_Call) Run(run func(ctx context.Context, fromE164 string)) *tryFallbackActivationUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *tryFallbackActivationUseCase_Execute_Call) Return(fallbackResult usecases.FallbackResult, err error) *tryFallbackActivationUseCase_Execute_Call {
	_c.Call.Return(fallbackResult, err)
	return _c
}

func (_c *tryFallbackActivationUseCase_Execute_Call) RunAndReturn(run func(ctx context.Context, fromE164 string) (usecases.FallbackResult, error)) *tryFallbackActivationUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
