// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/LimaTeixeiraTecnologia/mecontrola/internal/identity/application/interfaces"
)

// NewEntitlementReader creates a new instance of EntitlementReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEntitlementReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *EntitlementReader {
	mock := &EntitlementReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// EntitlementReader is an autogenerated mock type for the EntitlementReader type
type EntitlementReader struct {
	mock.Mock
}

type EntitlementReader_Expecter struct {
	mock *mock.Mock
}

func (_m *EntitlementReader) EXPECT() *EntitlementReader_Expecter {
	return &EntitlementReader_Expecter{mock: &_m.Mock}
}

// FindByUserID provides a mock function for the type EntitlementReader
func (_mock *EntitlementReader) FindByUserID(ctx context.Context, userID string) (interfaces.EntitlementRecord, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 interfaces.EntitlementRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (interfaces.EntitlementRecord, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) interfaces.EntitlementRecord); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(interfaces.EntitlementRecord)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EntitlementReader_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type EntitlementReader_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *EntitlementReader_Expecter) FindByUserID(ctx any, userID any) *EntitlementReader_FindByUserID_Call {
	return &EntitlementReader_FindByUserID_Call{Call: _e.mock.On("FindByUserID", ctx, userID)}
}

func (_c *EntitlementReader_FindByUserID_Call) Run(run func(ctx context.Context, userID string)) *EntitlementReader_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EntitlementReader_FindByUserID_Call) Return(entitlementRecord interfaces.EntitlementRecord, err error) *EntitlementReader_FindByUserID_Call {
	_c.Call.Return(entitlementRecord, err)
	return _c
}

func (_c *EntitlementReader_FindByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string) (interfaces.EntitlementRecord, error)) *EntitlementReader_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}
