// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/LimaTeixeiraTecnologia/mecontrola/internal/identity/application/interfaces"
	mock "github.com/stretchr/testify/mock"
)

// NewEntitlementRepository creates a new instance of EntitlementRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEntitlementRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *EntitlementRepository {
	mock := &EntitlementRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// EntitlementRepository is an autogenerated mock type for the EntitlementRepository type
type EntitlementRepository struct {
	mock.Mock
}

type EntitlementRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *EntitlementRepository) EXPECT() *EntitlementRepository_Expecter {
	return &EntitlementRepository_Expecter{mock: &_m.Mock}
}

// FindByUserID provides a mock function for the type EntitlementRepository
func (_mock *EntitlementRepository) FindByUserID(ctx context.Context, userID string) (interfaces.EntitlementRecord, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 interfaces.EntitlementRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (interfaces.EntitlementRecord, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) interfaces.EntitlementRecord); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(interfaces.EntitlementRecord)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EntitlementRepository_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type EntitlementRepository_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *EntitlementRepository_Expecter) FindByUserID(ctx interface{}, userID interface{}) *EntitlementRepository_FindByUserID_Call {
	return &EntitlementRepository_FindByUserID_Call{Call: _e.mock.On("FindByUserID", ctx, userID)}
}

func (_c *EntitlementRepository_FindByUserID_Call) Run(run func(ctx context.Context, userID string)) *EntitlementRepository_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EntitlementRepository_FindByUserID_Call) Return(entitlementRecord interfaces.EntitlementRecord, err error) *EntitlementRepository_FindByUserID_Call {
	_c.Call.Return(entitlementRecord, err)
	return _c
}

func (_c *EntitlementRepository_FindByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string) (interfaces.EntitlementRecord, error)) *EntitlementRepository_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type EntitlementRepository
func (_mock *EntitlementRepository) Upsert(ctx context.Context, record interfaces.EntitlementRecord) error {
	ret := _mock.Called(ctx, record)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interfaces.EntitlementRecord) error); ok {
		r0 = returnFunc(ctx, record)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EntitlementRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type EntitlementRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - record interfaces.EntitlementRecord
func (_e *EntitlementRepository_Expecter) Upsert(ctx interface{}, record interface{}) *EntitlementRepository_Upsert_Call {
	return &EntitlementRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, record)}
}

func (_c *EntitlementRepository_Upsert_Call) Run(run func(ctx context.Context, record interfaces.EntitlementRecord)) *EntitlementRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interfaces.EntitlementRecord
		if args[1] != nil {
			arg1 = args[1].(interfaces.EntitlementRecord)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EntitlementRepository_Upsert_Call) Return(err error) *EntitlementRepository_Upsert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EntitlementRepository_Upsert_Call) RunAndReturn(run func(ctx context.Context, record interfaces.EntitlementRecord) error) *EntitlementRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertPending provides a mock function for the type EntitlementRepository
func (_mock *EntitlementRepository) UpsertPending(ctx context.Context, subscriptionID string, funnelToken string, payload []byte) error {
	ret := _mock.Called(ctx, subscriptionID, funnelToken, payload)

	if len(ret) == 0 {
		panic("no return value specified for UpsertPending")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []byte) error); ok {
		r0 = returnFunc(ctx, subscriptionID, funnelToken, payload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EntitlementRepository_UpsertPending_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertPending'
type EntitlementRepository_UpsertPending_Call struct {
	*mock.Call
}

// UpsertPending is a helper method to define mock.On call
//   - ctx context.Context
//   - subscriptionID string
//   - funnelToken string
//   - payload []byte
func (_e *EntitlementRepository_Expecter) UpsertPending(ctx interface{}, subscriptionID interface{}, funnelToken interface{}, payload interface{}) *EntitlementRepository_UpsertPending_Call {
	return &EntitlementRepository_UpsertPending_Call{Call: _e.mock.On("UpsertPending", ctx, subscriptionID, funnelToken, payload)}
}

func (_c *EntitlementRepository_UpsertPending_Call) Run(run func(ctx context.Context, subscriptionID string, funnelToken string, payload []byte)) *EntitlementRepository_UpsertPending_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *EntitlementRepository_UpsertPending_Call) Return(err error) *EntitlementRepository_UpsertPending_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EntitlementRepository_UpsertPending_Call) RunAndReturn(run func(ctx context.Context, subscriptionID string, funnelToken string, payload []byte) error) *EntitlementRepository_UpsertPending_Call {
	_c.Call.Return(run)
	return _c
}
