// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/JailtonJunior94/devkit-go/pkg/database"
	"github.com/LimaTeixeiraTecnologia/mecontrola/internal/identity/application/interfaces"
	mock "github.com/stretchr/testify/mock"
)

// NewRepositoryFactory creates a new instance of RepositoryFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepositoryFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepositoryFactory {
	mock := &RepositoryFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RepositoryFactory is an autogenerated mock type for the RepositoryFactory type
type RepositoryFactory struct {
	mock.Mock
}

type RepositoryFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *RepositoryFactory) EXPECT() *RepositoryFactory_Expecter {
	return &RepositoryFactory_Expecter{mock: &_m.Mock}
}

// EntitlementRepository provides a mock function for the type RepositoryFactory
func (_mock *RepositoryFactory) EntitlementRepository(db database.DBTX) interfaces.EntitlementRepository {
	ret := _mock.Called(db)

	if len(ret) == 0 {
		panic("no return value specified for EntitlementRepository")
	}

	var r0 interfaces.EntitlementRepository
	if returnFunc, ok := ret.Get(0).(func(database.DBTX) interfaces.EntitlementRepository); ok {
		r0 = returnFunc(db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.EntitlementRepository)
		}
	}
	return r0
}

// RepositoryFactory_EntitlementRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EntitlementRepository'
type RepositoryFactory_EntitlementRepository_Call struct {
	*mock.Call
}

// EntitlementRepository is a helper method to define mock.On call
//   - db database.DBTX
func (_e *RepositoryFactory_Expecter) EntitlementRepository(db interface{}) *RepositoryFactory_EntitlementRepository_Call {
	return &RepositoryFactory_EntitlementRepository_Call{Call: _e.mock.On("EntitlementRepository", db)}
}

func (_c *RepositoryFactory_EntitlementRepository_Call) Run(run func(db database.DBTX)) *RepositoryFactory_EntitlementRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 database.DBTX
		if args[0] != nil {
			arg0 = args[0].(database.DBTX)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RepositoryFactory_EntitlementRepository_Call) Return(entitlementRepository interfaces.EntitlementRepository) *RepositoryFactory_EntitlementRepository_Call {
	_c.Call.Return(entitlementRepository)
	return _c
}

func (_c *RepositoryFactory_EntitlementRepository_Call) RunAndReturn(run func(db database.DBTX) interfaces.EntitlementRepository) *RepositoryFactory_EntitlementRepository_Call {
	_c.Call.Return(run)
	return _c
}

// UserRepository provides a mock function for the type RepositoryFactory
func (_mock *RepositoryFactory) UserRepository(db database.DBTX) interfaces.UserRepository {
	ret := _mock.Called(db)

	if len(ret) == 0 {
		panic("no return value specified for UserRepository")
	}

	var r0 interfaces.UserRepository
	if returnFunc, ok := ret.Get(0).(func(database.DBTX) interfaces.UserRepository); ok {
		r0 = returnFunc(db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.UserRepository)
		}
	}
	return r0
}

// RepositoryFactory_UserRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserRepository'
type RepositoryFactory_UserRepository_Call struct {
	*mock.Call
}

// UserRepository is a helper method to define mock.On call
//   - db database.DBTX
func (_e *RepositoryFactory_Expecter) UserRepository(db interface{}) *RepositoryFactory_UserRepository_Call {
	return &RepositoryFactory_UserRepository_Call{Call: _e.mock.On("UserRepository", db)}
}

func (_c *RepositoryFactory_UserRepository_Call) Run(run func(db database.DBTX)) *RepositoryFactory_UserRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 database.DBTX
		if args[0] != nil {
			arg0 = args[0].(database.DBTX)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RepositoryFactory_UserRepository_Call) Return(userRepository interfaces.UserRepository) *RepositoryFactory_UserRepository_Call {
	_c.Call.Return(userRepository)
	return _c
}

func (_c *RepositoryFactory_UserRepository_Call) RunAndReturn(run func(db database.DBTX) interfaces.UserRepository) *RepositoryFactory_UserRepository_Call {
	_c.Call.Return(run)
	return _c
}
