// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/LimaTeixeiraTecnologia/mecontrola/internal/identity/domain/entities"

	mock "github.com/stretchr/testify/mock"

	time "time"

	valueobjects "github.com/LimaTeixeiraTecnologia/mecontrola/internal/identity/domain/valueobjects"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

type UserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepository) EXPECT() *UserRepository_Expecter {
	return &UserRepository_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *UserRepository) FindByID(ctx context.Context, id entities.UserID) (*entities.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entities.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.UserID) (*entities.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entities.UserID) *entities.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entities.UserID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type UserRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id entities.UserID
func (_e *UserRepository_Expecter) FindByID(ctx interface{}, id interface{}) *UserRepository_FindByID_Call {
	return &UserRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *UserRepository_FindByID_Call) Run(run func(ctx context.Context, id entities.UserID)) *UserRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entities.UserID))
	})
	return _c
}

func (_c *UserRepository_FindByID_Call) Return(_a0 *entities.User, _a1 error) *UserRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_FindByID_Call) RunAndReturn(run func(context.Context, entities.UserID) (*entities.User, error)) *UserRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByWhatsAppNumber provides a mock function with given fields: ctx, number
func (_m *UserRepository) FindByWhatsAppNumber(ctx context.Context, number valueobjects.WhatsAppNumber) (*entities.User, error) {
	ret := _m.Called(ctx, number)

	if len(ret) == 0 {
		panic("no return value specified for FindByWhatsAppNumber")
	}

	var r0 *entities.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobjects.WhatsAppNumber) (*entities.User, error)); ok {
		return rf(ctx, number)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobjects.WhatsAppNumber) *entities.User); ok {
		r0 = rf(ctx, number)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobjects.WhatsAppNumber) error); ok {
		r1 = rf(ctx, number)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_FindByWhatsAppNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByWhatsAppNumber'
type UserRepository_FindByWhatsAppNumber_Call struct {
	*mock.Call
}

// FindByWhatsAppNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - number valueobjects.WhatsAppNumber
func (_e *UserRepository_Expecter) FindByWhatsAppNumber(ctx interface{}, number interface{}) *UserRepository_FindByWhatsAppNumber_Call {
	return &UserRepository_FindByWhatsAppNumber_Call{Call: _e.mock.On("FindByWhatsAppNumber", ctx, number)}
}

func (_c *UserRepository_FindByWhatsAppNumber_Call) Run(run func(ctx context.Context, number valueobjects.WhatsAppNumber)) *UserRepository_FindByWhatsAppNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobjects.WhatsAppNumber))
	})
	return _c
}

func (_c *UserRepository_FindByWhatsAppNumber_Call) Return(_a0 *entities.User, _a1 error) *UserRepository_FindByWhatsAppNumber_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_FindByWhatsAppNumber_Call) RunAndReturn(run func(context.Context, valueobjects.WhatsAppNumber) (*entities.User, error)) *UserRepository_FindByWhatsAppNumber_Call {
	_c.Call.Return(run)
	return _c
}

// LinkNewNumber provides a mock function with given fields: ctx, id, number, reason, now
func (_m *UserRepository) LinkNewNumber(ctx context.Context, id entities.UserID, number valueobjects.WhatsAppNumber, reason string, now time.Time) error {
	ret := _m.Called(ctx, id, number, reason, now)

	if len(ret) == 0 {
		panic("no return value specified for LinkNewNumber")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.UserID, valueobjects.WhatsAppNumber, string, time.Time) error); ok {
		r0 = rf(ctx, id, number, reason, now)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserRepository_LinkNewNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LinkNewNumber'
type UserRepository_LinkNewNumber_Call struct {
	*mock.Call
}

// LinkNewNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - id entities.UserID
//   - number valueobjects.WhatsAppNumber
//   - reason string
//   - now time.Time
func (_e *UserRepository_Expecter) LinkNewNumber(ctx interface{}, id interface{}, number interface{}, reason interface{}, now interface{}) *UserRepository_LinkNewNumber_Call {
	return &UserRepository_LinkNewNumber_Call{Call: _e.mock.On("LinkNewNumber", ctx, id, number, reason, now)}
}

func (_c *UserRepository_LinkNewNumber_Call) Run(run func(ctx context.Context, id entities.UserID, number valueobjects.WhatsAppNumber, reason string, now time.Time)) *UserRepository_LinkNewNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entities.UserID), args[2].(valueobjects.WhatsAppNumber), args[3].(string), args[4].(time.Time))
	})
	return _c
}

func (_c *UserRepository_LinkNewNumber_Call) Return(_a0 error) *UserRepository_LinkNewNumber_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserRepository_LinkNewNumber_Call) RunAndReturn(run func(context.Context, entities.UserID, valueobjects.WhatsAppNumber, string, time.Time) error) *UserRepository_LinkNewNumber_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDelete provides a mock function with given fields: ctx, id, now
func (_m *UserRepository) SoftDelete(ctx context.Context, id entities.UserID, now time.Time) error {
	ret := _m.Called(ctx, id, now)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.UserID, time.Time) error); ok {
		r0 = rf(ctx, id, now)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserRepository_SoftDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDelete'
type UserRepository_SoftDelete_Call struct {
	*mock.Call
}

// SoftDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - id entities.UserID
//   - now time.Time
func (_e *UserRepository_Expecter) SoftDelete(ctx interface{}, id interface{}, now interface{}) *UserRepository_SoftDelete_Call {
	return &UserRepository_SoftDelete_Call{Call: _e.mock.On("SoftDelete", ctx, id, now)}
}

func (_c *UserRepository_SoftDelete_Call) Run(run func(ctx context.Context, id entities.UserID, now time.Time)) *UserRepository_SoftDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entities.UserID), args[2].(time.Time))
	})
	return _c
}

func (_c *UserRepository_SoftDelete_Call) Return(_a0 error) *UserRepository_SoftDelete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserRepository_SoftDelete_Call) RunAndReturn(run func(context.Context, entities.UserID, time.Time) error) *UserRepository_SoftDelete_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertByWhatsAppNumber provides a mock function with given fields: ctx, number, now
func (_m *UserRepository) UpsertByWhatsAppNumber(ctx context.Context, number valueobjects.WhatsAppNumber, now time.Time) (*entities.User, error) {
	ret := _m.Called(ctx, number, now)

	if len(ret) == 0 {
		panic("no return value specified for UpsertByWhatsAppNumber")
	}

	var r0 *entities.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobjects.WhatsAppNumber, time.Time) (*entities.User, error)); ok {
		return rf(ctx, number, now)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobjects.WhatsAppNumber, time.Time) *entities.User); ok {
		r0 = rf(ctx, number, now)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobjects.WhatsAppNumber, time.Time) error); ok {
		r1 = rf(ctx, number, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_UpsertByWhatsAppNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertByWhatsAppNumber'
type UserRepository_UpsertByWhatsAppNumber_Call struct {
	*mock.Call
}

// UpsertByWhatsAppNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - number valueobjects.WhatsAppNumber
//   - now time.Time
func (_e *UserRepository_Expecter) UpsertByWhatsAppNumber(ctx interface{}, number interface{}, now interface{}) *UserRepository_UpsertByWhatsAppNumber_Call {
	return &UserRepository_UpsertByWhatsAppNumber_Call{Call: _e.mock.On("UpsertByWhatsAppNumber", ctx, number, now)}
}

func (_c *UserRepository_UpsertByWhatsAppNumber_Call) Run(run func(ctx context.Context, number valueobjects.WhatsAppNumber, now time.Time)) *UserRepository_UpsertByWhatsAppNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobjects.WhatsAppNumber), args[2].(time.Time))
	})
	return _c
}

func (_c *UserRepository_UpsertByWhatsAppNumber_Call) Return(_a0 *entities.User, _a1 error) *UserRepository_UpsertByWhatsAppNumber_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_UpsertByWhatsAppNumber_Call) RunAndReturn(run func(context.Context, valueobjects.WhatsAppNumber, time.Time) (*entities.User, error)) *UserRepository_UpsertByWhatsAppNumber_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
