// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/LimaTeixeiraTecnologia/mecontrola/internal/identity/domain/entities"
	"github.com/LimaTeixeiraTecnologia/mecontrola/internal/identity/domain/valueobjects"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewUserIdentityRepository creates a new instance of UserIdentityRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserIdentityRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserIdentityRepository {
	mock := &UserIdentityRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserIdentityRepository is an autogenerated mock type for the UserIdentityRepository type
type UserIdentityRepository struct {
	mock.Mock
}

type UserIdentityRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *UserIdentityRepository) EXPECT() *UserIdentityRepository_Expecter {
	return &UserIdentityRepository_Expecter{mock: &_m.Mock}
}

// FindByUserAndChannel provides a mock function for the type UserIdentityRepository
func (_mock *UserIdentityRepository) FindByUserAndChannel(ctx context.Context, userID uuid.UUID, channel valueobjects.Channel) (entities.UserIdentity, bool, error) {
	ret := _mock.Called(ctx, userID, channel)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserAndChannel")
	}

	var r0 entities.UserIdentity
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, valueobjects.Channel) (entities.UserIdentity, bool, error)); ok {
		return returnFunc(ctx, userID, channel)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, valueobjects.Channel) entities.UserIdentity); ok {
		r0 = returnFunc(ctx, userID, channel)
	} else {
		r0 = ret.Get(0).(entities.UserIdentity)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, valueobjects.Channel) bool); ok {
		r1 = returnFunc(ctx, userID, channel)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID, valueobjects.Channel) error); ok {
		r2 = returnFunc(ctx, userID, channel)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// UserIdentityRepository_FindByUserAndChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserAndChannel'
type UserIdentityRepository_FindByUserAndChannel_Call struct {
	*mock.Call
}

// FindByUserAndChannel is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - channel valueobjects.Channel
func (_e *UserIdentityRepository_Expecter) FindByUserAndChannel(ctx any, userID any, channel any) *UserIdentityRepository_FindByUserAndChannel_Call {
	return &UserIdentityRepository_FindByUserAndChannel_Call{Call: _e.mock.On("FindByUserAndChannel", ctx, userID, channel)}
}

func (_c *UserIdentityRepository_FindByUserAndChannel_Call) Run(run func(ctx context.Context, userID uuid.UUID, channel valueobjects.Channel)) *UserIdentityRepository_FindByUserAndChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 valueobjects.Channel
		if args[2] != nil {
			arg2 = args[2].(valueobjects.Channel)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserIdentityRepository_FindByUserAndChannel_Call) Return(userIdentity entities.UserIdentity, b bool, err error) *UserIdentityRepository_FindByUserAndChannel_Call {
	_c.Call.Return(userIdentity, b, err)
	return _c
}

func (_c *UserIdentityRepository_FindByUserAndChannel_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, channel valueobjects.Channel) (entities.UserIdentity, bool, error)) *UserIdentityRepository_FindByUserAndChannel_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type UserIdentityRepository
func (_mock *UserIdentityRepository) Insert(ctx context.Context, identity entities.UserIdentity) error {
	ret := _mock.Called(ctx, identity)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.UserIdentity) error); ok {
		r0 = returnFunc(ctx, identity)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserIdentityRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type UserIdentityRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - identity entities.UserIdentity
func (_e *UserIdentityRepository_Expecter) Insert(ctx any, identity any) *UserIdentityRepository_Insert_Call {
	return &UserIdentityRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, identity)}
}

func (_c *UserIdentityRepository_Insert_Call) Run(run func(ctx context.Context, identity entities.UserIdentity)) *UserIdentityRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.UserIdentity
		if args[1] != nil {
			arg1 = args[1].(entities.UserIdentity)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserIdentityRepository_Insert_Call) Return(err error) *UserIdentityRepository_Insert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserIdentityRepository_Insert_Call) RunAndReturn(run func(ctx context.Context, identity entities.UserIdentity) error) *UserIdentityRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function for the type UserIdentityRepository
func (_mock *UserIdentityRepository) ListByUser(ctx context.Context, userID uuid.UUID) ([]entities.UserIdentity, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []entities.UserIdentity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]entities.UserIdentity, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []entities.UserIdentity); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.UserIdentity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserIdentityRepository_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type UserIdentityRepository_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *UserIdentityRepository_Expecter) ListByUser(ctx any, userID any) *UserIdentityRepository_ListByUser_Call {
	return &UserIdentityRepository_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID)}
}

func (_c *UserIdentityRepository_ListByUser_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *UserIdentityRepository_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserIdentityRepository_ListByUser_Call) Return(userIdentitys []entities.UserIdentity, err error) *UserIdentityRepository_ListByUser_Call {
	_c.Call.Return(userIdentitys, err)
	return _c
}

func (_c *UserIdentityRepository_ListByUser_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]entities.UserIdentity, error)) *UserIdentityRepository_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// TryFindActive provides a mock function for the type UserIdentityRepository
func (_mock *UserIdentityRepository) TryFindActive(ctx context.Context, channel valueobjects.Channel, externalID valueobjects.ExternalID) (entities.UserIdentity, bool, error) {
	ret := _mock.Called(ctx, channel, externalID)

	if len(ret) == 0 {
		panic("no return value specified for TryFindActive")
	}

	var r0 entities.UserIdentity
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, valueobjects.Channel, valueobjects.ExternalID) (entities.UserIdentity, bool, error)); ok {
		return returnFunc(ctx, channel, externalID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, valueobjects.Channel, valueobjects.ExternalID) entities.UserIdentity); ok {
		r0 = returnFunc(ctx, channel, externalID)
	} else {
		r0 = ret.Get(0).(entities.UserIdentity)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, valueobjects.Channel, valueobjects.ExternalID) bool); ok {
		r1 = returnFunc(ctx, channel, externalID)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, valueobjects.Channel, valueobjects.ExternalID) error); ok {
		r2 = returnFunc(ctx, channel, externalID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// UserIdentityRepository_TryFindActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TryFindActive'
type UserIdentityRepository_TryFindActive_Call struct {
	*mock.Call
}

// TryFindActive is a helper method to define mock.On call
//   - ctx context.Context
//   - channel valueobjects.Channel
//   - externalID valueobjects.ExternalID
func (_e *UserIdentityRepository_Expecter) TryFindActive(ctx any, channel any, externalID any) *UserIdentityRepository_TryFindActive_Call {
	return &UserIdentityRepository_TryFindActive_Call{Call: _e.mock.On("TryFindActive", ctx, channel, externalID)}
}

func (_c *UserIdentityRepository_TryFindActive_Call) Run(run func(ctx context.Context, channel valueobjects.Channel, externalID valueobjects.ExternalID)) *UserIdentityRepository_TryFindActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 valueobjects.Channel
		if args[1] != nil {
			arg1 = args[1].(valueobjects.Channel)
		}
		var arg2 valueobjects.ExternalID
		if args[2] != nil {
			arg2 = args[2].(valueobjects.ExternalID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserIdentityRepository_TryFindActive_Call) Return(userIdentity entities.UserIdentity, b bool, err error) *UserIdentityRepository_TryFindActive_Call {
	_c.Call.Return(userIdentity, b, err)
	return _c
}

func (_c *UserIdentityRepository_TryFindActive_Call) RunAndReturn(run func(ctx context.Context, channel valueobjects.Channel, externalID valueobjects.ExternalID) (entities.UserIdentity, bool, error)) *UserIdentityRepository_TryFindActive_Call {
	_c.Call.Return(run)
	return _c
}

// Unlink provides a mock function for the type UserIdentityRepository
func (_mock *UserIdentityRepository) Unlink(ctx context.Context, id uuid.UUID, now time.Time) error {
	ret := _mock.Called(ctx, id, now)

	if len(ret) == 0 {
		panic("no return value specified for Unlink")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r0 = returnFunc(ctx, id, now)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserIdentityRepository_Unlink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unlink'
type UserIdentityRepository_Unlink_Call struct {
	*mock.Call
}

// Unlink is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - now time.Time
func (_e *UserIdentityRepository_Expecter) Unlink(ctx any, id any, now any) *UserIdentityRepository_Unlink_Call {
	return &UserIdentityRepository_Unlink_Call{Call: _e.mock.On("Unlink", ctx, id, now)}
}

func (_c *UserIdentityRepository_Unlink_Call) Run(run func(ctx context.Context, id uuid.UUID, now time.Time)) *UserIdentityRepository_Unlink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserIdentityRepository_Unlink_Call) Return(err error) *UserIdentityRepository_Unlink_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserIdentityRepository_Unlink_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, now time.Time) error) *UserIdentityRepository_Unlink_Call {
	_c.Call.Return(run)
	return _c
}
