// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"

	"github.com/LimaTeixeiraTecnologia/mecontrola/internal/transactions/domain/entities"
	"github.com/LimaTeixeiraTecnologia/mecontrola/internal/transactions/domain/valueobjects"
)

// NewCardInvoiceRepository creates a new instance of CardInvoiceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCardInvoiceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CardInvoiceRepository {
	mock := &CardInvoiceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CardInvoiceRepository is an autogenerated mock type for the CardInvoiceRepository type
type CardInvoiceRepository struct {
	mock.Mock
}

type CardInvoiceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CardInvoiceRepository) EXPECT() *CardInvoiceRepository_Expecter {
	return &CardInvoiceRepository_Expecter{mock: &_m.Mock}
}

// ApplyDelta provides a mock function for the type CardInvoiceRepository
func (_mock *CardInvoiceRepository) ApplyDelta(ctx context.Context, invoiceID uuid.UUID, deltaCents int64, expectedVersion int64) error {
	ret := _mock.Called(ctx, invoiceID, deltaCents, expectedVersion)

	if len(ret) == 0 {
		panic("no return value specified for ApplyDelta")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64, int64) error); ok {
		r0 = returnFunc(ctx, invoiceID, deltaCents, expectedVersion)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CardInvoiceRepository_ApplyDelta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyDelta'
type CardInvoiceRepository_ApplyDelta_Call struct {
	*mock.Call
}

// ApplyDelta is a helper method to define mock.On call
//   - ctx context.Context
//   - invoiceID uuid.UUID
//   - deltaCents int64
//   - expectedVersion int64
func (_e *CardInvoiceRepository_Expecter) ApplyDelta(ctx any, invoiceID any, deltaCents any, expectedVersion any) *CardInvoiceRepository_ApplyDelta_Call {
	return &CardInvoiceRepository_ApplyDelta_Call{Call: _e.mock.On("ApplyDelta", ctx, invoiceID, deltaCents, expectedVersion)}
}

func (_c *CardInvoiceRepository_ApplyDelta_Call) Run(run func(ctx context.Context, invoiceID uuid.UUID, deltaCents int64, expectedVersion int64)) *CardInvoiceRepository_ApplyDelta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *CardInvoiceRepository_ApplyDelta_Call) Return(err error) *CardInvoiceRepository_ApplyDelta_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CardInvoiceRepository_ApplyDelta_Call) RunAndReturn(run func(ctx context.Context, invoiceID uuid.UUID, deltaCents int64, expectedVersion int64) error) *CardInvoiceRepository_ApplyDelta_Call {
	_c.Call.Return(run)
	return _c
}

// GetByMonth provides a mock function for the type CardInvoiceRepository
func (_mock *CardInvoiceRepository) GetByMonth(ctx context.Context, userID uuid.UUID, cardID uuid.UUID, refMonth valueobjects.RefMonth) (*entities.CardInvoice, []*entities.CardInvoiceItem, error) {
	ret := _mock.Called(ctx, userID, cardID, refMonth)

	if len(ret) == 0 {
		panic("no return value specified for GetByMonth")
	}

	var r0 *entities.CardInvoice
	var r1 []*entities.CardInvoiceItem
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, valueobjects.RefMonth) (*entities.CardInvoice, []*entities.CardInvoiceItem, error)); ok {
		return returnFunc(ctx, userID, cardID, refMonth)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, valueobjects.RefMonth) *entities.CardInvoice); ok {
		r0 = returnFunc(ctx, userID, cardID, refMonth)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.CardInvoice)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, valueobjects.RefMonth) []*entities.CardInvoiceItem); ok {
		r1 = returnFunc(ctx, userID, cardID, refMonth)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]*entities.CardInvoiceItem)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID, uuid.UUID, valueobjects.RefMonth) error); ok {
		r2 = returnFunc(ctx, userID, cardID, refMonth)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// CardInvoiceRepository_GetByMonth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByMonth'
type CardInvoiceRepository_GetByMonth_Call struct {
	*mock.Call
}

// GetByMonth is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - cardID uuid.UUID
//   - refMonth valueobjects.RefMonth
func (_e *CardInvoiceRepository_Expecter) GetByMonth(ctx any, userID any, cardID any, refMonth any) *CardInvoiceRepository_GetByMonth_Call {
	return &CardInvoiceRepository_GetByMonth_Call{Call: _e.mock.On("GetByMonth", ctx, userID, cardID, refMonth)}
}

func (_c *CardInvoiceRepository_GetByMonth_Call) Run(run func(ctx context.Context, userID uuid.UUID, cardID uuid.UUID, refMonth valueobjects.RefMonth)) *CardInvoiceRepository_GetByMonth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 valueobjects.RefMonth
		if args[3] != nil {
			arg3 = args[3].(valueobjects.RefMonth)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *CardInvoiceRepository_GetByMonth_Call) Return(cardInvoice *entities.CardInvoice, cardInvoiceItems []*entities.CardInvoiceItem, err error) *CardInvoiceRepository_GetByMonth_Call {
	_c.Call.Return(cardInvoice, cardInvoiceItems, err)
	return _c
}

func (_c *CardInvoiceRepository_GetByMonth_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, cardID uuid.UUID, refMonth valueobjects.RefMonth) (*entities.CardInvoice, []*entities.CardInvoiceItem, error)) *CardInvoiceRepository_GetByMonth_Call {
	_c.Call.Return(run)
	return _c
}

// SumByMonth provides a mock function for the type CardInvoiceRepository
func (_mock *CardInvoiceRepository) SumByMonth(ctx context.Context, userID uuid.UUID, refMonth valueobjects.RefMonth) (int64, error) {
	ret := _mock.Called(ctx, userID, refMonth)

	if len(ret) == 0 {
		panic("no return value specified for SumByMonth")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, valueobjects.RefMonth) (int64, error)); ok {
		return returnFunc(ctx, userID, refMonth)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, valueobjects.RefMonth) int64); ok {
		r0 = returnFunc(ctx, userID, refMonth)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, valueobjects.RefMonth) error); ok {
		r1 = returnFunc(ctx, userID, refMonth)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CardInvoiceRepository_SumByMonth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SumByMonth'
type CardInvoiceRepository_SumByMonth_Call struct {
	*mock.Call
}

// SumByMonth is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - refMonth valueobjects.RefMonth
func (_e *CardInvoiceRepository_Expecter) SumByMonth(ctx any, userID any, refMonth any) *CardInvoiceRepository_SumByMonth_Call {
	return &CardInvoiceRepository_SumByMonth_Call{Call: _e.mock.On("SumByMonth", ctx, userID, refMonth)}
}

func (_c *CardInvoiceRepository_SumByMonth_Call) Run(run func(ctx context.Context, userID uuid.UUID, refMonth valueobjects.RefMonth)) *CardInvoiceRepository_SumByMonth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 valueobjects.RefMonth
		if args[2] != nil {
			arg2 = args[2].(valueobjects.RefMonth)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CardInvoiceRepository_SumByMonth_Call) Return(outcomeCents int64, err error) *CardInvoiceRepository_SumByMonth_Call {
	_c.Call.Return(outcomeCents, err)
	return _c
}

func (_c *CardInvoiceRepository_SumByMonth_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, refMonth valueobjects.RefMonth) (int64, error)) *CardInvoiceRepository_SumByMonth_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertByMonth provides a mock function for the type CardInvoiceRepository
func (_mock *CardInvoiceRepository) UpsertByMonth(ctx context.Context, userID uuid.UUID, cardID uuid.UUID, refMonth valueobjects.RefMonth, closingAt time.Time, dueAt time.Time) (*entities.CardInvoice, error) {
	ret := _mock.Called(ctx, userID, cardID, refMonth, closingAt, dueAt)

	if len(ret) == 0 {
		panic("no return value specified for UpsertByMonth")
	}

	var r0 *entities.CardInvoice
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, valueobjects.RefMonth, time.Time, time.Time) (*entities.CardInvoice, error)); ok {
		return returnFunc(ctx, userID, cardID, refMonth, closingAt, dueAt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, valueobjects.RefMonth, time.Time, time.Time) *entities.CardInvoice); ok {
		r0 = returnFunc(ctx, userID, cardID, refMonth, closingAt, dueAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.CardInvoice)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, valueobjects.RefMonth, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, userID, cardID, refMonth, closingAt, dueAt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CardInvoiceRepository_UpsertByMonth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertByMonth'
type CardInvoiceRepository_UpsertByMonth_Call struct {
	*mock.Call
}

// UpsertByMonth is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - cardID uuid.UUID
//   - refMonth valueobjects.RefMonth
//   - closingAt time.Time
//   - dueAt time.Time
func (_e *CardInvoiceRepository_Expecter) UpsertByMonth(ctx any, userID any, cardID any, refMonth any, closingAt any, dueAt any) *CardInvoiceRepository_UpsertByMonth_Call {
	return &CardInvoiceRepository_UpsertByMonth_Call{Call: _e.mock.On("UpsertByMonth", ctx, userID, cardID, refMonth, closingAt, dueAt)}
}

func (_c *CardInvoiceRepository_UpsertByMonth_Call) Run(run func(ctx context.Context, userID uuid.UUID, cardID uuid.UUID, refMonth valueobjects.RefMonth, closingAt time.Time, dueAt time.Time)) *CardInvoiceRepository_UpsertByMonth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 valueobjects.RefMonth
		if args[3] != nil {
			arg3 = args[3].(valueobjects.RefMonth)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		var arg5 time.Time
		if args[5] != nil {
			arg5 = args[5].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *CardInvoiceRepository_UpsertByMonth_Call) Return(cardInvoice *entities.CardInvoice, err error) *CardInvoiceRepository_UpsertByMonth_Call {
	_c.Call.Return(cardInvoice, err)
	return _c
}

func (_c *CardInvoiceRepository_UpsertByMonth_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, cardID uuid.UUID, refMonth valueobjects.RefMonth, closingAt time.Time, dueAt time.Time) (*entities.CardInvoice, error)) *CardInvoiceRepository_UpsertByMonth_Call {
	_c.Call.Return(run)
	return _c
}
