// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/LimaTeixeiraTecnologia/mecontrola/internal/transactions/application/interfaces"
	"github.com/LimaTeixeiraTecnologia/mecontrola/internal/transactions/domain/valueobjects"
	mock "github.com/stretchr/testify/mock"
)

// NewCategoryWriteGate creates a new instance of CategoryWriteGate. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCategoryWriteGate(t interface {
	mock.TestingT
	Cleanup(func())
}) *CategoryWriteGate {
	mock := &CategoryWriteGate{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CategoryWriteGate is an autogenerated mock type for the CategoryWriteGate type
type CategoryWriteGate struct {
	mock.Mock
}

type CategoryWriteGate_Expecter struct {
	mock *mock.Mock
}

func (_m *CategoryWriteGate) EXPECT() *CategoryWriteGate_Expecter {
	return &CategoryWriteGate_Expecter{mock: &_m.Mock}
}

// Approve provides a mock function for the type CategoryWriteGate
func (_mock *CategoryWriteGate) Approve(ctx context.Context, in interfaces.CategoryWriteGateInput) (valueobjects.CategoryWriteEvidence, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Approve")
	}

	var r0 valueobjects.CategoryWriteEvidence
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interfaces.CategoryWriteGateInput) (valueobjects.CategoryWriteEvidence, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, interfaces.CategoryWriteGateInput) valueobjects.CategoryWriteEvidence); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(valueobjects.CategoryWriteEvidence)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, interfaces.CategoryWriteGateInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CategoryWriteGate_Approve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Approve'
type CategoryWriteGate_Approve_Call struct {
	*mock.Call
}

// Approve is a helper method to define mock.On call
//   - ctx context.Context
//   - in interfaces.CategoryWriteGateInput
func (_e *CategoryWriteGate_Expecter) Approve(ctx any, in any) *CategoryWriteGate_Approve_Call {
	return &CategoryWriteGate_Approve_Call{Call: _e.mock.On("Approve", ctx, in)}
}

func (_c *CategoryWriteGate_Approve_Call) Run(run func(ctx context.Context, in interfaces.CategoryWriteGateInput)) *CategoryWriteGate_Approve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interfaces.CategoryWriteGateInput
		if args[1] != nil {
			arg1 = args[1].(interfaces.CategoryWriteGateInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CategoryWriteGate_Approve_Call) Return(categoryWriteEvidence valueobjects.CategoryWriteEvidence, err error) *CategoryWriteGate_Approve_Call {
	_c.Call.Return(categoryWriteEvidence, err)
	return _c
}

func (_c *CategoryWriteGate_Approve_Call) RunAndReturn(run func(ctx context.Context, in interfaces.CategoryWriteGateInput) (valueobjects.CategoryWriteEvidence, error)) *CategoryWriteGate_Approve_Call {
	_c.Call.Return(run)
	return _c
}
