// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"

	"github.com/LimaTeixeiraTecnologia/mecontrola/internal/transactions/application/interfaces"
)

// NewCategoryValidator creates a new instance of CategoryValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCategoryValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *CategoryValidator {
	mock := &CategoryValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CategoryValidator is an autogenerated mock type for the CategoryValidator type
type CategoryValidator struct {
	mock.Mock
}

type CategoryValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *CategoryValidator) EXPECT() *CategoryValidator_Expecter {
	return &CategoryValidator_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function for the type CategoryValidator
func (_mock *CategoryValidator) Validate(ctx context.Context, categoryID uuid.UUID, subcategoryID *uuid.UUID) (interfaces.CategorySnapshot, error) {
	ret := _mock.Called(ctx, categoryID, subcategoryID)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 interfaces.CategorySnapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *uuid.UUID) (interfaces.CategorySnapshot, error)); ok {
		return returnFunc(ctx, categoryID, subcategoryID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *uuid.UUID) interfaces.CategorySnapshot); ok {
		r0 = returnFunc(ctx, categoryID, subcategoryID)
	} else {
		r0 = ret.Get(0).(interfaces.CategorySnapshot)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, *uuid.UUID) error); ok {
		r1 = returnFunc(ctx, categoryID, subcategoryID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CategoryValidator_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type CategoryValidator_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - ctx context.Context
//   - categoryID uuid.UUID
//   - subcategoryID *uuid.UUID
func (_e *CategoryValidator_Expecter) Validate(ctx any, categoryID any, subcategoryID any) *CategoryValidator_Validate_Call {
	return &CategoryValidator_Validate_Call{Call: _e.mock.On("Validate", ctx, categoryID, subcategoryID)}
}

func (_c *CategoryValidator_Validate_Call) Run(run func(ctx context.Context, categoryID uuid.UUID, subcategoryID *uuid.UUID)) *CategoryValidator_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(*uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CategoryValidator_Validate_Call) Return(categorySnapshot interfaces.CategorySnapshot, err error) *CategoryValidator_Validate_Call {
	_c.Call.Return(categorySnapshot, err)
	return _c
}

func (_c *CategoryValidator_Validate_Call) RunAndReturn(run func(ctx context.Context, categoryID uuid.UUID, subcategoryID *uuid.UUID) (interfaces.CategorySnapshot, error)) *CategoryValidator_Validate_Call {
	_c.Call.Return(run)
	return _c
}
