// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/JailtonJunior94/devkit-go/pkg/database"
	"github.com/LimaTeixeiraTecnologia/mecontrola/internal/transactions/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewRecurringTemplateEventPublisher creates a new instance of RecurringTemplateEventPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRecurringTemplateEventPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *RecurringTemplateEventPublisher {
	mock := &RecurringTemplateEventPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RecurringTemplateEventPublisher is an autogenerated mock type for the RecurringTemplateEventPublisher type
type RecurringTemplateEventPublisher struct {
	mock.Mock
}

type RecurringTemplateEventPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *RecurringTemplateEventPublisher) EXPECT() *RecurringTemplateEventPublisher_Expecter {
	return &RecurringTemplateEventPublisher_Expecter{mock: &_m.Mock}
}

// PublishCreated provides a mock function for the type RecurringTemplateEventPublisher
func (_mock *RecurringTemplateEventPublisher) PublishCreated(ctx context.Context, db database.DBTX, evt entities.RecurringTemplateCreated) error {
	ret := _mock.Called(ctx, db, evt)

	if len(ret) == 0 {
		panic("no return value specified for PublishCreated")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, database.DBTX, entities.RecurringTemplateCreated) error); ok {
		r0 = returnFunc(ctx, db, evt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RecurringTemplateEventPublisher_PublishCreated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishCreated'
type RecurringTemplateEventPublisher_PublishCreated_Call struct {
	*mock.Call
}

// PublishCreated is a helper method to define mock.On call
//   - ctx context.Context
//   - db database.DBTX
//   - evt entities.RecurringTemplateCreated
func (_e *RecurringTemplateEventPublisher_Expecter) PublishCreated(ctx any, db any, evt any) *RecurringTemplateEventPublisher_PublishCreated_Call {
	return &RecurringTemplateEventPublisher_PublishCreated_Call{Call: _e.mock.On("PublishCreated", ctx, db, evt)}
}

func (_c *RecurringTemplateEventPublisher_PublishCreated_Call) Run(run func(ctx context.Context, db database.DBTX, evt entities.RecurringTemplateCreated)) *RecurringTemplateEventPublisher_PublishCreated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 database.DBTX
		if args[1] != nil {
			arg1 = args[1].(database.DBTX)
		}
		var arg2 entities.RecurringTemplateCreated
		if args[2] != nil {
			arg2 = args[2].(entities.RecurringTemplateCreated)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RecurringTemplateEventPublisher_PublishCreated_Call) Return(err error) *RecurringTemplateEventPublisher_PublishCreated_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RecurringTemplateEventPublisher_PublishCreated_Call) RunAndReturn(run func(ctx context.Context, db database.DBTX, evt entities.RecurringTemplateCreated) error) *RecurringTemplateEventPublisher_PublishCreated_Call {
	_c.Call.Return(run)
	return _c
}

// PublishDeleted provides a mock function for the type RecurringTemplateEventPublisher
func (_mock *RecurringTemplateEventPublisher) PublishDeleted(ctx context.Context, db database.DBTX, evt entities.RecurringTemplateDeleted) error {
	ret := _mock.Called(ctx, db, evt)

	if len(ret) == 0 {
		panic("no return value specified for PublishDeleted")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, database.DBTX, entities.RecurringTemplateDeleted) error); ok {
		r0 = returnFunc(ctx, db, evt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RecurringTemplateEventPublisher_PublishDeleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishDeleted'
type RecurringTemplateEventPublisher_PublishDeleted_Call struct {
	*mock.Call
}

// PublishDeleted is a helper method to define mock.On call
//   - ctx context.Context
//   - db database.DBTX
//   - evt entities.RecurringTemplateDeleted
func (_e *RecurringTemplateEventPublisher_Expecter) PublishDeleted(ctx any, db any, evt any) *RecurringTemplateEventPublisher_PublishDeleted_Call {
	return &RecurringTemplateEventPublisher_PublishDeleted_Call{Call: _e.mock.On("PublishDeleted", ctx, db, evt)}
}

func (_c *RecurringTemplateEventPublisher_PublishDeleted_Call) Run(run func(ctx context.Context, db database.DBTX, evt entities.RecurringTemplateDeleted)) *RecurringTemplateEventPublisher_PublishDeleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 database.DBTX
		if args[1] != nil {
			arg1 = args[1].(database.DBTX)
		}
		var arg2 entities.RecurringTemplateDeleted
		if args[2] != nil {
			arg2 = args[2].(entities.RecurringTemplateDeleted)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RecurringTemplateEventPublisher_PublishDeleted_Call) Return(err error) *RecurringTemplateEventPublisher_PublishDeleted_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RecurringTemplateEventPublisher_PublishDeleted_Call) RunAndReturn(run func(ctx context.Context, db database.DBTX, evt entities.RecurringTemplateDeleted) error) *RecurringTemplateEventPublisher_PublishDeleted_Call {
	_c.Call.Return(run)
	return _c
}

// PublishUpdated provides a mock function for the type RecurringTemplateEventPublisher
func (_mock *RecurringTemplateEventPublisher) PublishUpdated(ctx context.Context, db database.DBTX, evt entities.RecurringTemplateUpdated) error {
	ret := _mock.Called(ctx, db, evt)

	if len(ret) == 0 {
		panic("no return value specified for PublishUpdated")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, database.DBTX, entities.RecurringTemplateUpdated) error); ok {
		r0 = returnFunc(ctx, db, evt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RecurringTemplateEventPublisher_PublishUpdated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishUpdated'
type RecurringTemplateEventPublisher_PublishUpdated_Call struct {
	*mock.Call
}

// PublishUpdated is a helper method to define mock.On call
//   - ctx context.Context
//   - db database.DBTX
//   - evt entities.RecurringTemplateUpdated
func (_e *RecurringTemplateEventPublisher_Expecter) PublishUpdated(ctx any, db any, evt any) *RecurringTemplateEventPublisher_PublishUpdated_Call {
	return &RecurringTemplateEventPublisher_PublishUpdated_Call{Call: _e.mock.On("PublishUpdated", ctx, db, evt)}
}

func (_c *RecurringTemplateEventPublisher_PublishUpdated_Call) Run(run func(ctx context.Context, db database.DBTX, evt entities.RecurringTemplateUpdated)) *RecurringTemplateEventPublisher_PublishUpdated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 database.DBTX
		if args[1] != nil {
			arg1 = args[1].(database.DBTX)
		}
		var arg2 entities.RecurringTemplateUpdated
		if args[2] != nil {
			arg2 = args[2].(entities.RecurringTemplateUpdated)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RecurringTemplateEventPublisher_PublishUpdated_Call) Return(err error) *RecurringTemplateEventPublisher_PublishUpdated_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RecurringTemplateEventPublisher_PublishUpdated_Call) RunAndReturn(run func(ctx context.Context, db database.DBTX, evt entities.RecurringTemplateUpdated) error) *RecurringTemplateEventPublisher_PublishUpdated_Call {
	_c.Call.Return(run)
	return _c
}
