// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/JailtonJunior94/devkit-go/pkg/database"
	"github.com/LimaTeixeiraTecnologia/mecontrola/internal/transactions/application/interfaces"
	mock "github.com/stretchr/testify/mock"
)

// NewRepositoryFactory creates a new instance of RepositoryFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepositoryFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepositoryFactory {
	mock := &RepositoryFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RepositoryFactory is an autogenerated mock type for the RepositoryFactory type
type RepositoryFactory struct {
	mock.Mock
}

type RepositoryFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *RepositoryFactory) EXPECT() *RepositoryFactory_Expecter {
	return &RepositoryFactory_Expecter{mock: &_m.Mock}
}

// CardInvoiceRepository provides a mock function for the type RepositoryFactory
func (_mock *RepositoryFactory) CardInvoiceRepository(db database.DBTX) interfaces.CardInvoiceRepository {
	ret := _mock.Called(db)

	if len(ret) == 0 {
		panic("no return value specified for CardInvoiceRepository")
	}

	var r0 interfaces.CardInvoiceRepository
	if returnFunc, ok := ret.Get(0).(func(database.DBTX) interfaces.CardInvoiceRepository); ok {
		r0 = returnFunc(db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.CardInvoiceRepository)
		}
	}
	return r0
}

// RepositoryFactory_CardInvoiceRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CardInvoiceRepository'
type RepositoryFactory_CardInvoiceRepository_Call struct {
	*mock.Call
}

// CardInvoiceRepository is a helper method to define mock.On call
//   - db database.DBTX
func (_e *RepositoryFactory_Expecter) CardInvoiceRepository(db any) *RepositoryFactory_CardInvoiceRepository_Call {
	return &RepositoryFactory_CardInvoiceRepository_Call{Call: _e.mock.On("CardInvoiceRepository", db)}
}

func (_c *RepositoryFactory_CardInvoiceRepository_Call) Run(run func(db database.DBTX)) *RepositoryFactory_CardInvoiceRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 database.DBTX
		if args[0] != nil {
			arg0 = args[0].(database.DBTX)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RepositoryFactory_CardInvoiceRepository_Call) Return(cardInvoiceRepository interfaces.CardInvoiceRepository) *RepositoryFactory_CardInvoiceRepository_Call {
	_c.Call.Return(cardInvoiceRepository)
	return _c
}

func (_c *RepositoryFactory_CardInvoiceRepository_Call) RunAndReturn(run func(db database.DBTX) interfaces.CardInvoiceRepository) *RepositoryFactory_CardInvoiceRepository_Call {
	_c.Call.Return(run)
	return _c
}

// CardPurchaseRepository provides a mock function for the type RepositoryFactory
func (_mock *RepositoryFactory) CardPurchaseRepository(db database.DBTX) interfaces.CardPurchaseRepository {
	ret := _mock.Called(db)

	if len(ret) == 0 {
		panic("no return value specified for CardPurchaseRepository")
	}

	var r0 interfaces.CardPurchaseRepository
	if returnFunc, ok := ret.Get(0).(func(database.DBTX) interfaces.CardPurchaseRepository); ok {
		r0 = returnFunc(db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.CardPurchaseRepository)
		}
	}
	return r0
}

// RepositoryFactory_CardPurchaseRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CardPurchaseRepository'
type RepositoryFactory_CardPurchaseRepository_Call struct {
	*mock.Call
}

// CardPurchaseRepository is a helper method to define mock.On call
//   - db database.DBTX
func (_e *RepositoryFactory_Expecter) CardPurchaseRepository(db any) *RepositoryFactory_CardPurchaseRepository_Call {
	return &RepositoryFactory_CardPurchaseRepository_Call{Call: _e.mock.On("CardPurchaseRepository", db)}
}

func (_c *RepositoryFactory_CardPurchaseRepository_Call) Run(run func(db database.DBTX)) *RepositoryFactory_CardPurchaseRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 database.DBTX
		if args[0] != nil {
			arg0 = args[0].(database.DBTX)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RepositoryFactory_CardPurchaseRepository_Call) Return(cardPurchaseRepository interfaces.CardPurchaseRepository) *RepositoryFactory_CardPurchaseRepository_Call {
	_c.Call.Return(cardPurchaseRepository)
	return _c
}

func (_c *RepositoryFactory_CardPurchaseRepository_Call) RunAndReturn(run func(db database.DBTX) interfaces.CardPurchaseRepository) *RepositoryFactory_CardPurchaseRepository_Call {
	_c.Call.Return(run)
	return _c
}

// MonthlySummaryRepository provides a mock function for the type RepositoryFactory
func (_mock *RepositoryFactory) MonthlySummaryRepository(db database.DBTX) interfaces.MonthlySummaryRepository {
	ret := _mock.Called(db)

	if len(ret) == 0 {
		panic("no return value specified for MonthlySummaryRepository")
	}

	var r0 interfaces.MonthlySummaryRepository
	if returnFunc, ok := ret.Get(0).(func(database.DBTX) interfaces.MonthlySummaryRepository); ok {
		r0 = returnFunc(db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.MonthlySummaryRepository)
		}
	}
	return r0
}

// RepositoryFactory_MonthlySummaryRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MonthlySummaryRepository'
type RepositoryFactory_MonthlySummaryRepository_Call struct {
	*mock.Call
}

// MonthlySummaryRepository is a helper method to define mock.On call
//   - db database.DBTX
func (_e *RepositoryFactory_Expecter) MonthlySummaryRepository(db any) *RepositoryFactory_MonthlySummaryRepository_Call {
	return &RepositoryFactory_MonthlySummaryRepository_Call{Call: _e.mock.On("MonthlySummaryRepository", db)}
}

func (_c *RepositoryFactory_MonthlySummaryRepository_Call) Run(run func(db database.DBTX)) *RepositoryFactory_MonthlySummaryRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 database.DBTX
		if args[0] != nil {
			arg0 = args[0].(database.DBTX)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RepositoryFactory_MonthlySummaryRepository_Call) Return(monthlySummaryRepository interfaces.MonthlySummaryRepository) *RepositoryFactory_MonthlySummaryRepository_Call {
	_c.Call.Return(monthlySummaryRepository)
	return _c
}

func (_c *RepositoryFactory_MonthlySummaryRepository_Call) RunAndReturn(run func(db database.DBTX) interfaces.MonthlySummaryRepository) *RepositoryFactory_MonthlySummaryRepository_Call {
	_c.Call.Return(run)
	return _c
}

// RecurringMaterializationRepository provides a mock function for the type RepositoryFactory
func (_mock *RepositoryFactory) RecurringMaterializationRepository(db database.DBTX) interfaces.RecurringMaterializationRepository {
	ret := _mock.Called(db)

	if len(ret) == 0 {
		panic("no return value specified for RecurringMaterializationRepository")
	}

	var r0 interfaces.RecurringMaterializationRepository
	if returnFunc, ok := ret.Get(0).(func(database.DBTX) interfaces.RecurringMaterializationRepository); ok {
		r0 = returnFunc(db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.RecurringMaterializationRepository)
		}
	}
	return r0
}

// RepositoryFactory_RecurringMaterializationRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecurringMaterializationRepository'
type RepositoryFactory_RecurringMaterializationRepository_Call struct {
	*mock.Call
}

// RecurringMaterializationRepository is a helper method to define mock.On call
//   - db database.DBTX
func (_e *RepositoryFactory_Expecter) RecurringMaterializationRepository(db any) *RepositoryFactory_RecurringMaterializationRepository_Call {
	return &RepositoryFactory_RecurringMaterializationRepository_Call{Call: _e.mock.On("RecurringMaterializationRepository", db)}
}

func (_c *RepositoryFactory_RecurringMaterializationRepository_Call) Run(run func(db database.DBTX)) *RepositoryFactory_RecurringMaterializationRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 database.DBTX
		if args[0] != nil {
			arg0 = args[0].(database.DBTX)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RepositoryFactory_RecurringMaterializationRepository_Call) Return(recurringMaterializationRepository interfaces.RecurringMaterializationRepository) *RepositoryFactory_RecurringMaterializationRepository_Call {
	_c.Call.Return(recurringMaterializationRepository)
	return _c
}

func (_c *RepositoryFactory_RecurringMaterializationRepository_Call) RunAndReturn(run func(db database.DBTX) interfaces.RecurringMaterializationRepository) *RepositoryFactory_RecurringMaterializationRepository_Call {
	_c.Call.Return(run)
	return _c
}

// RecurringTemplateRepository provides a mock function for the type RepositoryFactory
func (_mock *RepositoryFactory) RecurringTemplateRepository(db database.DBTX) interfaces.RecurringTemplateRepository {
	ret := _mock.Called(db)

	if len(ret) == 0 {
		panic("no return value specified for RecurringTemplateRepository")
	}

	var r0 interfaces.RecurringTemplateRepository
	if returnFunc, ok := ret.Get(0).(func(database.DBTX) interfaces.RecurringTemplateRepository); ok {
		r0 = returnFunc(db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.RecurringTemplateRepository)
		}
	}
	return r0
}

// RepositoryFactory_RecurringTemplateRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecurringTemplateRepository'
type RepositoryFactory_RecurringTemplateRepository_Call struct {
	*mock.Call
}

// RecurringTemplateRepository is a helper method to define mock.On call
//   - db database.DBTX
func (_e *RepositoryFactory_Expecter) RecurringTemplateRepository(db any) *RepositoryFactory_RecurringTemplateRepository_Call {
	return &RepositoryFactory_RecurringTemplateRepository_Call{Call: _e.mock.On("RecurringTemplateRepository", db)}
}

func (_c *RepositoryFactory_RecurringTemplateRepository_Call) Run(run func(db database.DBTX)) *RepositoryFactory_RecurringTemplateRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 database.DBTX
		if args[0] != nil {
			arg0 = args[0].(database.DBTX)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RepositoryFactory_RecurringTemplateRepository_Call) Return(recurringTemplateRepository interfaces.RecurringTemplateRepository) *RepositoryFactory_RecurringTemplateRepository_Call {
	_c.Call.Return(recurringTemplateRepository)
	return _c
}

func (_c *RepositoryFactory_RecurringTemplateRepository_Call) RunAndReturn(run func(db database.DBTX) interfaces.RecurringTemplateRepository) *RepositoryFactory_RecurringTemplateRepository_Call {
	_c.Call.Return(run)
	return _c
}

// TransactionRepository provides a mock function for the type RepositoryFactory
func (_mock *RepositoryFactory) TransactionRepository(db database.DBTX) interfaces.TransactionRepository {
	ret := _mock.Called(db)

	if len(ret) == 0 {
		panic("no return value specified for TransactionRepository")
	}

	var r0 interfaces.TransactionRepository
	if returnFunc, ok := ret.Get(0).(func(database.DBTX) interfaces.TransactionRepository); ok {
		r0 = returnFunc(db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.TransactionRepository)
		}
	}
	return r0
}

// RepositoryFactory_TransactionRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransactionRepository'
type RepositoryFactory_TransactionRepository_Call struct {
	*mock.Call
}

// TransactionRepository is a helper method to define mock.On call
//   - db database.DBTX
func (_e *RepositoryFactory_Expecter) TransactionRepository(db any) *RepositoryFactory_TransactionRepository_Call {
	return &RepositoryFactory_TransactionRepository_Call{Call: _e.mock.On("TransactionRepository", db)}
}

func (_c *RepositoryFactory_TransactionRepository_Call) Run(run func(db database.DBTX)) *RepositoryFactory_TransactionRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 database.DBTX
		if args[0] != nil {
			arg0 = args[0].(database.DBTX)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RepositoryFactory_TransactionRepository_Call) Return(transactionRepository interfaces.TransactionRepository) *RepositoryFactory_TransactionRepository_Call {
	_c.Call.Return(transactionRepository)
	return _c
}

func (_c *RepositoryFactory_TransactionRepository_Call) RunAndReturn(run func(db database.DBTX) interfaces.TransactionRepository) *RepositoryFactory_TransactionRepository_Call {
	_c.Call.Return(run)
	return _c
}
