// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/LimaTeixeiraTecnologia/mecontrola/internal/transactions/application/interfaces"
	"github.com/LimaTeixeiraTecnologia/mecontrola/internal/transactions/domain/entities"
	"github.com/LimaTeixeiraTecnologia/mecontrola/internal/transactions/domain/valueobjects"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewTransactionRepository creates a new instance of TransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionRepository {
	mock := &TransactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TransactionRepository is an autogenerated mock type for the TransactionRepository type
type TransactionRepository struct {
	mock.Mock
}

type TransactionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TransactionRepository) EXPECT() *TransactionRepository_Expecter {
	return &TransactionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type TransactionRepository
func (_mock *TransactionRepository) Create(ctx context.Context, tx *entities.Transaction) error {
	ret := _mock.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Transaction) error); ok {
		r0 = returnFunc(ctx, tx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TransactionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TransactionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *entities.Transaction
func (_e *TransactionRepository_Expecter) Create(ctx interface{}, tx interface{}) *TransactionRepository_Create_Call {
	return &TransactionRepository_Create_Call{Call: _e.mock.On("Create", ctx, tx)}
}

func (_c *TransactionRepository_Create_Call) Run(run func(ctx context.Context, tx *entities.Transaction)) *TransactionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Transaction
		if args[1] != nil {
			arg1 = args[1].(*entities.Transaction)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TransactionRepository_Create_Call) Return(err error) *TransactionRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TransactionRepository_Create_Call) RunAndReturn(run func(ctx context.Context, tx *entities.Transaction) error) *TransactionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type TransactionRepository
func (_mock *TransactionRepository) GetByID(ctx context.Context, id uuid.UUID, userID uuid.UUID) (*entities.Transaction, error) {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entities.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*entities.Transaction, error)); ok {
		return returnFunc(ctx, id, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *entities.Transaction); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TransactionRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type TransactionRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *TransactionRepository_Expecter) GetByID(ctx interface{}, id interface{}, userID interface{}) *TransactionRepository_GetByID_Call {
	return &TransactionRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id, userID)}
}

func (_c *TransactionRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *TransactionRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TransactionRepository_GetByID_Call) Return(transaction *entities.Transaction, err error) *TransactionRepository_GetByID_Call {
	_c.Call.Return(transaction, err)
	return _c
}

func (_c *TransactionRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID) (*entities.Transaction, error)) *TransactionRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByMonth provides a mock function for the type TransactionRepository
func (_mock *TransactionRepository) ListByMonth(ctx context.Context, userID uuid.UUID, refMonth valueobjects.RefMonth, cursor interfaces.Cursor, limit int) ([]*entities.Transaction, interfaces.Cursor, error) {
	ret := _mock.Called(ctx, userID, refMonth, cursor, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListByMonth")
	}

	var r0 []*entities.Transaction
	var r1 interfaces.Cursor
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, valueobjects.RefMonth, interfaces.Cursor, int) ([]*entities.Transaction, interfaces.Cursor, error)); ok {
		return returnFunc(ctx, userID, refMonth, cursor, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, valueobjects.RefMonth, interfaces.Cursor, int) []*entities.Transaction); ok {
		r0 = returnFunc(ctx, userID, refMonth, cursor, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, valueobjects.RefMonth, interfaces.Cursor, int) interfaces.Cursor); ok {
		r1 = returnFunc(ctx, userID, refMonth, cursor, limit)
	} else {
		r1 = ret.Get(1).(interfaces.Cursor)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID, valueobjects.RefMonth, interfaces.Cursor, int) error); ok {
		r2 = returnFunc(ctx, userID, refMonth, cursor, limit)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// TransactionRepository_ListByMonth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByMonth'
type TransactionRepository_ListByMonth_Call struct {
	*mock.Call
}

// ListByMonth is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - refMonth valueobjects.RefMonth
//   - cursor interfaces.Cursor
//   - limit int
func (_e *TransactionRepository_Expecter) ListByMonth(ctx interface{}, userID interface{}, refMonth interface{}, cursor interface{}, limit interface{}) *TransactionRepository_ListByMonth_Call {
	return &TransactionRepository_ListByMonth_Call{Call: _e.mock.On("ListByMonth", ctx, userID, refMonth, cursor, limit)}
}

func (_c *TransactionRepository_ListByMonth_Call) Run(run func(ctx context.Context, userID uuid.UUID, refMonth valueobjects.RefMonth, cursor interfaces.Cursor, limit int)) *TransactionRepository_ListByMonth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 valueobjects.RefMonth
		if args[2] != nil {
			arg2 = args[2].(valueobjects.RefMonth)
		}
		var arg3 interfaces.Cursor
		if args[3] != nil {
			arg3 = args[3].(interfaces.Cursor)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *TransactionRepository_ListByMonth_Call) Return(transactions []*entities.Transaction, cursor1 interfaces.Cursor, err error) *TransactionRepository_ListByMonth_Call {
	_c.Call.Return(transactions, cursor1, err)
	return _c
}

func (_c *TransactionRepository_ListByMonth_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, refMonth valueobjects.RefMonth, cursor interfaces.Cursor, limit int) ([]*entities.Transaction, interfaces.Cursor, error)) *TransactionRepository_ListByMonth_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDelete provides a mock function for the type TransactionRepository
func (_mock *TransactionRepository) SoftDelete(ctx context.Context, id uuid.UUID, userID uuid.UUID, expectedVersion int64, now time.Time) error {
	ret := _mock.Called(ctx, id, userID, expectedVersion, now)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int64, time.Time) error); ok {
		r0 = returnFunc(ctx, id, userID, expectedVersion, now)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TransactionRepository_SoftDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDelete'
type TransactionRepository_SoftDelete_Call struct {
	*mock.Call
}

// SoftDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
//   - expectedVersion int64
//   - now time.Time
func (_e *TransactionRepository_Expecter) SoftDelete(ctx interface{}, id interface{}, userID interface{}, expectedVersion interface{}, now interface{}) *TransactionRepository_SoftDelete_Call {
	return &TransactionRepository_SoftDelete_Call{Call: _e.mock.On("SoftDelete", ctx, id, userID, expectedVersion, now)}
}

func (_c *TransactionRepository_SoftDelete_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID, expectedVersion int64, now time.Time)) *TransactionRepository_SoftDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *TransactionRepository_SoftDelete_Call) Return(err error) *TransactionRepository_SoftDelete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TransactionRepository_SoftDelete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID, expectedVersion int64, now time.Time) error) *TransactionRepository_SoftDelete_Call {
	_c.Call.Return(run)
	return _c
}

// SumByMonth provides a mock function for the type TransactionRepository
func (_mock *TransactionRepository) SumByMonth(ctx context.Context, userID uuid.UUID, refMonth valueobjects.RefMonth) (int64, int64, error) {
	ret := _mock.Called(ctx, userID, refMonth)

	if len(ret) == 0 {
		panic("no return value specified for SumByMonth")
	}

	var r0 int64
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, valueobjects.RefMonth) (int64, int64, error)); ok {
		return returnFunc(ctx, userID, refMonth)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, valueobjects.RefMonth) int64); ok {
		r0 = returnFunc(ctx, userID, refMonth)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, valueobjects.RefMonth) int64); ok {
		r1 = returnFunc(ctx, userID, refMonth)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID, valueobjects.RefMonth) error); ok {
		r2 = returnFunc(ctx, userID, refMonth)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// TransactionRepository_SumByMonth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SumByMonth'
type TransactionRepository_SumByMonth_Call struct {
	*mock.Call
}

// SumByMonth is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - refMonth valueobjects.RefMonth
func (_e *TransactionRepository_Expecter) SumByMonth(ctx interface{}, userID interface{}, refMonth interface{}) *TransactionRepository_SumByMonth_Call {
	return &TransactionRepository_SumByMonth_Call{Call: _e.mock.On("SumByMonth", ctx, userID, refMonth)}
}

func (_c *TransactionRepository_SumByMonth_Call) Run(run func(ctx context.Context, userID uuid.UUID, refMonth valueobjects.RefMonth)) *TransactionRepository_SumByMonth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 valueobjects.RefMonth
		if args[2] != nil {
			arg2 = args[2].(valueobjects.RefMonth)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TransactionRepository_SumByMonth_Call) Return(incomeCents int64, outcomeCents int64, err error) *TransactionRepository_SumByMonth_Call {
	_c.Call.Return(incomeCents, outcomeCents, err)
	return _c
}

func (_c *TransactionRepository_SumByMonth_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, refMonth valueobjects.RefMonth) (int64, int64, error)) *TransactionRepository_SumByMonth_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWithVersion provides a mock function for the type TransactionRepository
func (_mock *TransactionRepository) UpdateWithVersion(ctx context.Context, tx *entities.Transaction, expectedVersion int64) error {
	ret := _mock.Called(ctx, tx, expectedVersion)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWithVersion")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Transaction, int64) error); ok {
		r0 = returnFunc(ctx, tx, expectedVersion)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TransactionRepository_UpdateWithVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWithVersion'
type TransactionRepository_UpdateWithVersion_Call struct {
	*mock.Call
}

// UpdateWithVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *entities.Transaction
//   - expectedVersion int64
func (_e *TransactionRepository_Expecter) UpdateWithVersion(ctx interface{}, tx interface{}, expectedVersion interface{}) *TransactionRepository_UpdateWithVersion_Call {
	return &TransactionRepository_UpdateWithVersion_Call{Call: _e.mock.On("UpdateWithVersion", ctx, tx, expectedVersion)}
}

func (_c *TransactionRepository_UpdateWithVersion_Call) Run(run func(ctx context.Context, tx *entities.Transaction, expectedVersion int64)) *TransactionRepository_UpdateWithVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Transaction
		if args[1] != nil {
			arg1 = args[1].(*entities.Transaction)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TransactionRepository_UpdateWithVersion_Call) Return(err error) *TransactionRepository_UpdateWithVersion_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TransactionRepository_UpdateWithVersion_Call) RunAndReturn(run func(ctx context.Context, tx *entities.Transaction, expectedVersion int64) error) *TransactionRepository_UpdateWithVersion_Call {
	_c.Call.Return(run)
	return _c
}
