// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewVersionReader creates a new instance of VersionReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVersionReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *VersionReader {
	mock := &VersionReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// VersionReader is an autogenerated mock type for the VersionReader type
type VersionReader struct {
	mock.Mock
}

type VersionReader_Expecter struct {
	mock *mock.Mock
}

func (_m *VersionReader) EXPECT() *VersionReader_Expecter {
	return &VersionReader_Expecter{mock: &_m.Mock}
}

// Current provides a mock function for the type VersionReader
func (_mock *VersionReader) Current(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Current")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// VersionReader_Current_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Current'
type VersionReader_Current_Call struct {
	*mock.Call
}

// Current is a helper method to define mock.On call
//   - ctx context.Context
func (_e *VersionReader_Expecter) Current(ctx interface{}) *VersionReader_Current_Call {
	return &VersionReader_Current_Call{Call: _e.mock.On("Current", ctx)}
}

func (_c *VersionReader_Current_Call) Run(run func(ctx context.Context)) *VersionReader_Current_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *VersionReader_Current_Call) Return(n int64, err error) *VersionReader_Current_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *VersionReader_Current_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *VersionReader_Current_Call {
	_c.Call.Return(run)
	return _c
}
