// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/LimaTeixeiraTecnologia/mecontrola/internal/identity/application/dtos/input"
	mock "github.com/stretchr/testify/mock"
)

// newGatewayAuthFailureLogger creates a new instance of gatewayAuthFailureLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newGatewayAuthFailureLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *gatewayAuthFailureLogger {
	mock := &gatewayAuthFailureLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// gatewayAuthFailureLogger is an autogenerated mock type for the gatewayAuthFailureLogger type
type gatewayAuthFailureLogger struct {
	mock.Mock
}

type gatewayAuthFailureLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *gatewayAuthFailureLogger) EXPECT() *gatewayAuthFailureLogger_Expecter {
	return &gatewayAuthFailureLogger_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function for the type gatewayAuthFailureLogger
func (_mock *gatewayAuthFailureLogger) Handle(ctx context.Context, in input.RecordGatewayAuthFailureInput) error {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, input.RecordGatewayAuthFailureInput) error); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// gatewayAuthFailureLogger_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type gatewayAuthFailureLogger_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - in input.RecordGatewayAuthFailureInput
func (_e *gatewayAuthFailureLogger_Expecter) Handle(ctx interface{}, in interface{}) *gatewayAuthFailureLogger_Handle_Call {
	return &gatewayAuthFailureLogger_Handle_Call{Call: _e.mock.On("Handle", ctx, in)}
}

func (_c *gatewayAuthFailureLogger_Handle_Call) Run(run func(ctx context.Context, in input.RecordGatewayAuthFailureInput)) *gatewayAuthFailureLogger_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 input.RecordGatewayAuthFailureInput
		if args[1] != nil {
			arg1 = args[1].(input.RecordGatewayAuthFailureInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *gatewayAuthFailureLogger_Handle_Call) Return(err error) *gatewayAuthFailureLogger_Handle_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *gatewayAuthFailureLogger_Handle_Call) RunAndReturn(run func(ctx context.Context, in input.RecordGatewayAuthFailureInput) error) *gatewayAuthFailureLogger_Handle_Call {
	_c.Call.Return(run)
	return _c
}
