// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/LimaTeixeiraTecnologia/mecontrola/internal/platform/agent"
)

func NewAgentRuntime(t interface {
	mock.TestingT
	Cleanup(func())
}) *AgentRuntime {
	m := &AgentRuntime{}
	m.Mock.Test(t)
	t.Cleanup(func() { m.AssertExpectations(t) })
	return m
}

type AgentRuntime struct {
	mock.Mock
}

type AgentRuntime_Expecter struct {
	mock *mock.Mock
}

func (_m *AgentRuntime) EXPECT() *AgentRuntime_Expecter {
	return &AgentRuntime_Expecter{mock: &_m.Mock}
}

func (_mock *AgentRuntime) Execute(ctx context.Context, in agent.InboundRequest) (agent.Outcome, error) {
	ret := _mock.Called(ctx, in)
	var r0 agent.Outcome
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, agent.InboundRequest) (agent.Outcome, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, agent.InboundRequest) agent.Outcome); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(agent.Outcome)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, agent.InboundRequest) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type AgentRuntime_Execute_Call struct {
	*mock.Call
}

func (_e *AgentRuntime_Expecter) Execute(ctx any, in any) *AgentRuntime_Execute_Call {
	return &AgentRuntime_Execute_Call{Call: _e.mock.On("Execute", ctx, in)}
}

func (_c *AgentRuntime_Execute_Call) Return(outcome agent.Outcome, err error) *AgentRuntime_Execute_Call {
	_c.Call.Return(outcome, err)
	return _c
}

func (_c *AgentRuntime_Execute_Call) RunAndReturn(run func(context.Context, agent.InboundRequest) (agent.Outcome, error)) *AgentRuntime_Execute_Call {
	_c.Call.Return(run)
	return _c
}
