// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/LimaTeixeiraTecnologia/mecontrola/internal/platform/agent"
)

func NewHooks(t interface {
	mock.TestingT
	Cleanup(func())
}) *Hooks {
	m := &Hooks{}
	m.Mock.Test(t)
	t.Cleanup(func() { m.AssertExpectations(t) })
	return m
}

type Hooks struct {
	mock.Mock
}

type Hooks_Expecter struct {
	mock *mock.Mock
}

func (_m *Hooks) EXPECT() *Hooks_Expecter {
	return &Hooks_Expecter{mock: &_m.Mock}
}

func (_mock *Hooks) BeforeExecute(ctx context.Context, agentID string, in agent.Request) context.Context {
	ret := _mock.Called(ctx, agentID, in)
	var r0 context.Context
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, agent.Request) context.Context); ok {
		return returnFunc(ctx, agentID, in)
	}
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(context.Context)
	}
	return r0
}

type Hooks_BeforeExecute_Call struct {
	*mock.Call
}

func (_e *Hooks_Expecter) BeforeExecute(ctx any, agentID any, in any) *Hooks_BeforeExecute_Call {
	return &Hooks_BeforeExecute_Call{Call: _e.mock.On("BeforeExecute", ctx, agentID, in)}
}

func (_c *Hooks_BeforeExecute_Call) Return(ctx context.Context) *Hooks_BeforeExecute_Call {
	_c.Call.Return(ctx)
	return _c
}

func (_mock *Hooks) AfterExecute(ctx context.Context, agentID string, result agent.Result, err error) {
	_mock.Called(ctx, agentID, result, err)
}

type Hooks_AfterExecute_Call struct {
	*mock.Call
}

func (_e *Hooks_Expecter) AfterExecute(ctx any, agentID any, result any, err any) *Hooks_AfterExecute_Call {
	return &Hooks_AfterExecute_Call{Call: _e.mock.On("AfterExecute", ctx, agentID, result, err)}
}

func (_c *Hooks_AfterExecute_Call) Return() *Hooks_AfterExecute_Call {
	_c.Call.Return()
	return _c
}

func (_mock *Hooks) BeforeTool(ctx context.Context, agentID, toolID string) context.Context {
	ret := _mock.Called(ctx, agentID, toolID)
	var r0 context.Context
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) context.Context); ok {
		return returnFunc(ctx, agentID, toolID)
	}
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(context.Context)
	}
	return r0
}

type Hooks_BeforeTool_Call struct {
	*mock.Call
}

func (_e *Hooks_Expecter) BeforeTool(ctx any, agentID any, toolID any) *Hooks_BeforeTool_Call {
	return &Hooks_BeforeTool_Call{Call: _e.mock.On("BeforeTool", ctx, agentID, toolID)}
}

func (_c *Hooks_BeforeTool_Call) Return(ctx context.Context) *Hooks_BeforeTool_Call {
	_c.Call.Return(ctx)
	return _c
}

func (_mock *Hooks) AfterTool(ctx context.Context, agentID, toolID string, argsJSON, resultBytes []byte, err error) {
	_mock.Called(ctx, agentID, toolID, argsJSON, resultBytes, err)
}

type Hooks_AfterTool_Call struct {
	*mock.Call
}

func (_e *Hooks_Expecter) AfterTool(ctx any, agentID any, toolID any, argsJSON any, resultBytes any, err any) *Hooks_AfterTool_Call {
	return &Hooks_AfterTool_Call{Call: _e.mock.On("AfterTool", ctx, agentID, toolID, argsJSON, resultBytes, err)}
}

func (_c *Hooks_AfterTool_Call) Return() *Hooks_AfterTool_Call {
	_c.Call.Return()
	return _c
}
