// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

func NewWorkingMemory(t interface {
	mock.TestingT
	Cleanup(func())
}) *WorkingMemory {
	m := &WorkingMemory{}
	m.Mock.Test(t)
	t.Cleanup(func() { m.AssertExpectations(t) })
	return m
}

type WorkingMemory struct {
	mock.Mock
}

type WorkingMemory_Expecter struct {
	mock *mock.Mock
}

func (_m *WorkingMemory) EXPECT() *WorkingMemory_Expecter {
	return &WorkingMemory_Expecter{mock: &_m.Mock}
}

func (_mock *WorkingMemory) Get(ctx context.Context, resourceID string) (string, error) {
	ret := _mock.Called(ctx, resourceID)
	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, resourceID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, resourceID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, resourceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type WorkingMemory_Get_Call struct {
	*mock.Call
}

func (_e *WorkingMemory_Expecter) Get(ctx any, resourceID any) *WorkingMemory_Get_Call {
	return &WorkingMemory_Get_Call{Call: _e.mock.On("Get", ctx, resourceID)}
}

func (_c *WorkingMemory_Get_Call) Return(content string, err error) *WorkingMemory_Get_Call {
	_c.Call.Return(content, err)
	return _c
}

func (_mock *WorkingMemory) Upsert(ctx context.Context, resourceID, content string) error {
	ret := _mock.Called(ctx, resourceID, content)
	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		return returnFunc(ctx, resourceID, content)
	}
	r0 = ret.Error(0)
	return r0
}

type WorkingMemory_Upsert_Call struct {
	*mock.Call
}

func (_e *WorkingMemory_Expecter) Upsert(ctx any, resourceID any, content any) *WorkingMemory_Upsert_Call {
	return &WorkingMemory_Upsert_Call{Call: _e.mock.On("Upsert", ctx, resourceID, content)}
}

func (_c *WorkingMemory_Upsert_Call) Return(err error) *WorkingMemory_Upsert_Call {
	_c.Call.Return(err)
	return _c
}
