// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/LimaTeixeiraTecnologia/mecontrola/internal/platform/scorer"
)

func NewScorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Scorer {
	m := &Scorer{}
	m.Mock.Test(t)
	t.Cleanup(func() { m.AssertExpectations(t) })
	return m
}

type Scorer struct {
	mock.Mock
}

type Scorer_Expecter struct {
	mock *mock.Mock
}

func (_m *Scorer) EXPECT() *Scorer_Expecter {
	return &Scorer_Expecter{mock: &_m.Mock}
}

func (_mock *Scorer) ID() string {
	ret := _mock.Called()
	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		return returnFunc()
	}
	r0 = ret.Get(0).(string)
	return r0
}

type Scorer_ID_Call struct {
	*mock.Call
}

func (_e *Scorer_Expecter) ID() *Scorer_ID_Call {
	return &Scorer_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *Scorer_ID_Call) Return(id string) *Scorer_ID_Call {
	_c.Call.Return(id)
	return _c
}

func (_mock *Scorer) Kind() scorer.ScorerKind {
	ret := _mock.Called()
	var r0 scorer.ScorerKind
	if returnFunc, ok := ret.Get(0).(func() scorer.ScorerKind); ok {
		return returnFunc()
	}
	r0 = ret.Get(0).(scorer.ScorerKind)
	return r0
}

type Scorer_Kind_Call struct {
	*mock.Call
}

func (_e *Scorer_Expecter) Kind() *Scorer_Kind_Call {
	return &Scorer_Kind_Call{Call: _e.mock.On("Kind")}
}

func (_c *Scorer_Kind_Call) Return(kind scorer.ScorerKind) *Scorer_Kind_Call {
	_c.Call.Return(kind)
	return _c
}

func (_mock *Scorer) Score(ctx context.Context, s scorer.RunSample) (scorer.ScoreResult, error) {
	ret := _mock.Called(ctx, s)
	var r0 scorer.ScoreResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, scorer.RunSample) scorer.ScoreResult); ok {
		r0 = returnFunc(ctx, s)
	} else {
		r0 = ret.Get(0).(scorer.ScoreResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, scorer.RunSample) error); ok {
		r1 = returnFunc(ctx, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type Scorer_Score_Call struct {
	*mock.Call
}

func (_e *Scorer_Expecter) Score(ctx, s interface{}) *Scorer_Score_Call {
	return &Scorer_Score_Call{Call: _e.mock.On("Score", ctx, s)}
}

func (_c *Scorer_Score_Call) Return(result scorer.ScoreResult, err error) *Scorer_Score_Call {
	_c.Call.Return(result, err)
	return _c
}
