// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/LimaTeixeiraTecnologia/mecontrola/internal/agent/application/tools"
	mock "github.com/stretchr/testify/mock"
)

// NewCategoryClassifier creates a new instance of CategoryClassifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCategoryClassifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *CategoryClassifier {
	mock := &CategoryClassifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CategoryClassifier is an autogenerated mock type for the CategoryClassifier type
type CategoryClassifier struct {
	mock.Mock
}

type CategoryClassifier_Expecter struct {
	mock *mock.Mock
}

func (_m *CategoryClassifier) EXPECT() *CategoryClassifier_Expecter {
	return &CategoryClassifier_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type CategoryClassifier
func (_mock *CategoryClassifier) Execute(ctx context.Context, in tools.CategoryClassifyInput) (tools.CategoryClassifyResult, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 tools.CategoryClassifyResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, tools.CategoryClassifyInput) (tools.CategoryClassifyResult, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, tools.CategoryClassifyInput) tools.CategoryClassifyResult); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(tools.CategoryClassifyResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, tools.CategoryClassifyInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CategoryClassifier_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type CategoryClassifier_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - in tools.CategoryClassifyInput
func (_e *CategoryClassifier_Expecter) Execute(ctx any, in any) *CategoryClassifier_Execute_Call {
	return &CategoryClassifier_Execute_Call{Call: _e.mock.On("Execute", ctx, in)}
}

func (_c *CategoryClassifier_Execute_Call) Run(run func(ctx context.Context, in tools.CategoryClassifyInput)) *CategoryClassifier_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 tools.CategoryClassifyInput
		if args[1] != nil {
			arg1 = args[1].(tools.CategoryClassifyInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CategoryClassifier_Execute_Call) Return(categoryClassifyResult tools.CategoryClassifyResult, err error) *CategoryClassifier_Execute_Call {
	_c.Call.Return(categoryClassifyResult, err)
	return _c
}

func (_c *CategoryClassifier_Execute_Call) RunAndReturn(run func(ctx context.Context, in tools.CategoryClassifyInput) (tools.CategoryClassifyResult, error)) *CategoryClassifier_Execute_Call {
	_c.Call.Return(run)
	return _c
}
