// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/JailtonJunior94/devkit-go/pkg/database"
	"github.com/LimaTeixeiraTecnologia/mecontrola/internal/card/application/interfaces"
	mock "github.com/stretchr/testify/mock"
)

// NewRepositoryFactory creates a new instance of RepositoryFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepositoryFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepositoryFactory {
	mock := &RepositoryFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RepositoryFactory is an autogenerated mock type for the RepositoryFactory type
type RepositoryFactory struct {
	mock.Mock
}

type RepositoryFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *RepositoryFactory) EXPECT() *RepositoryFactory_Expecter {
	return &RepositoryFactory_Expecter{mock: &_m.Mock}
}

// CardRepository provides a mock function for the type RepositoryFactory
func (_mock *RepositoryFactory) CardRepository(db database.DBTX) interfaces.CardRepository {
	ret := _mock.Called(db)

	if len(ret) == 0 {
		panic("no return value specified for CardRepository")
	}

	var r0 interfaces.CardRepository
	if returnFunc, ok := ret.Get(0).(func(database.DBTX) interfaces.CardRepository); ok {
		r0 = returnFunc(db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.CardRepository)
		}
	}
	return r0
}

// RepositoryFactory_CardRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CardRepository'
type RepositoryFactory_CardRepository_Call struct {
	*mock.Call
}

// CardRepository is a helper method to define mock.On call
//   - db database.DBTX
func (_e *RepositoryFactory_Expecter) CardRepository(db interface{}) *RepositoryFactory_CardRepository_Call {
	return &RepositoryFactory_CardRepository_Call{Call: _e.mock.On("CardRepository", db)}
}

func (_c *RepositoryFactory_CardRepository_Call) Run(run func(db database.DBTX)) *RepositoryFactory_CardRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 database.DBTX
		if args[0] != nil {
			arg0 = args[0].(database.DBTX)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RepositoryFactory_CardRepository_Call) Return(cardRepository interfaces.CardRepository) *RepositoryFactory_CardRepository_Call {
	_c.Call.Return(cardRepository)
	return _c
}

func (_c *RepositoryFactory_CardRepository_Call) RunAndReturn(run func(db database.DBTX) interfaces.CardRepository) *RepositoryFactory_CardRepository_Call {
	_c.Call.Return(run)
	return _c
}
