// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/JailtonJunior94/devkit-go/pkg/database"
	"github.com/LimaTeixeiraTecnologia/mecontrola/internal/budgets/application/dtos/input"
	"github.com/LimaTeixeiraTecnologia/mecontrola/internal/budgets/domain/entities"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewAlertRepository creates a new instance of AlertRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAlertRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AlertRepository {
	mock := &AlertRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AlertRepository is an autogenerated mock type for the AlertRepository type
type AlertRepository struct {
	mock.Mock
}

type AlertRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *AlertRepository) EXPECT() *AlertRepository_Expecter {
	return &AlertRepository_Expecter{mock: &_m.Mock}
}

// CountDelivered provides a mock function for the type AlertRepository
func (_mock *AlertRepository) CountDelivered(ctx context.Context, db database.DBTX, k entities.ThresholdKey) (int64, error) {
	ret := _mock.Called(ctx, db, k)

	if len(ret) == 0 {
		panic("no return value specified for CountDelivered")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, database.DBTX, entities.ThresholdKey) (int64, error)); ok {
		return returnFunc(ctx, db, k)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, database.DBTX, entities.ThresholdKey) int64); ok {
		r0 = returnFunc(ctx, db, k)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, database.DBTX, entities.ThresholdKey) error); ok {
		r1 = returnFunc(ctx, db, k)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AlertRepository_CountDelivered_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountDelivered'
type AlertRepository_CountDelivered_Call struct {
	*mock.Call
}

// CountDelivered is a helper method to define mock.On call
//   - ctx context.Context
//   - db database.DBTX
//   - k entities.ThresholdKey
func (_e *AlertRepository_Expecter) CountDelivered(ctx interface{}, db interface{}, k interface{}) *AlertRepository_CountDelivered_Call {
	return &AlertRepository_CountDelivered_Call{Call: _e.mock.On("CountDelivered", ctx, db, k)}
}

func (_c *AlertRepository_CountDelivered_Call) Run(run func(ctx context.Context, db database.DBTX, k entities.ThresholdKey)) *AlertRepository_CountDelivered_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 database.DBTX
		if args[1] != nil {
			arg1 = args[1].(database.DBTX)
		}
		var arg2 entities.ThresholdKey
		if args[2] != nil {
			arg2 = args[2].(entities.ThresholdKey)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AlertRepository_CountDelivered_Call) Return(n int64, err error) *AlertRepository_CountDelivered_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *AlertRepository_CountDelivered_Call) RunAndReturn(run func(ctx context.Context, db database.DBTX, k entities.ThresholdKey) (int64, error)) *AlertRepository_CountDelivered_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type AlertRepository
func (_mock *AlertRepository) Insert(ctx context.Context, db database.DBTX, a entities.Alert) error {
	ret := _mock.Called(ctx, db, a)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, database.DBTX, entities.Alert) error); ok {
		r0 = returnFunc(ctx, db, a)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AlertRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type AlertRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - db database.DBTX
//   - a entities.Alert
func (_e *AlertRepository_Expecter) Insert(ctx interface{}, db interface{}, a interface{}) *AlertRepository_Insert_Call {
	return &AlertRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, db, a)}
}

func (_c *AlertRepository_Insert_Call) Run(run func(ctx context.Context, db database.DBTX, a entities.Alert)) *AlertRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 database.DBTX
		if args[1] != nil {
			arg1 = args[1].(database.DBTX)
		}
		var arg2 entities.Alert
		if args[2] != nil {
			arg2 = args[2].(entities.Alert)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AlertRepository_Insert_Call) Return(err error) *AlertRepository_Insert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AlertRepository_Insert_Call) RunAndReturn(run func(ctx context.Context, db database.DBTX, a entities.Alert) error) *AlertRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// ListForUser provides a mock function for the type AlertRepository
func (_mock *AlertRepository) ListForUser(ctx context.Context, db database.DBTX, userID uuid.UUID, q input.AlertQuery) ([]entities.Alert, string, error) {
	ret := _mock.Called(ctx, db, userID, q)

	if len(ret) == 0 {
		panic("no return value specified for ListForUser")
	}

	var r0 []entities.Alert
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, database.DBTX, uuid.UUID, input.AlertQuery) ([]entities.Alert, string, error)); ok {
		return returnFunc(ctx, db, userID, q)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, database.DBTX, uuid.UUID, input.AlertQuery) []entities.Alert); ok {
		r0 = returnFunc(ctx, db, userID, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Alert)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, database.DBTX, uuid.UUID, input.AlertQuery) string); ok {
		r1 = returnFunc(ctx, db, userID, q)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, database.DBTX, uuid.UUID, input.AlertQuery) error); ok {
		r2 = returnFunc(ctx, db, userID, q)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// AlertRepository_ListForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListForUser'
type AlertRepository_ListForUser_Call struct {
	*mock.Call
}

// ListForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - db database.DBTX
//   - userID uuid.UUID
//   - q input.AlertQuery
func (_e *AlertRepository_Expecter) ListForUser(ctx interface{}, db interface{}, userID interface{}, q interface{}) *AlertRepository_ListForUser_Call {
	return &AlertRepository_ListForUser_Call{Call: _e.mock.On("ListForUser", ctx, db, userID, q)}
}

func (_c *AlertRepository_ListForUser_Call) Run(run func(ctx context.Context, db database.DBTX, userID uuid.UUID, q input.AlertQuery)) *AlertRepository_ListForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 database.DBTX
		if args[1] != nil {
			arg1 = args[1].(database.DBTX)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 input.AlertQuery
		if args[3] != nil {
			arg3 = args[3].(input.AlertQuery)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *AlertRepository_ListForUser_Call) Return(alerts []entities.Alert, s string, err error) *AlertRepository_ListForUser_Call {
	_c.Call.Return(alerts, s, err)
	return _c
}

func (_c *AlertRepository_ListForUser_Call) RunAndReturn(run func(ctx context.Context, db database.DBTX, userID uuid.UUID, q input.AlertQuery) ([]entities.Alert, string, error)) *AlertRepository_ListForUser_Call {
	_c.Call.Return(run)
	return _c
}

// PurgeOld provides a mock function for the type AlertRepository
func (_mock *AlertRepository) PurgeOld(ctx context.Context, db database.DBTX, olderThan string, limit int) (int64, error) {
	ret := _mock.Called(ctx, db, olderThan, limit)

	if len(ret) == 0 {
		panic("no return value specified for PurgeOld")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, database.DBTX, string, int) (int64, error)); ok {
		return returnFunc(ctx, db, olderThan, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, database.DBTX, string, int) int64); ok {
		r0 = returnFunc(ctx, db, olderThan, limit)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, database.DBTX, string, int) error); ok {
		r1 = returnFunc(ctx, db, olderThan, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AlertRepository_PurgeOld_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PurgeOld'
type AlertRepository_PurgeOld_Call struct {
	*mock.Call
}

// PurgeOld is a helper method to define mock.On call
//   - ctx context.Context
//   - db database.DBTX
//   - olderThan string
//   - limit int
func (_e *AlertRepository_Expecter) PurgeOld(ctx interface{}, db interface{}, olderThan interface{}, limit interface{}) *AlertRepository_PurgeOld_Call {
	return &AlertRepository_PurgeOld_Call{Call: _e.mock.On("PurgeOld", ctx, db, olderThan, limit)}
}

func (_c *AlertRepository_PurgeOld_Call) Run(run func(ctx context.Context, db database.DBTX, olderThan string, limit int)) *AlertRepository_PurgeOld_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 database.DBTX
		if args[1] != nil {
			arg1 = args[1].(database.DBTX)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *AlertRepository_PurgeOld_Call) Return(n int64, err error) *AlertRepository_PurgeOld_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *AlertRepository_PurgeOld_Call) RunAndReturn(run func(ctx context.Context, db database.DBTX, olderThan string, limit int) (int64, error)) *AlertRepository_PurgeOld_Call {
	_c.Call.Return(run)
	return _c
}
