// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/LimaTeixeiraTecnologia/mecontrola/internal/budgets/application/interfaces"
	"github.com/LimaTeixeiraTecnologia/mecontrola/internal/budgets/domain/valueobjects"
)

// NewCardThresholdReader creates a new instance of CardThresholdReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCardThresholdReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *CardThresholdReader {
	mock := &CardThresholdReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CardThresholdReader is an autogenerated mock type for the CardThresholdReader type
type CardThresholdReader struct {
	mock.Mock
}

type CardThresholdReader_Expecter struct {
	mock *mock.Mock
}

func (_m *CardThresholdReader) EXPECT() *CardThresholdReader_Expecter {
	return &CardThresholdReader_Expecter{mock: &_m.Mock}
}

// ListActiveCardsForThresholdScan provides a mock function for the type CardThresholdReader
func (_mock *CardThresholdReader) ListActiveCardsForThresholdScan(ctx context.Context, refMonth valueobjects.Competence, limit int) ([]interfaces.ActiveCardForScan, error) {
	ret := _mock.Called(ctx, refMonth, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListActiveCardsForThresholdScan")
	}

	var r0 []interfaces.ActiveCardForScan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, valueobjects.Competence, int) ([]interfaces.ActiveCardForScan, error)); ok {
		return returnFunc(ctx, refMonth, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, valueobjects.Competence, int) []interfaces.ActiveCardForScan); ok {
		r0 = returnFunc(ctx, refMonth, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interfaces.ActiveCardForScan)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, valueobjects.Competence, int) error); ok {
		r1 = returnFunc(ctx, refMonth, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CardThresholdReader_ListActiveCardsForThresholdScan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListActiveCardsForThresholdScan'
type CardThresholdReader_ListActiveCardsForThresholdScan_Call struct {
	*mock.Call
}

// ListActiveCardsForThresholdScan is a helper method to define mock.On call
//   - ctx context.Context
//   - refMonth valueobjects.Competence
//   - limit int
func (_e *CardThresholdReader_Expecter) ListActiveCardsForThresholdScan(ctx any, refMonth any, limit any) *CardThresholdReader_ListActiveCardsForThresholdScan_Call {
	return &CardThresholdReader_ListActiveCardsForThresholdScan_Call{Call: _e.mock.On("ListActiveCardsForThresholdScan", ctx, refMonth, limit)}
}

func (_c *CardThresholdReader_ListActiveCardsForThresholdScan_Call) Run(run func(ctx context.Context, refMonth valueobjects.Competence, limit int)) *CardThresholdReader_ListActiveCardsForThresholdScan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 valueobjects.Competence
		if args[1] != nil {
			arg1 = args[1].(valueobjects.Competence)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CardThresholdReader_ListActiveCardsForThresholdScan_Call) Return(activeCardForScans []interfaces.ActiveCardForScan, err error) *CardThresholdReader_ListActiveCardsForThresholdScan_Call {
	_c.Call.Return(activeCardForScans, err)
	return _c
}

func (_c *CardThresholdReader_ListActiveCardsForThresholdScan_Call) RunAndReturn(run func(ctx context.Context, refMonth valueobjects.Competence, limit int) ([]interfaces.ActiveCardForScan, error)) *CardThresholdReader_ListActiveCardsForThresholdScan_Call {
	_c.Call.Return(run)
	return _c
}
