// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/LimaTeixeiraTecnologia/mecontrola/internal/budgets/domain/events"
	"github.com/LimaTeixeiraTecnologia/mecontrola/internal/platform/database"
)

// NewExpenseCommittedPublisher creates a new instance of ExpenseCommittedPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExpenseCommittedPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExpenseCommittedPublisher {
	mock := &ExpenseCommittedPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ExpenseCommittedPublisher is an autogenerated mock type for the ExpenseCommittedPublisher type
type ExpenseCommittedPublisher struct {
	mock.Mock
}

type ExpenseCommittedPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *ExpenseCommittedPublisher) EXPECT() *ExpenseCommittedPublisher_Expecter {
	return &ExpenseCommittedPublisher_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function for the type ExpenseCommittedPublisher
func (_mock *ExpenseCommittedPublisher) Publish(ctx context.Context, db database.DBTX, evt events.ExpenseCommitted) error {
	ret := _mock.Called(ctx, db, evt)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, database.DBTX, events.ExpenseCommitted) error); ok {
		r0 = returnFunc(ctx, db, evt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ExpenseCommittedPublisher_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type ExpenseCommittedPublisher_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - db database.DBTX
//   - evt events.ExpenseCommitted
func (_e *ExpenseCommittedPublisher_Expecter) Publish(ctx any, db any, evt any) *ExpenseCommittedPublisher_Publish_Call {
	return &ExpenseCommittedPublisher_Publish_Call{Call: _e.mock.On("Publish", ctx, db, evt)}
}

func (_c *ExpenseCommittedPublisher_Publish_Call) Run(run func(ctx context.Context, db database.DBTX, evt events.ExpenseCommitted)) *ExpenseCommittedPublisher_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 database.DBTX
		if args[1] != nil {
			arg1 = args[1].(database.DBTX)
		}
		var arg2 events.ExpenseCommitted
		if args[2] != nil {
			arg2 = args[2].(events.ExpenseCommitted)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ExpenseCommittedPublisher_Publish_Call) Return(err error) *ExpenseCommittedPublisher_Publish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ExpenseCommittedPublisher_Publish_Call) RunAndReturn(run func(ctx context.Context, db database.DBTX, evt events.ExpenseCommitted) error) *ExpenseCommittedPublisher_Publish_Call {
	_c.Call.Return(run)
	return _c
}
