// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"

	"github.com/LimaTeixeiraTecnologia/mecontrola/internal/budgets/domain/entities"
	"github.com/LimaTeixeiraTecnologia/mecontrola/internal/budgets/domain/valueobjects"
)

// NewExpenseRepository creates a new instance of ExpenseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExpenseRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExpenseRepository {
	mock := &ExpenseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ExpenseRepository is an autogenerated mock type for the ExpenseRepository type
type ExpenseRepository struct {
	mock.Mock
}

type ExpenseRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ExpenseRepository) EXPECT() *ExpenseRepository_Expecter {
	return &ExpenseRepository_Expecter{mock: &_m.Mock}
}

// GetByIdentity provides a mock function for the type ExpenseRepository
func (_mock *ExpenseRepository) GetByIdentity(ctx context.Context, k entities.ExpenseIdentity) (entities.Expense, entities.ExpenseTombstone, error) {
	ret := _mock.Called(ctx, k)

	if len(ret) == 0 {
		panic("no return value specified for GetByIdentity")
	}

	var r0 entities.Expense
	var r1 entities.ExpenseTombstone
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.ExpenseIdentity) (entities.Expense, entities.ExpenseTombstone, error)); ok {
		return returnFunc(ctx, k)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.ExpenseIdentity) entities.Expense); ok {
		r0 = returnFunc(ctx, k)
	} else {
		r0 = ret.Get(0).(entities.Expense)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.ExpenseIdentity) entities.ExpenseTombstone); ok {
		r1 = returnFunc(ctx, k)
	} else {
		r1 = ret.Get(1).(entities.ExpenseTombstone)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, entities.ExpenseIdentity) error); ok {
		r2 = returnFunc(ctx, k)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// ExpenseRepository_GetByIdentity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIdentity'
type ExpenseRepository_GetByIdentity_Call struct {
	*mock.Call
}

// GetByIdentity is a helper method to define mock.On call
//   - ctx context.Context
//   - k entities.ExpenseIdentity
func (_e *ExpenseRepository_Expecter) GetByIdentity(ctx any, k any) *ExpenseRepository_GetByIdentity_Call {
	return &ExpenseRepository_GetByIdentity_Call{Call: _e.mock.On("GetByIdentity", ctx, k)}
}

func (_c *ExpenseRepository_GetByIdentity_Call) Run(run func(ctx context.Context, k entities.ExpenseIdentity)) *ExpenseRepository_GetByIdentity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.ExpenseIdentity
		if args[1] != nil {
			arg1 = args[1].(entities.ExpenseIdentity)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ExpenseRepository_GetByIdentity_Call) Return(expense entities.Expense, expenseTombstone entities.ExpenseTombstone, err error) *ExpenseRepository_GetByIdentity_Call {
	_c.Call.Return(expense, expenseTombstone, err)
	return _c
}

func (_c *ExpenseRepository_GetByIdentity_Call) RunAndReturn(run func(ctx context.Context, k entities.ExpenseIdentity) (entities.Expense, entities.ExpenseTombstone, error)) *ExpenseRepository_GetByIdentity_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type ExpenseRepository
func (_mock *ExpenseRepository) Insert(ctx context.Context, e entities.Expense) error {
	ret := _mock.Called(ctx, e)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Expense) error); ok {
		r0 = returnFunc(ctx, e)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ExpenseRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type ExpenseRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - e entities.Expense
func (_e *ExpenseRepository_Expecter) Insert(ctx any, e any) *ExpenseRepository_Insert_Call {
	return &ExpenseRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, e)}
}

func (_c *ExpenseRepository_Insert_Call) Run(run func(ctx context.Context, e entities.Expense)) *ExpenseRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.Expense
		if args[1] != nil {
			arg1 = args[1].(entities.Expense)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ExpenseRepository_Insert_Call) Return(err error) *ExpenseRepository_Insert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ExpenseRepository_Insert_Call) RunAndReturn(run func(ctx context.Context, e entities.Expense) error) *ExpenseRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// PurgeDeleted provides a mock function for the type ExpenseRepository
func (_mock *ExpenseRepository) PurgeDeleted(ctx context.Context, olderThan string, limit int) (int64, error) {
	ret := _mock.Called(ctx, olderThan, limit)

	if len(ret) == 0 {
		panic("no return value specified for PurgeDeleted")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) (int64, error)); ok {
		return returnFunc(ctx, olderThan, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) int64); ok {
		r0 = returnFunc(ctx, olderThan, limit)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = returnFunc(ctx, olderThan, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ExpenseRepository_PurgeDeleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PurgeDeleted'
type ExpenseRepository_PurgeDeleted_Call struct {
	*mock.Call
}

// PurgeDeleted is a helper method to define mock.On call
//   - ctx context.Context
//   - olderThan string
//   - limit int
func (_e *ExpenseRepository_Expecter) PurgeDeleted(ctx any, olderThan any, limit any) *ExpenseRepository_PurgeDeleted_Call {
	return &ExpenseRepository_PurgeDeleted_Call{Call: _e.mock.On("PurgeDeleted", ctx, olderThan, limit)}
}

func (_c *ExpenseRepository_PurgeDeleted_Call) Run(run func(ctx context.Context, olderThan string, limit int)) *ExpenseRepository_PurgeDeleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ExpenseRepository_PurgeDeleted_Call) Return(n int64, err error) *ExpenseRepository_PurgeDeleted_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *ExpenseRepository_PurgeDeleted_Call) RunAndReturn(run func(ctx context.Context, olderThan string, limit int) (int64, error)) *ExpenseRepository_PurgeDeleted_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDelete provides a mock function for the type ExpenseRepository
func (_mock *ExpenseRepository) SoftDelete(ctx context.Context, e entities.Expense, expectedVersion int64) (int64, error) {
	ret := _mock.Called(ctx, e, expectedVersion)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Expense, int64) (int64, error)); ok {
		return returnFunc(ctx, e, expectedVersion)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Expense, int64) int64); ok {
		r0 = returnFunc(ctx, e, expectedVersion)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.Expense, int64) error); ok {
		r1 = returnFunc(ctx, e, expectedVersion)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ExpenseRepository_SoftDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDelete'
type ExpenseRepository_SoftDelete_Call struct {
	*mock.Call
}

// SoftDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - e entities.Expense
//   - expectedVersion int64
func (_e *ExpenseRepository_Expecter) SoftDelete(ctx any, e any, expectedVersion any) *ExpenseRepository_SoftDelete_Call {
	return &ExpenseRepository_SoftDelete_Call{Call: _e.mock.On("SoftDelete", ctx, e, expectedVersion)}
}

func (_c *ExpenseRepository_SoftDelete_Call) Run(run func(ctx context.Context, e entities.Expense, expectedVersion int64)) *ExpenseRepository_SoftDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.Expense
		if args[1] != nil {
			arg1 = args[1].(entities.Expense)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ExpenseRepository_SoftDelete_Call) Return(tombstoneVersion int64, err error) *ExpenseRepository_SoftDelete_Call {
	_c.Call.Return(tombstoneVersion, err)
	return _c
}

func (_c *ExpenseRepository_SoftDelete_Call) RunAndReturn(run func(ctx context.Context, e entities.Expense, expectedVersion int64) (int64, error)) *ExpenseRepository_SoftDelete_Call {
	_c.Call.Return(run)
	return _c
}

// SumByRoot provides a mock function for the type ExpenseRepository
func (_mock *ExpenseRepository) SumByRoot(ctx context.Context, userID uuid.UUID, c valueobjects.Competence) (map[valueobjects.RootSlug]int64, error) {
	ret := _mock.Called(ctx, userID, c)

	if len(ret) == 0 {
		panic("no return value specified for SumByRoot")
	}

	var r0 map[valueobjects.RootSlug]int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, valueobjects.Competence) (map[valueobjects.RootSlug]int64, error)); ok {
		return returnFunc(ctx, userID, c)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, valueobjects.Competence) map[valueobjects.RootSlug]int64); ok {
		r0 = returnFunc(ctx, userID, c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[valueobjects.RootSlug]int64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, valueobjects.Competence) error); ok {
		r1 = returnFunc(ctx, userID, c)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ExpenseRepository_SumByRoot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SumByRoot'
type ExpenseRepository_SumByRoot_Call struct {
	*mock.Call
}

// SumByRoot is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - c valueobjects.Competence
func (_e *ExpenseRepository_Expecter) SumByRoot(ctx any, userID any, c any) *ExpenseRepository_SumByRoot_Call {
	return &ExpenseRepository_SumByRoot_Call{Call: _e.mock.On("SumByRoot", ctx, userID, c)}
}

func (_c *ExpenseRepository_SumByRoot_Call) Run(run func(ctx context.Context, userID uuid.UUID, c valueobjects.Competence)) *ExpenseRepository_SumByRoot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 valueobjects.Competence
		if args[2] != nil {
			arg2 = args[2].(valueobjects.Competence)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ExpenseRepository_SumByRoot_Call) Return(rootSlugToInt64 map[valueobjects.RootSlug]int64, err error) *ExpenseRepository_SumByRoot_Call {
	_c.Call.Return(rootSlugToInt64, err)
	return _c
}

func (_c *ExpenseRepository_SumByRoot_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, c valueobjects.Competence) (map[valueobjects.RootSlug]int64, error)) *ExpenseRepository_SumByRoot_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type ExpenseRepository
func (_mock *ExpenseRepository) Update(ctx context.Context, e entities.Expense, expectedVersion int64) error {
	ret := _mock.Called(ctx, e, expectedVersion)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Expense, int64) error); ok {
		r0 = returnFunc(ctx, e, expectedVersion)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ExpenseRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ExpenseRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - e entities.Expense
//   - expectedVersion int64
func (_e *ExpenseRepository_Expecter) Update(ctx any, e any, expectedVersion any) *ExpenseRepository_Update_Call {
	return &ExpenseRepository_Update_Call{Call: _e.mock.On("Update", ctx, e, expectedVersion)}
}

func (_c *ExpenseRepository_Update_Call) Run(run func(ctx context.Context, e entities.Expense, expectedVersion int64)) *ExpenseRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.Expense
		if args[1] != nil {
			arg1 = args[1].(entities.Expense)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ExpenseRepository_Update_Call) Return(err error) *ExpenseRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ExpenseRepository_Update_Call) RunAndReturn(run func(ctx context.Context, e entities.Expense, expectedVersion int64) error) *ExpenseRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
