// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/JailtonJunior94/devkit-go/pkg/database"
	"github.com/LimaTeixeiraTecnologia/mecontrola/internal/budgets/application/interfaces"
	mock "github.com/stretchr/testify/mock"
)

// NewRepositoryFactory creates a new instance of RepositoryFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepositoryFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepositoryFactory {
	mock := &RepositoryFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RepositoryFactory is an autogenerated mock type for the RepositoryFactory type
type RepositoryFactory struct {
	mock.Mock
}

type RepositoryFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *RepositoryFactory) EXPECT() *RepositoryFactory_Expecter {
	return &RepositoryFactory_Expecter{mock: &_m.Mock}
}

// AlertRepository provides a mock function for the type RepositoryFactory
func (_mock *RepositoryFactory) AlertRepository(db database.DBTX) interfaces.AlertRepository {
	ret := _mock.Called(db)

	if len(ret) == 0 {
		panic("no return value specified for AlertRepository")
	}

	var r0 interfaces.AlertRepository
	if returnFunc, ok := ret.Get(0).(func(database.DBTX) interfaces.AlertRepository); ok {
		r0 = returnFunc(db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.AlertRepository)
		}
	}
	return r0
}

// RepositoryFactory_AlertRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AlertRepository'
type RepositoryFactory_AlertRepository_Call struct {
	*mock.Call
}

// AlertRepository is a helper method to define mock.On call
//   - db database.DBTX
func (_e *RepositoryFactory_Expecter) AlertRepository(db interface{}) *RepositoryFactory_AlertRepository_Call {
	return &RepositoryFactory_AlertRepository_Call{Call: _e.mock.On("AlertRepository", db)}
}

func (_c *RepositoryFactory_AlertRepository_Call) Run(run func(db database.DBTX)) *RepositoryFactory_AlertRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 database.DBTX
		if args[0] != nil {
			arg0 = args[0].(database.DBTX)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RepositoryFactory_AlertRepository_Call) Return(alertRepository interfaces.AlertRepository) *RepositoryFactory_AlertRepository_Call {
	_c.Call.Return(alertRepository)
	return _c
}

func (_c *RepositoryFactory_AlertRepository_Call) RunAndReturn(run func(db database.DBTX) interfaces.AlertRepository) *RepositoryFactory_AlertRepository_Call {
	_c.Call.Return(run)
	return _c
}

// BudgetRepository provides a mock function for the type RepositoryFactory
func (_mock *RepositoryFactory) BudgetRepository(db database.DBTX) interfaces.BudgetRepository {
	ret := _mock.Called(db)

	if len(ret) == 0 {
		panic("no return value specified for BudgetRepository")
	}

	var r0 interfaces.BudgetRepository
	if returnFunc, ok := ret.Get(0).(func(database.DBTX) interfaces.BudgetRepository); ok {
		r0 = returnFunc(db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.BudgetRepository)
		}
	}
	return r0
}

// RepositoryFactory_BudgetRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BudgetRepository'
type RepositoryFactory_BudgetRepository_Call struct {
	*mock.Call
}

// BudgetRepository is a helper method to define mock.On call
//   - db database.DBTX
func (_e *RepositoryFactory_Expecter) BudgetRepository(db interface{}) *RepositoryFactory_BudgetRepository_Call {
	return &RepositoryFactory_BudgetRepository_Call{Call: _e.mock.On("BudgetRepository", db)}
}

func (_c *RepositoryFactory_BudgetRepository_Call) Run(run func(db database.DBTX)) *RepositoryFactory_BudgetRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 database.DBTX
		if args[0] != nil {
			arg0 = args[0].(database.DBTX)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RepositoryFactory_BudgetRepository_Call) Return(budgetRepository interfaces.BudgetRepository) *RepositoryFactory_BudgetRepository_Call {
	_c.Call.Return(budgetRepository)
	return _c
}

func (_c *RepositoryFactory_BudgetRepository_Call) RunAndReturn(run func(db database.DBTX) interfaces.BudgetRepository) *RepositoryFactory_BudgetRepository_Call {
	_c.Call.Return(run)
	return _c
}

// ExpenseRepository provides a mock function for the type RepositoryFactory
func (_mock *RepositoryFactory) ExpenseRepository(db database.DBTX) interfaces.ExpenseRepository {
	ret := _mock.Called(db)

	if len(ret) == 0 {
		panic("no return value specified for ExpenseRepository")
	}

	var r0 interfaces.ExpenseRepository
	if returnFunc, ok := ret.Get(0).(func(database.DBTX) interfaces.ExpenseRepository); ok {
		r0 = returnFunc(db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.ExpenseRepository)
		}
	}
	return r0
}

// RepositoryFactory_ExpenseRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExpenseRepository'
type RepositoryFactory_ExpenseRepository_Call struct {
	*mock.Call
}

// ExpenseRepository is a helper method to define mock.On call
//   - db database.DBTX
func (_e *RepositoryFactory_Expecter) ExpenseRepository(db interface{}) *RepositoryFactory_ExpenseRepository_Call {
	return &RepositoryFactory_ExpenseRepository_Call{Call: _e.mock.On("ExpenseRepository", db)}
}

func (_c *RepositoryFactory_ExpenseRepository_Call) Run(run func(db database.DBTX)) *RepositoryFactory_ExpenseRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 database.DBTX
		if args[0] != nil {
			arg0 = args[0].(database.DBTX)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RepositoryFactory_ExpenseRepository_Call) Return(expenseRepository interfaces.ExpenseRepository) *RepositoryFactory_ExpenseRepository_Call {
	_c.Call.Return(expenseRepository)
	return _c
}

func (_c *RepositoryFactory_ExpenseRepository_Call) RunAndReturn(run func(db database.DBTX) interfaces.ExpenseRepository) *RepositoryFactory_ExpenseRepository_Call {
	_c.Call.Return(run)
	return _c
}

// PendingEventRepository provides a mock function for the type RepositoryFactory
func (_mock *RepositoryFactory) PendingEventRepository(db database.DBTX) interfaces.PendingEventRepository {
	ret := _mock.Called(db)

	if len(ret) == 0 {
		panic("no return value specified for PendingEventRepository")
	}

	var r0 interfaces.PendingEventRepository
	if returnFunc, ok := ret.Get(0).(func(database.DBTX) interfaces.PendingEventRepository); ok {
		r0 = returnFunc(db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.PendingEventRepository)
		}
	}
	return r0
}

// RepositoryFactory_PendingEventRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PendingEventRepository'
type RepositoryFactory_PendingEventRepository_Call struct {
	*mock.Call
}

// PendingEventRepository is a helper method to define mock.On call
//   - db database.DBTX
func (_e *RepositoryFactory_Expecter) PendingEventRepository(db interface{}) *RepositoryFactory_PendingEventRepository_Call {
	return &RepositoryFactory_PendingEventRepository_Call{Call: _e.mock.On("PendingEventRepository", db)}
}

func (_c *RepositoryFactory_PendingEventRepository_Call) Run(run func(db database.DBTX)) *RepositoryFactory_PendingEventRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 database.DBTX
		if args[0] != nil {
			arg0 = args[0].(database.DBTX)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RepositoryFactory_PendingEventRepository_Call) Return(pendingEventRepository interfaces.PendingEventRepository) *RepositoryFactory_PendingEventRepository_Call {
	_c.Call.Return(pendingEventRepository)
	return _c
}

func (_c *RepositoryFactory_PendingEventRepository_Call) RunAndReturn(run func(db database.DBTX) interfaces.PendingEventRepository) *RepositoryFactory_PendingEventRepository_Call {
	_c.Call.Return(run)
	return _c
}

// ThresholdStateRepository provides a mock function for the type RepositoryFactory
func (_mock *RepositoryFactory) ThresholdStateRepository(db database.DBTX) interfaces.ThresholdStateRepository {
	ret := _mock.Called(db)

	if len(ret) == 0 {
		panic("no return value specified for ThresholdStateRepository")
	}

	var r0 interfaces.ThresholdStateRepository
	if returnFunc, ok := ret.Get(0).(func(database.DBTX) interfaces.ThresholdStateRepository); ok {
		r0 = returnFunc(db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.ThresholdStateRepository)
		}
	}
	return r0
}

// RepositoryFactory_ThresholdStateRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ThresholdStateRepository'
type RepositoryFactory_ThresholdStateRepository_Call struct {
	*mock.Call
}

// ThresholdStateRepository is a helper method to define mock.On call
//   - db database.DBTX
func (_e *RepositoryFactory_Expecter) ThresholdStateRepository(db interface{}) *RepositoryFactory_ThresholdStateRepository_Call {
	return &RepositoryFactory_ThresholdStateRepository_Call{Call: _e.mock.On("ThresholdStateRepository", db)}
}

func (_c *RepositoryFactory_ThresholdStateRepository_Call) Run(run func(db database.DBTX)) *RepositoryFactory_ThresholdStateRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 database.DBTX
		if args[0] != nil {
			arg0 = args[0].(database.DBTX)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RepositoryFactory_ThresholdStateRepository_Call) Return(thresholdStateRepository interfaces.ThresholdStateRepository) *RepositoryFactory_ThresholdStateRepository_Call {
	_c.Call.Return(thresholdStateRepository)
	return _c
}

func (_c *RepositoryFactory_ThresholdStateRepository_Call) RunAndReturn(run func(db database.DBTX) interfaces.ThresholdStateRepository) *RepositoryFactory_ThresholdStateRepository_Call {
	_c.Call.Return(run)
	return _c
}
