// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"

	"github.com/LimaTeixeiraTecnologia/mecontrola/internal/budgets/domain/entities"
	"github.com/LimaTeixeiraTecnologia/mecontrola/internal/budgets/domain/valueobjects"
)

// NewThresholdStateRepository creates a new instance of ThresholdStateRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewThresholdStateRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ThresholdStateRepository {
	mock := &ThresholdStateRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ThresholdStateRepository is an autogenerated mock type for the ThresholdStateRepository type
type ThresholdStateRepository struct {
	mock.Mock
}

type ThresholdStateRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ThresholdStateRepository) EXPECT() *ThresholdStateRepository_Expecter {
	return &ThresholdStateRepository_Expecter{mock: &_m.Mock}
}

// GetCurrentlyCrossed provides a mock function for the type ThresholdStateRepository
func (_mock *ThresholdStateRepository) GetCurrentlyCrossed(ctx context.Context, userID uuid.UUID, competence valueobjects.Competence, rootSlug valueobjects.RootSlug) (map[valueobjects.Threshold]bool, error) {
	ret := _mock.Called(ctx, userID, competence, rootSlug)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentlyCrossed")
	}

	var r0 map[valueobjects.Threshold]bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, valueobjects.Competence, valueobjects.RootSlug) (map[valueobjects.Threshold]bool, error)); ok {
		return returnFunc(ctx, userID, competence, rootSlug)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, valueobjects.Competence, valueobjects.RootSlug) map[valueobjects.Threshold]bool); ok {
		r0 = returnFunc(ctx, userID, competence, rootSlug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[valueobjects.Threshold]bool)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, valueobjects.Competence, valueobjects.RootSlug) error); ok {
		r1 = returnFunc(ctx, userID, competence, rootSlug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ThresholdStateRepository_GetCurrentlyCrossed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentlyCrossed'
type ThresholdStateRepository_GetCurrentlyCrossed_Call struct {
	*mock.Call
}

// GetCurrentlyCrossed is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - competence valueobjects.Competence
//   - rootSlug valueobjects.RootSlug
func (_e *ThresholdStateRepository_Expecter) GetCurrentlyCrossed(ctx any, userID any, competence any, rootSlug any) *ThresholdStateRepository_GetCurrentlyCrossed_Call {
	return &ThresholdStateRepository_GetCurrentlyCrossed_Call{Call: _e.mock.On("GetCurrentlyCrossed", ctx, userID, competence, rootSlug)}
}

func (_c *ThresholdStateRepository_GetCurrentlyCrossed_Call) Run(run func(ctx context.Context, userID uuid.UUID, competence valueobjects.Competence, rootSlug valueobjects.RootSlug)) *ThresholdStateRepository_GetCurrentlyCrossed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 valueobjects.Competence
		if args[2] != nil {
			arg2 = args[2].(valueobjects.Competence)
		}
		var arg3 valueobjects.RootSlug
		if args[3] != nil {
			arg3 = args[3].(valueobjects.RootSlug)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ThresholdStateRepository_GetCurrentlyCrossed_Call) Return(thresholdToBool map[valueobjects.Threshold]bool, err error) *ThresholdStateRepository_GetCurrentlyCrossed_Call {
	_c.Call.Return(thresholdToBool, err)
	return _c
}

func (_c *ThresholdStateRepository_GetCurrentlyCrossed_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, competence valueobjects.Competence, rootSlug valueobjects.RootSlug) (map[valueobjects.Threshold]bool, error)) *ThresholdStateRepository_GetCurrentlyCrossed_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertIfTransition provides a mock function for the type ThresholdStateRepository
func (_mock *ThresholdStateRepository) UpsertIfTransition(ctx context.Context, k entities.ThresholdKey, nowCrossed bool, committedAt time.Time) (bool, error) {
	ret := _mock.Called(ctx, k, nowCrossed, committedAt)

	if len(ret) == 0 {
		panic("no return value specified for UpsertIfTransition")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.ThresholdKey, bool, time.Time) (bool, error)); ok {
		return returnFunc(ctx, k, nowCrossed, committedAt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.ThresholdKey, bool, time.Time) bool); ok {
		r0 = returnFunc(ctx, k, nowCrossed, committedAt)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.ThresholdKey, bool, time.Time) error); ok {
		r1 = returnFunc(ctx, k, nowCrossed, committedAt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ThresholdStateRepository_UpsertIfTransition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertIfTransition'
type ThresholdStateRepository_UpsertIfTransition_Call struct {
	*mock.Call
}

// UpsertIfTransition is a helper method to define mock.On call
//   - ctx context.Context
//   - k entities.ThresholdKey
//   - nowCrossed bool
//   - committedAt time.Time
func (_e *ThresholdStateRepository_Expecter) UpsertIfTransition(ctx any, k any, nowCrossed any, committedAt any) *ThresholdStateRepository_UpsertIfTransition_Call {
	return &ThresholdStateRepository_UpsertIfTransition_Call{Call: _e.mock.On("UpsertIfTransition", ctx, k, nowCrossed, committedAt)}
}

func (_c *ThresholdStateRepository_UpsertIfTransition_Call) Run(run func(ctx context.Context, k entities.ThresholdKey, nowCrossed bool, committedAt time.Time)) *ThresholdStateRepository_UpsertIfTransition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.ThresholdKey
		if args[1] != nil {
			arg1 = args[1].(entities.ThresholdKey)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ThresholdStateRepository_UpsertIfTransition_Call) Return(transitioned bool, err error) *ThresholdStateRepository_UpsertIfTransition_Call {
	_c.Call.Return(transitioned, err)
	return _c
}

func (_c *ThresholdStateRepository_UpsertIfTransition_Call) RunAndReturn(run func(ctx context.Context, k entities.ThresholdKey, nowCrossed bool, committedAt time.Time) (bool, error)) *ThresholdStateRepository_UpsertIfTransition_Call {
	_c.Call.Return(run)
	return _c
}
