// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"

	"github.com/LimaTeixeiraTecnologia/mecontrola/internal/budgets/application/interfaces"
)

// NewUserChannelResolver creates a new instance of UserChannelResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserChannelResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserChannelResolver {
	mock := &UserChannelResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserChannelResolver is an autogenerated mock type for the UserChannelResolver type
type UserChannelResolver struct {
	mock.Mock
}

type UserChannelResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *UserChannelResolver) EXPECT() *UserChannelResolver_Expecter {
	return &UserChannelResolver_Expecter{mock: &_m.Mock}
}

// ResolvePreferred provides a mock function for the type UserChannelResolver
func (_mock *UserChannelResolver) ResolvePreferred(ctx context.Context, userID uuid.UUID) (interfaces.UserChannelPreference, bool, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ResolvePreferred")
	}

	var r0 interfaces.UserChannelPreference
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (interfaces.UserChannelPreference, bool, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) interfaces.UserChannelPreference); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(interfaces.UserChannelPreference)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) bool); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID) error); ok {
		r2 = returnFunc(ctx, userID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// UserChannelResolver_ResolvePreferred_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolvePreferred'
type UserChannelResolver_ResolvePreferred_Call struct {
	*mock.Call
}

// ResolvePreferred is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *UserChannelResolver_Expecter) ResolvePreferred(ctx any, userID any) *UserChannelResolver_ResolvePreferred_Call {
	return &UserChannelResolver_ResolvePreferred_Call{Call: _e.mock.On("ResolvePreferred", ctx, userID)}
}

func (_c *UserChannelResolver_ResolvePreferred_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *UserChannelResolver_ResolvePreferred_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserChannelResolver_ResolvePreferred_Call) Return(userChannelPreference interfaces.UserChannelPreference, b bool, err error) *UserChannelResolver_ResolvePreferred_Call {
	_c.Call.Return(userChannelPreference, b, err)
	return _c
}

func (_c *UserChannelResolver_ResolvePreferred_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (interfaces.UserChannelPreference, bool, error)) *UserChannelResolver_ResolvePreferred_Call {
	_c.Call.Return(run)
	return _c
}
