package golden

func dailyOperationsCases() []Case {
	return []Case{
		{
			Name:             "edicao lancamento por termo e valor",
			Category:         CategoryExpenseIncome,
			Origin:           "synthetic",
			Input:            "corrige aquele lançamento do mercado, era 25 reais",
			ToolSubset:       []string{"edit_entry"},
			ExpectedTool:     "edit_entry",
			ResponseProperty: nonEmptyResponse,
			ResponseDescribe: "inicia edição de lançamento buscando candidatos por termo/valor",
		},
		{
			Name:             "edicao lancamento de receita por termo e valor",
			Category:         CategoryExpenseIncome,
			Origin:           "synthetic",
			Input:            "corrige aquela receita do salário, era 3200 reais",
			ToolSubset:       []string{"edit_entry"},
			ExpectedTool:     "edit_entry",
			ResponseProperty: nonEmptyResponse,
			ResponseDescribe: "inicia edição de lançamento de receita buscando candidatos por termo/valor",
		},
		{
			Name:             "alterar distribuicao do orcamento",
			Category:         CategoryBudget,
			Origin:           "synthetic",
			Input:            "quero mudar a distribuição do orçamento, custo fixo pra 35%",
			ToolSubset:       []string{"adjust_allocation"},
			ExpectedTool:     "adjust_allocation",
			ResponseProperty: nonEmptyResponse,
			ResponseDescribe: "solicita ajuste de alocação por categoria",
		},
		{
			Name:             "alterar valor total do orcamento",
			Category:         CategoryBudgetTotal,
			Origin:           "synthetic",
			Input:            "minha renda mudou, quero alterar o valor total do meu orçamento para 6000 reais",
			ToolSubset:       []string{"edit_budget_total"},
			ExpectedTool:     "edit_budget_total",
			ResponseProperty: nonEmptyResponse,
			ResponseDescribe: "solicita alteração do total do orçamento reescalando a distribuição",
		},
		{
			Name:             "editar cartao apelido",
			Category:         CategoryCard,
			Origin:           "synthetic",
			Input:            "quero mudar o apelido do meu cartão nubank para nu roxo",
			ToolSubset:       []string{"update_card", "resolve_card", "list_cards"},
			ExpectedTool:     "update_card",
			ResponseProperty: nonEmptyResponse,
			ResponseDescribe: "solicita atualização de dados do cartão com confirmação",
		},
		{
			Name:               "excluir cartao com aviso de impacto",
			Category:           CategoryCard,
			Origin:             "synthetic",
			Input:              "quero excluir meu cartão nubank",
			ToolSubset:         []string{"delete_entry", "resolve_card", "list_cards"},
			ExpectedAnyOfTools: []string{"resolve_card", "delete_entry", "list_cards"},
			ResponseProperty:   nonEmptyResponse,
			ResponseDescribe:   "resolve o 💳 por apelido (resolve_card, ou list_cards quando a resolução exige desambiguação) antes de excluir, ou já passa pelo gate destrutivo com aviso de impacto",
		},
		{
			Name:             "alterar objetivo financeiro",
			Category:         CategoryGoal,
			Origin:           "synthetic",
			Input:            "quero mudar meu objetivo financeiro, agora é comprar um carro",
			ToolSubset:       []string{"edit_goal"},
			ExpectedTool:     "edit_goal",
			ResponseProperty: nonEmptyResponse,
			ResponseDescribe: "busca objetivo atual, pergunta o novo e apresenta resumo antes de reescrever a working memory",
		},
		{
			Name:             "cancelamento de plano informacional",
			Category:         CategoryCancelPlan,
			Origin:           "synthetic",
			Input:            "como eu cancelo minha assinatura?",
			ToolSubset:       []string{"cancel_plan_info"},
			ExpectedTool:     "cancel_plan_info",
			ResponseProperty: nonEmptyResponse,
			ResponseDescribe: "responde com o passo a passo oficial de cancelamento sem alterar a assinatura",
		},
		{
			Name:             "suporte informacional",
			Category:         CategorySupport,
			Origin:           "synthetic",
			Input:            "preciso de ajuda, como falo com o suporte?",
			ToolSubset:       []string{"support_info"},
			ExpectedTool:     "support_info",
			ResponseProperty: containsAny("contato@limateixeira.com.br", "24 hora", "e-mail"),
			ResponseDescribe: "responde com o e-mail de suporte e prazo de resposta verbatim",
		},
		{
			Name:             "resumo por categoria",
			Category:         CategoryCategoryDetail,
			Origin:           "synthetic",
			Input:            "como está minha categoria de alimentação esse mês?",
			ToolSubset:       []string{"category_detail"},
			ExpectedTool:     "category_detail",
			ResponseProperty: nonEmptyResponse,
			ResponseDescribe: "detalha lançamentos, planejado, gasto e disponível/excedente da categoria",
		},
		{
			Name:             "resumo geral do orcamento",
			Category:         CategoryGeneralSummary,
			Origin:           "synthetic",
			Input:            "me dá um panorama geral do meu orçamento esse mês",
			ToolSubset:       []string{"category_detail"},
			ExpectedTool:     "category_detail",
			ResponseProperty: nonEmptyResponse,
			ResponseDescribe: "resumo geral determinístico com categorias e consolidado (planejado, gasto, disponível)",
		},
	}
}
