package golden

func incomeNaturalLanguageCases() []Case {
	return []Case{
		{
			Name:         "receita nl grupo recebimentos",
			Category:     CategoryExpenseIncome,
			Origin:       "RF-01 grupo 1 (recebimentos)",
			Input:        "recebi 200 reais hoje",
			ToolSubset:   []string{"register_income", "register_expense"},
			ExpectedTool: "register_income",
			ExpectedArgs: map[string]any{
				"amountCents": 20000.0,
			},
			ResponseProperty: nonEmptyResponse,
			ResponseDescribe: "recebimento genérico roteia para register_income com o valor correto",
		},
		{
			Name:         "receita nl grupo trabalho",
			Category:     CategoryExpenseIncome,
			Origin:       "RF-01 grupo 2 (trabalho)",
			Input:        "ganhei 800 reais com um trabalho ontem",
			ToolSubset:   []string{"register_income", "register_expense"},
			ExpectedTool: "register_income",
			ExpectedArgs: map[string]any{
				"amountCents": 80000.0,
			},
			ResponseProperty: nonEmptyResponse,
			ResponseDescribe: "receita de trabalho roteia para register_income",
		},
		{
			Name:         "receita nl grupo autonomos",
			Category:     CategoryExpenseIncome,
			Origin:       "RF-01 grupo 3 (profissionais autônomos)",
			Input:        "fechei um freela de 1500 reais",
			ToolSubset:   []string{"register_income", "register_expense"},
			ExpectedTool: "register_income",
			ExpectedArgs: map[string]any{
				"amountCents": 150000.0,
			},
			ResponseProperty: nonEmptyResponse,
			ResponseDescribe: "receita de autônomo (freela) roteia para register_income",
		},
		{
			Name:         "receita nl grupo comercio",
			Category:     CategoryExpenseIncome,
			Origin:       "RF-01 grupo 4 (comércio)",
			Input:        "vendi um produto por 350 reais",
			ToolSubset:   []string{"register_income", "register_expense"},
			ExpectedTool: "register_income",
			ExpectedArgs: map[string]any{
				"amountCents": 35000.0,
			},
			ResponseProperty: nonEmptyResponse,
			ResponseDescribe: "venda de comércio roteia para register_income",
		},
		{
			Name:         "receita nl grupo producao artesanal",
			Category:     CategoryExpenseIncome,
			Origin:       "RF-01 grupo 5 (produção artesanal)",
			Input:        "vendi meus bolos caseiros e faturei 240 reais",
			ToolSubset:   []string{"register_income", "register_expense"},
			ExpectedTool: "register_income",
			ExpectedArgs: map[string]any{
				"amountCents": 24000.0,
			},
			ResponseProperty: nonEmptyResponse,
			ResponseDescribe: "produção artesanal roteia para register_income",
		},
		{
			Name:         "receita nl grupo comissoes bonus",
			Category:     CategoryExpenseIncome,
			Origin:       "RF-01 grupo 6 (comissões e bônus)",
			Input:        "caiu minha comissão de 600 reais",
			ToolSubset:   []string{"register_income", "register_expense"},
			ExpectedTool: "register_income",
			ExpectedArgs: map[string]any{
				"amountCents": 60000.0,
			},
			ResponseProperty: nonEmptyResponse,
			ResponseDescribe: "comissão roteia para register_income",
		},
		{
			Name:         "receita nl grupo salario",
			Category:     CategoryExpenseIncome,
			Origin:       "RF-01 grupo 7 (salário)",
			Input:        "recebi meu salário de 3000 reais",
			ToolSubset:   []string{"register_income", "register_expense"},
			ExpectedTool: "register_income",
			ExpectedArgs: map[string]any{
				"amountCents": 300000.0,
			},
			ResponseProperty: nonEmptyResponse,
			ResponseDescribe: "salário roteia para register_income",
		},
		{
			Name:         "receita nl grupo alugueis",
			Category:     CategoryExpenseIncome,
			Origin:       "RF-01 grupo 8 (aluguéis)",
			Input:        "recebi 950 reais de aluguel do apartamento",
			ToolSubset:   []string{"register_income", "register_expense"},
			ExpectedTool: "register_income",
			ExpectedArgs: map[string]any{
				"amountCents": 95000.0,
			},
			ResponseProperty: nonEmptyResponse,
			ResponseDescribe: "aluguel recebido roteia para register_income",
		},
		{
			Name:         "receita nl grupo investimentos",
			Category:     CategoryExpenseIncome,
			Origin:       "RF-01 grupo 9 (investimentos)",
			Input:        "rendeu 90 reais de dividendos na minha corretora",
			ToolSubset:   []string{"register_income", "register_expense"},
			ExpectedTool: "register_income",
			ExpectedArgs: map[string]any{
				"amountCents": 9000.0,
			},
			ResponseProperty: nonEmptyResponse,
			ResponseDescribe: "rendimento de investimento roteia para register_income",
		},
		{
			Name:         "receita nl valor por extenso simples cem",
			Category:     CategoryExpenseIncome,
			Origin:       "RF-04 por-extenso simples",
			Input:        "recebi cem reais de um serviço hoje",
			ToolSubset:   []string{"register_income", "register_expense"},
			ExpectedTool: "register_income",
			ExpectedArgs: map[string]any{
				"amountCents": 10000.0,
			},
			ResponseProperty: nonEmptyResponse,
			ResponseDescribe: "valor por-extenso simples cem convertido para 10000 centavos",
		},
		{
			Name:         "receita nl valor por extenso simples dois mil",
			Category:     CategoryExpenseIncome,
			Origin:       "RF-04 por-extenso simples",
			Input:        "ganhei dois mil de comissão esse mês",
			ToolSubset:   []string{"register_income", "register_expense"},
			ExpectedTool: "register_income",
			ExpectedArgs: map[string]any{
				"amountCents": 200000.0,
			},
			ResponseProperty: nonEmptyResponse,
			ResponseDescribe: "valor por-extenso simples dois mil convertido para 200000 centavos",
		},
		{
			Name:         "receita nl valor por extenso composto",
			Category:     CategoryExpenseIncome,
			Origin:       "RF-04 por-extenso composto",
			Input:        "recebi dois mil e quinhentos de um freela",
			ToolSubset:   []string{"register_income", "register_expense"},
			ExpectedTool: "register_income",
			ExpectedArgs: map[string]any{
				"amountCents": 250000.0,
			},
			ResponseProperty: nonEmptyResponse,
			ResponseDescribe: "valor por-extenso composto dois mil e quinhentos convertido para 250000 centavos",
		},
		{
			Name:         "receita nl valor giria pila",
			Category:     CategoryExpenseIncome,
			Origin:       "RF-03 gíria",
			Input:        "recebi 100 pila de um bico hoje",
			ToolSubset:   []string{"register_income", "register_expense"},
			ExpectedTool: "register_income",
			ExpectedArgs: map[string]any{
				"amountCents": 10000.0,
			},
			ResponseProperty: nonEmptyResponse,
			ResponseDescribe: "gíria 100 pila convertida para 10000 centavos",
		},
		{
			Name:         "receita nl valor giria conto",
			Category:     CategoryExpenseIncome,
			Origin:       "RF-03 gíria",
			Input:        "caiu 500 conto de comissão",
			ToolSubset:   []string{"register_income", "register_expense"},
			ExpectedTool: "register_income",
			ExpectedArgs: map[string]any{
				"amountCents": 50000.0,
			},
			ResponseProperty: nonEmptyResponse,
			ResponseDescribe: "gíria 500 conto convertida para 50000 centavos",
		},
		{
			Name:         "receita nl data semana passada roteia com valor",
			Category:     CategoryExpenseIncome,
			Origin:       "RF-06 data nova (semana passada); resolução determinística coberta por unit test de ParseInputDate (task 1.0)",
			Input:        "recebi 300 reais de freela semana passada",
			ToolSubset:   []string{"register_income", "register_expense"},
			ExpectedTool: "register_income",
			ExpectedArgs: map[string]any{
				"amountCents": 30000.0,
			},
			ResponseProperty: nonEmptyResponse,
			ResponseDescribe: "frase de receita com data relativa (semana passada) roteia para register_income com o valor correto",
		},
		{
			Name:         "receita nl data mes passado roteia com valor",
			Category:     CategoryExpenseIncome,
			Origin:       "RF-06 data nova (mês passado); resolução determinística coberta por unit test de ParseInputDate (task 1.0)",
			Input:        "recebi 700 reais de aluguel mês passado",
			ToolSubset:   []string{"register_income", "register_expense"},
			ExpectedTool: "register_income",
			ExpectedArgs: map[string]any{
				"amountCents": 70000.0,
			},
			ResponseProperty: nonEmptyResponse,
			ResponseDescribe: "frase de receita com data relativa (mês passado) roteia para register_income com o valor correto",
		},
		{
			Name:         "receita nl data dia 10 roteia com valor",
			Category:     CategoryExpenseIncome,
			Origin:       "RF-06 data nova (dia N); resolução determinística coberta por unit test de ParseInputDate (task 1.0)",
			Input:        "recebi 450 reais de comissão dia 10",
			ToolSubset:   []string{"register_income", "register_expense"},
			ExpectedTool: "register_income",
			ExpectedArgs: map[string]any{
				"amountCents": 45000.0,
			},
			ResponseProperty: nonEmptyResponse,
			ResponseDescribe: "frase de receita com dia-do-mês isolado (dia 10) roteia para register_income com o valor correto",
		},
		{
			Name:             "receita nl confirmacao relay verbatim",
			Category:         CategoryExpenseIncome,
			Origin:           "RF-11/RF-12 confirmação oficial antes de gravar (relay verbatim da tool)",
			Input:            "recebi 200 reais de um freela hoje",
			ToolSubset:       []string{"register_income_confirm"},
			ExpectedTool:     "register_income",
			ResponseProperty: containsAny(RegisterExpenseConfirmMessage),
			ResponseDescribe: "agente repassa verbatim a confirmação oficial retornada pela tool antes de qualquer gravação",
		},
		{
			Name:         "receita nl canal reconhecido nao persiste pagamento",
			Category:     CategoryExpenseIncome,
			Origin:       "RF-15 canal (no cartão) reconhecido como receita, sem capturar forma de pagamento",
			Input:        "recebi 500 no cartão de um cliente hoje",
			ToolSubset:   []string{"register_income", "register_expense"},
			ExpectedTool: "register_income",
			ExpectedArgs: map[string]any{
				"amountCents": 50000.0,
			},
			ResponseProperty: allOf(
				nonEmptyResponse,
				notContainsAny("forma de pagamento", "qual forma", "pix, débito", "no débito, no crédito"),
			),
			ResponseDescribe: "receita com canal (no cartão) roteia para register_income sem perguntar nem persistir forma de pagamento",
		},
		{
			Name:         "receita nl separador milhar nao vira multiplo",
			Category:     CategoryExpenseIncome,
			Origin:       "armadilha produção: separador de milhar não pode virar aviso de múltiplos lançamentos",
			Input:        "recebi R$ 1.500,00 de salário",
			ToolSubset:   []string{"register_income", "register_expense"},
			ExpectedTool: "register_income",
			ExpectedArgs: map[string]any{
				"amountCents": 150000.0,
			},
			ResponseProperty: allOf(
				nonEmptyResponse,
				notContainsAny("mais de um lançamento", "um de cada vez", "um lançamento por vez", "separadamente"),
			),
			ResponseDescribe: "receita com separador de milhar registra valor único e nunca dispara aviso de múltiplos lançamentos",
		},
		{
			Name:         "receita nl origem literal sem parafrase",
			Category:     CategoryExpenseIncome,
			Origin:       "RF-02 armadilha: origem registrada com o termo literal do usuário, nunca paráfrase",
			Input:        "recebi 250 reais da venda de um bolo caseiro",
			ToolSubset:   []string{"register_income", "register_expense"},
			ExpectedTool: "register_income",
			ExpectedArgs: map[string]any{
				"amountCents": 25000.0,
			},
			ResponseProperty: allOf(
				nonEmptyResponse,
				notContainsAny("mais de um lançamento", "um de cada vez", "um lançamento por vez", "separadamente"),
			),
			ResponseDescribe: "origem da receita preservada como termo literal, valor único sem falso múltiplo",
		},
	}
}
