package golden

func queryCases() []Case {
	return []Case{
		{
			Name:             "c1 quanto gastei no mes",
			Category:         CategoryQuery,
			Origin:           "synthetic",
			Input:            "quanto gastei esse mês?",
			ToolSubset:       []string{"query_month"},
			ExpectedTool:     "query_month",
			ResponseProperty: nonEmptyResponse,
			ResponseDescribe: "resposta baseada em dado retornado por query_month",
		},
		{
			Name:             "c2 como estou indo panorama",
			Category:         CategoryQuery,
			Origin:           "synthetic",
			Input:            "como estou indo?",
			ToolSubset:       []string{"query_month", "query_plan"},
			ExpectedTools:    []string{"query_month", "query_plan"},
			ResponseProperty: nonEmptyResponse,
			ResponseDescribe: "panorama combina resumo do mês e do orçamento",
		},
		{
			Name:             "c3 orcamento do mes",
			Category:         CategoryQuery,
			Origin:           "synthetic",
			Input:            "como está meu orçamento deste mês?",
			ToolSubset:       []string{"query_plan"},
			ExpectedTool:     "query_plan",
			ResponseProperty: nonEmptyResponse,
			ResponseDescribe: "resposta baseada em dado retornado por query_plan",
		},
		{
			Name:             "c4 ultima transacao",
			Category:         CategoryQuery,
			Origin:           "synthetic",
			Input:            "qual foi a minha última transação?",
			ToolSubset:       []string{"query_month"},
			ExpectedTool:     "query_month",
			ResponseProperty: nonEmptyResponse,
			ResponseDescribe: "consulta a tool de mês para responder sobre a última transação",
		},
		{
			Name:             "c5 busca por termo",
			Category:         CategoryQuery,
			Origin:           "synthetic",
			Input:            "procura lançamentos com a palavra mercado",
			ToolSubset:       []string{"search_transactions"},
			ExpectedTool:     "search_transactions",
			ResponseProperty: nonEmptyResponse,
			ResponseDescribe: "busca explícita por termo usa search_transactions",
		},
		{
			Name:             "c6 orcamento completo",
			Category:         CategoryQuery,
			Origin:           "synthetic",
			Input:            "me mostra o orçamento completo",
			ToolSubset:       []string{"query_plan"},
			ExpectedTool:     "query_plan",
			ResponseProperty: nonEmptyResponse,
			ResponseDescribe: "orçamento completo consulta query_plan",
		},
		{
			Name:               "c7 retrospectiva mensal",
			Category:           CategoryQuery,
			Origin:             "synthetic",
			Input:              "como foi meu mês de junho de 2026?",
			ToolSubset:         []string{"query_plan", "query_month"},
			ExpectedAnyOfTools: []string{"query_plan", "query_month"},
			ResponseProperty:   containsAny("junho de 2026"),
			ResponseDescribe:   "retrospectiva compõe query_plan/query_month e exibe mês por extenso",
		},
	}
}
