// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/LimaTeixeiraTecnologia/mecontrola/internal/platform/llm"
)

func NewProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *Provider {
	mock := &Provider{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}

type Provider struct {
	mock.Mock
}

type Provider_Expecter struct {
	mock *mock.Mock
}

func (_m *Provider) EXPECT() *Provider_Expecter {
	return &Provider_Expecter{mock: &_m.Mock}
}

func (_mock *Provider) Slug() string {
	ret := _mock.Called()
	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		return returnFunc()
	}
	r0 = ret.Get(0).(string)
	return r0
}

type Provider_Slug_Call struct {
	*mock.Call
}

func (_e *Provider_Expecter) Slug() *Provider_Slug_Call {
	return &Provider_Slug_Call{Call: _e.mock.On("Slug")}
}

func (_c *Provider_Slug_Call) Return(slug string) *Provider_Slug_Call {
	_c.Call.Return(slug)
	return _c
}

func (_mock *Provider) Complete(ctx context.Context, req llm.Request) (llm.Response, error) {
	ret := _mock.Called(ctx, req)
	var r0 llm.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, llm.Request) (llm.Response, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, llm.Request) llm.Response); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(llm.Response)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, llm.Request) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type Provider_Complete_Call struct {
	*mock.Call
}

func (_e *Provider_Expecter) Complete(ctx any, req any) *Provider_Complete_Call {
	return &Provider_Complete_Call{Call: _e.mock.On("Complete", ctx, req)}
}

func (_c *Provider_Complete_Call) Run(run func(ctx context.Context, req llm.Request)) *Provider_Complete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(arg0, args[1].(llm.Request))
	})
	return _c
}

func (_c *Provider_Complete_Call) Return(resp llm.Response, err error) *Provider_Complete_Call {
	_c.Call.Return(resp, err)
	return _c
}

func (_c *Provider_Complete_Call) RunAndReturn(run func(context.Context, llm.Request) (llm.Response, error)) *Provider_Complete_Call {
	_c.Call.Return(run)
	return _c
}

func (_mock *Provider) Stream(ctx context.Context, req llm.Request) (llm.TokenStream, error) {
	ret := _mock.Called(ctx, req)
	var r0 llm.TokenStream
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, llm.Request) (llm.TokenStream, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, llm.Request) llm.TokenStream); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(llm.TokenStream)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, llm.Request) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type Provider_Stream_Call struct {
	*mock.Call
}

func (_e *Provider_Expecter) Stream(ctx any, req any) *Provider_Stream_Call {
	return &Provider_Stream_Call{Call: _e.mock.On("Stream", ctx, req)}
}

func (_c *Provider_Stream_Call) Return(ts llm.TokenStream, err error) *Provider_Stream_Call {
	_c.Call.Return(ts, err)
	return _c
}

func (_c *Provider_Stream_Call) RunAndReturn(run func(context.Context, llm.Request) (llm.TokenStream, error)) *Provider_Stream_Call {
	_c.Call.Return(run)
	return _c
}

func (_mock *Provider) Embed(ctx context.Context, texts []string) ([][]float32, error) {
	ret := _mock.Called(ctx, texts)
	var r0 [][]float32
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) ([][]float32, error)); ok {
		return returnFunc(ctx, texts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) [][]float32); ok {
		r0 = returnFunc(ctx, texts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]float32)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, texts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type Provider_Embed_Call struct {
	*mock.Call
}

func (_e *Provider_Expecter) Embed(ctx any, texts any) *Provider_Embed_Call {
	return &Provider_Embed_Call{Call: _e.mock.On("Embed", ctx, texts)}
}

func (_c *Provider_Embed_Call) Return(embeddings [][]float32, err error) *Provider_Embed_Call {
	_c.Call.Return(embeddings, err)
	return _c
}
