// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/LimaTeixeiraTecnologia/mecontrola/internal/agents/application/interfaces"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewCardManager creates a new instance of CardManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCardManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *CardManager {
	mock := &CardManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CardManager is an autogenerated mock type for the CardManager type
type CardManager struct {
	mock.Mock
}

type CardManager_Expecter struct {
	mock *mock.Mock
}

func (_m *CardManager) EXPECT() *CardManager_Expecter {
	return &CardManager_Expecter{mock: &_m.Mock}
}

// BankRecognized provides a mock function for the type CardManager
func (_mock *CardManager) BankRecognized(ctx context.Context, bank string) (bool, error) {
	ret := _mock.Called(ctx, bank)

	if len(ret) == 0 {
		panic("no return value specified for BankRecognized")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, bank)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, bank)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, bank)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CardManager_BankRecognized_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BankRecognized'
type CardManager_BankRecognized_Call struct {
	*mock.Call
}

// BankRecognized is a helper method to define mock.On call
//   - ctx context.Context
//   - bank string
func (_e *CardManager_Expecter) BankRecognized(ctx any, bank any) *CardManager_BankRecognized_Call {
	return &CardManager_BankRecognized_Call{Call: _e.mock.On("BankRecognized", ctx, bank)}
}

func (_c *CardManager_BankRecognized_Call) Run(run func(ctx context.Context, bank string)) *CardManager_BankRecognized_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CardManager_BankRecognized_Call) Return(b bool, err error) *CardManager_BankRecognized_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *CardManager_BankRecognized_Call) RunAndReturn(run func(ctx context.Context, bank string) (bool, error)) *CardManager_BankRecognized_Call {
	_c.Call.Return(run)
	return _c
}

// BestPurchaseDay provides a mock function for the type CardManager
func (_mock *CardManager) BestPurchaseDay(ctx context.Context, bank string, dueDay int) (interfaces.BestPurchaseDay, error) {
	ret := _mock.Called(ctx, bank, dueDay)

	if len(ret) == 0 {
		panic("no return value specified for BestPurchaseDay")
	}

	var r0 interfaces.BestPurchaseDay
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) (interfaces.BestPurchaseDay, error)); ok {
		return returnFunc(ctx, bank, dueDay)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) interfaces.BestPurchaseDay); ok {
		r0 = returnFunc(ctx, bank, dueDay)
	} else {
		r0 = ret.Get(0).(interfaces.BestPurchaseDay)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = returnFunc(ctx, bank, dueDay)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CardManager_BestPurchaseDay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BestPurchaseDay'
type CardManager_BestPurchaseDay_Call struct {
	*mock.Call
}

// BestPurchaseDay is a helper method to define mock.On call
//   - ctx context.Context
//   - bank string
//   - dueDay int
func (_e *CardManager_Expecter) BestPurchaseDay(ctx any, bank any, dueDay any) *CardManager_BestPurchaseDay_Call {
	return &CardManager_BestPurchaseDay_Call{Call: _e.mock.On("BestPurchaseDay", ctx, bank, dueDay)}
}

func (_c *CardManager_BestPurchaseDay_Call) Run(run func(ctx context.Context, bank string, dueDay int)) *CardManager_BestPurchaseDay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CardManager_BestPurchaseDay_Call) Return(bestPurchaseDay interfaces.BestPurchaseDay, err error) *CardManager_BestPurchaseDay_Call {
	_c.Call.Return(bestPurchaseDay, err)
	return _c
}

func (_c *CardManager_BestPurchaseDay_Call) RunAndReturn(run func(ctx context.Context, bank string, dueDay int) (interfaces.BestPurchaseDay, error)) *CardManager_BestPurchaseDay_Call {
	_c.Call.Return(run)
	return _c
}

// CountCards provides a mock function for the type CardManager
func (_mock *CardManager) CountCards(ctx context.Context, userID uuid.UUID) (int64, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountCards")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int64, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) int64); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CardManager_CountCards_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountCards'
type CardManager_CountCards_Call struct {
	*mock.Call
}

// CountCards is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *CardManager_Expecter) CountCards(ctx any, userID any) *CardManager_CountCards_Call {
	return &CardManager_CountCards_Call{Call: _e.mock.On("CountCards", ctx, userID)}
}

func (_c *CardManager_CountCards_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *CardManager_CountCards_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CardManager_CountCards_Call) Return(n int64, err error) *CardManager_CountCards_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *CardManager_CountCards_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (int64, error)) *CardManager_CountCards_Call {
	_c.Call.Return(run)
	return _c
}

// CreateCard provides a mock function for the type CardManager
func (_mock *CardManager) CreateCard(ctx context.Context, in interfaces.NewCard) (interfaces.CardRef, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for CreateCard")
	}

	var r0 interfaces.CardRef
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interfaces.NewCard) (interfaces.CardRef, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, interfaces.NewCard) interfaces.CardRef); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(interfaces.CardRef)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, interfaces.NewCard) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CardManager_CreateCard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCard'
type CardManager_CreateCard_Call struct {
	*mock.Call
}

// CreateCard is a helper method to define mock.On call
//   - ctx context.Context
//   - in interfaces.NewCard
func (_e *CardManager_Expecter) CreateCard(ctx any, in any) *CardManager_CreateCard_Call {
	return &CardManager_CreateCard_Call{Call: _e.mock.On("CreateCard", ctx, in)}
}

func (_c *CardManager_CreateCard_Call) Run(run func(ctx context.Context, in interfaces.NewCard)) *CardManager_CreateCard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interfaces.NewCard
		if args[1] != nil {
			arg1 = args[1].(interfaces.NewCard)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CardManager_CreateCard_Call) Return(cardRef interfaces.CardRef, err error) *CardManager_CreateCard_Call {
	_c.Call.Return(cardRef, err)
	return _c
}

func (_c *CardManager_CreateCard_Call) RunAndReturn(run func(ctx context.Context, in interfaces.NewCard) (interfaces.CardRef, error)) *CardManager_CreateCard_Call {
	_c.Call.Return(run)
	return _c
}

// GetCard provides a mock function for the type CardManager
func (_mock *CardManager) GetCard(ctx context.Context, cardID uuid.UUID, userID uuid.UUID) (interfaces.Card, error) {
	ret := _mock.Called(ctx, cardID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetCard")
	}

	var r0 interfaces.Card
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (interfaces.Card, error)); ok {
		return returnFunc(ctx, cardID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) interfaces.Card); ok {
		r0 = returnFunc(ctx, cardID, userID)
	} else {
		r0 = ret.Get(0).(interfaces.Card)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, cardID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CardManager_GetCard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCard'
type CardManager_GetCard_Call struct {
	*mock.Call
}

// GetCard is a helper method to define mock.On call
//   - ctx context.Context
//   - cardID uuid.UUID
//   - userID uuid.UUID
func (_e *CardManager_Expecter) GetCard(ctx any, cardID any, userID any) *CardManager_GetCard_Call {
	return &CardManager_GetCard_Call{Call: _e.mock.On("GetCard", ctx, cardID, userID)}
}

func (_c *CardManager_GetCard_Call) Run(run func(ctx context.Context, cardID uuid.UUID, userID uuid.UUID)) *CardManager_GetCard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CardManager_GetCard_Call) Return(card interfaces.Card, err error) *CardManager_GetCard_Call {
	_c.Call.Return(card, err)
	return _c
}

func (_c *CardManager_GetCard_Call) RunAndReturn(run func(ctx context.Context, cardID uuid.UUID, userID uuid.UUID) (interfaces.Card, error)) *CardManager_GetCard_Call {
	_c.Call.Return(run)
	return _c
}

// HasOpenInstallments provides a mock function for the type CardManager
func (_mock *CardManager) HasOpenInstallments(ctx context.Context, cardID uuid.UUID, userID uuid.UUID) (bool, error) {
	ret := _mock.Called(ctx, cardID, userID)

	if len(ret) == 0 {
		panic("no return value specified for HasOpenInstallments")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (bool, error)); ok {
		return returnFunc(ctx, cardID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) bool); ok {
		r0 = returnFunc(ctx, cardID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, cardID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CardManager_HasOpenInstallments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasOpenInstallments'
type CardManager_HasOpenInstallments_Call struct {
	*mock.Call
}

// HasOpenInstallments is a helper method to define mock.On call
//   - ctx context.Context
//   - cardID uuid.UUID
//   - userID uuid.UUID
func (_e *CardManager_Expecter) HasOpenInstallments(ctx any, cardID any, userID any) *CardManager_HasOpenInstallments_Call {
	return &CardManager_HasOpenInstallments_Call{Call: _e.mock.On("HasOpenInstallments", ctx, cardID, userID)}
}

func (_c *CardManager_HasOpenInstallments_Call) Run(run func(ctx context.Context, cardID uuid.UUID, userID uuid.UUID)) *CardManager_HasOpenInstallments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CardManager_HasOpenInstallments_Call) Return(b bool, err error) *CardManager_HasOpenInstallments_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *CardManager_HasOpenInstallments_Call) RunAndReturn(run func(ctx context.Context, cardID uuid.UUID, userID uuid.UUID) (bool, error)) *CardManager_HasOpenInstallments_Call {
	_c.Call.Return(run)
	return _c
}

// ListCards provides a mock function for the type CardManager
func (_mock *CardManager) ListCards(ctx context.Context, userID uuid.UUID) ([]interfaces.Card, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListCards")
	}

	var r0 []interfaces.Card
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]interfaces.Card, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []interfaces.Card); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interfaces.Card)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CardManager_ListCards_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCards'
type CardManager_ListCards_Call struct {
	*mock.Call
}

// ListCards is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *CardManager_Expecter) ListCards(ctx any, userID any) *CardManager_ListCards_Call {
	return &CardManager_ListCards_Call{Call: _e.mock.On("ListCards", ctx, userID)}
}

func (_c *CardManager_ListCards_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *CardManager_ListCards_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CardManager_ListCards_Call) Return(cards []interfaces.Card, err error) *CardManager_ListCards_Call {
	_c.Call.Return(cards, err)
	return _c
}

func (_c *CardManager_ListCards_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]interfaces.Card, error)) *CardManager_ListCards_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveCardByNickname provides a mock function for the type CardManager
func (_mock *CardManager) ResolveCardByNickname(ctx context.Context, userID uuid.UUID, nickname string) (interfaces.Card, error) {
	ret := _mock.Called(ctx, userID, nickname)

	if len(ret) == 0 {
		panic("no return value specified for ResolveCardByNickname")
	}

	var r0 interfaces.Card
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (interfaces.Card, error)); ok {
		return returnFunc(ctx, userID, nickname)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) interfaces.Card); ok {
		r0 = returnFunc(ctx, userID, nickname)
	} else {
		r0 = ret.Get(0).(interfaces.Card)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, userID, nickname)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CardManager_ResolveCardByNickname_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveCardByNickname'
type CardManager_ResolveCardByNickname_Call struct {
	*mock.Call
}

// ResolveCardByNickname is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - nickname string
func (_e *CardManager_Expecter) ResolveCardByNickname(ctx any, userID any, nickname any) *CardManager_ResolveCardByNickname_Call {
	return &CardManager_ResolveCardByNickname_Call{Call: _e.mock.On("ResolveCardByNickname", ctx, userID, nickname)}
}

func (_c *CardManager_ResolveCardByNickname_Call) Run(run func(ctx context.Context, userID uuid.UUID, nickname string)) *CardManager_ResolveCardByNickname_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CardManager_ResolveCardByNickname_Call) Return(card interfaces.Card, err error) *CardManager_ResolveCardByNickname_Call {
	_c.Call.Return(card, err)
	return _c
}

func (_c *CardManager_ResolveCardByNickname_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, nickname string) (interfaces.Card, error)) *CardManager_ResolveCardByNickname_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDeleteCard provides a mock function for the type CardManager
func (_mock *CardManager) SoftDeleteCard(ctx context.Context, cardID uuid.UUID, userID uuid.UUID) error {
	ret := _mock.Called(ctx, cardID, userID)

	if len(ret) == 0 {
		panic("no return value specified for SoftDeleteCard")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, cardID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CardManager_SoftDeleteCard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDeleteCard'
type CardManager_SoftDeleteCard_Call struct {
	*mock.Call
}

// SoftDeleteCard is a helper method to define mock.On call
//   - ctx context.Context
//   - cardID uuid.UUID
//   - userID uuid.UUID
func (_e *CardManager_Expecter) SoftDeleteCard(ctx any, cardID any, userID any) *CardManager_SoftDeleteCard_Call {
	return &CardManager_SoftDeleteCard_Call{Call: _e.mock.On("SoftDeleteCard", ctx, cardID, userID)}
}

func (_c *CardManager_SoftDeleteCard_Call) Run(run func(ctx context.Context, cardID uuid.UUID, userID uuid.UUID)) *CardManager_SoftDeleteCard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CardManager_SoftDeleteCard_Call) Return(err error) *CardManager_SoftDeleteCard_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CardManager_SoftDeleteCard_Call) RunAndReturn(run func(ctx context.Context, cardID uuid.UUID, userID uuid.UUID) error) *CardManager_SoftDeleteCard_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCard provides a mock function for the type CardManager
func (_mock *CardManager) UpdateCard(ctx context.Context, in interfaces.CardUpdate) (interfaces.Card, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCard")
	}

	var r0 interfaces.Card
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interfaces.CardUpdate) (interfaces.Card, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, interfaces.CardUpdate) interfaces.Card); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(interfaces.Card)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, interfaces.CardUpdate) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CardManager_UpdateCard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCard'
type CardManager_UpdateCard_Call struct {
	*mock.Call
}

// UpdateCard is a helper method to define mock.On call
//   - ctx context.Context
//   - in interfaces.CardUpdate
func (_e *CardManager_Expecter) UpdateCard(ctx any, in any) *CardManager_UpdateCard_Call {
	return &CardManager_UpdateCard_Call{Call: _e.mock.On("UpdateCard", ctx, in)}
}

func (_c *CardManager_UpdateCard_Call) Run(run func(ctx context.Context, in interfaces.CardUpdate)) *CardManager_UpdateCard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interfaces.CardUpdate
		if args[1] != nil {
			arg1 = args[1].(interfaces.CardUpdate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CardManager_UpdateCard_Call) Return(card interfaces.Card, err error) *CardManager_UpdateCard_Call {
	_c.Call.Return(card, err)
	return _c
}

func (_c *CardManager_UpdateCard_Call) RunAndReturn(run func(ctx context.Context, in interfaces.CardUpdate) (interfaces.Card, error)) *CardManager_UpdateCard_Call {
	_c.Call.Return(run)
	return _c
}
