// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/LimaTeixeiraTecnologia/mecontrola/internal/agents/application/interfaces"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewCategoriesReader creates a new instance of CategoriesReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCategoriesReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *CategoriesReader {
	mock := &CategoriesReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CategoriesReader is an autogenerated mock type for the CategoriesReader type
type CategoriesReader struct {
	mock.Mock
}

type CategoriesReader_Expecter struct {
	mock *mock.Mock
}

func (_m *CategoriesReader) EXPECT() *CategoriesReader_Expecter {
	return &CategoriesReader_Expecter{mock: &_m.Mock}
}

// ResolveRootsBySlug provides a mock function for the type CategoriesReader
func (_mock *CategoriesReader) ResolveRootsBySlug(ctx context.Context, slugs []string) (map[string]uuid.UUID, error) {
	ret := _mock.Called(ctx, slugs)

	if len(ret) == 0 {
		panic("no return value specified for ResolveRootsBySlug")
	}

	var r0 map[string]uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) (map[string]uuid.UUID, error)); ok {
		return returnFunc(ctx, slugs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) map[string]uuid.UUID); ok {
		r0 = returnFunc(ctx, slugs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, slugs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CategoriesReader_ResolveRootsBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveRootsBySlug'
type CategoriesReader_ResolveRootsBySlug_Call struct {
	*mock.Call
}

// ResolveRootsBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slugs []string
func (_e *CategoriesReader_Expecter) ResolveRootsBySlug(ctx any, slugs any) *CategoriesReader_ResolveRootsBySlug_Call {
	return &CategoriesReader_ResolveRootsBySlug_Call{Call: _e.mock.On("ResolveRootsBySlug", ctx, slugs)}
}

func (_c *CategoriesReader_ResolveRootsBySlug_Call) Run(run func(ctx context.Context, slugs []string)) *CategoriesReader_ResolveRootsBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CategoriesReader_ResolveRootsBySlug_Call) Return(stringToUUID map[string]uuid.UUID, err error) *CategoriesReader_ResolveRootsBySlug_Call {
	_c.Call.Return(stringToUUID, err)
	return _c
}

func (_c *CategoriesReader_ResolveRootsBySlug_Call) RunAndReturn(run func(ctx context.Context, slugs []string) (map[string]uuid.UUID, error)) *CategoriesReader_ResolveRootsBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// SearchDictionary provides a mock function for the type CategoriesReader
func (_mock *CategoriesReader) SearchDictionary(ctx context.Context, term string, kind string) ([]interfaces.CategoryCandidate, error) {
	ret := _mock.Called(ctx, term, kind)

	if len(ret) == 0 {
		panic("no return value specified for SearchDictionary")
	}

	var r0 []interfaces.CategoryCandidate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]interfaces.CategoryCandidate, error)); ok {
		return returnFunc(ctx, term, kind)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []interfaces.CategoryCandidate); ok {
		r0 = returnFunc(ctx, term, kind)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interfaces.CategoryCandidate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, term, kind)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CategoriesReader_SearchDictionary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchDictionary'
type CategoriesReader_SearchDictionary_Call struct {
	*mock.Call
}

// SearchDictionary is a helper method to define mock.On call
//   - ctx context.Context
//   - term string
//   - kind string
func (_e *CategoriesReader_Expecter) SearchDictionary(ctx any, term any, kind any) *CategoriesReader_SearchDictionary_Call {
	return &CategoriesReader_SearchDictionary_Call{Call: _e.mock.On("SearchDictionary", ctx, term, kind)}
}

func (_c *CategoriesReader_SearchDictionary_Call) Run(run func(ctx context.Context, term string, kind string)) *CategoriesReader_SearchDictionary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CategoriesReader_SearchDictionary_Call) Return(categoryCandidates []interfaces.CategoryCandidate, err error) *CategoriesReader_SearchDictionary_Call {
	_c.Call.Return(categoryCandidates, err)
	return _c
}

func (_c *CategoriesReader_SearchDictionary_Call) RunAndReturn(run func(ctx context.Context, term string, kind string) ([]interfaces.CategoryCandidate, error)) *CategoriesReader_SearchDictionary_Call {
	_c.Call.Return(run)
	return _c
}
