// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/LimaTeixeiraTecnologia/mecontrola/internal/agents/application/interfaces"
	mock "github.com/stretchr/testify/mock"
)

// NewRecurrenceManager creates a new instance of RecurrenceManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRecurrenceManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *RecurrenceManager {
	mock := &RecurrenceManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RecurrenceManager is an autogenerated mock type for the RecurrenceManager type
type RecurrenceManager struct {
	mock.Mock
}

type RecurrenceManager_Expecter struct {
	mock *mock.Mock
}

func (_m *RecurrenceManager) EXPECT() *RecurrenceManager_Expecter {
	return &RecurrenceManager_Expecter{mock: &_m.Mock}
}

// CreateRecurrence provides a mock function for the type RecurrenceManager
func (_mock *RecurrenceManager) CreateRecurrence(ctx context.Context, in interfaces.RawRecurrence) (interfaces.EntryRef, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for CreateRecurrence")
	}

	var r0 interfaces.EntryRef
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interfaces.RawRecurrence) (interfaces.EntryRef, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, interfaces.RawRecurrence) interfaces.EntryRef); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(interfaces.EntryRef)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, interfaces.RawRecurrence) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RecurrenceManager_CreateRecurrence_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRecurrence'
type RecurrenceManager_CreateRecurrence_Call struct {
	*mock.Call
}

// CreateRecurrence is a helper method to define mock.On call
//   - ctx context.Context
//   - in interfaces.RawRecurrence
func (_e *RecurrenceManager_Expecter) CreateRecurrence(ctx any, in any) *RecurrenceManager_CreateRecurrence_Call {
	return &RecurrenceManager_CreateRecurrence_Call{Call: _e.mock.On("CreateRecurrence", ctx, in)}
}

func (_c *RecurrenceManager_CreateRecurrence_Call) Run(run func(ctx context.Context, in interfaces.RawRecurrence)) *RecurrenceManager_CreateRecurrence_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interfaces.RawRecurrence
		if args[1] != nil {
			arg1 = args[1].(interfaces.RawRecurrence)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RecurrenceManager_CreateRecurrence_Call) Return(entryRef interfaces.EntryRef, err error) *RecurrenceManager_CreateRecurrence_Call {
	_c.Call.Return(entryRef, err)
	return _c
}

func (_c *RecurrenceManager_CreateRecurrence_Call) RunAndReturn(run func(ctx context.Context, in interfaces.RawRecurrence) (interfaces.EntryRef, error)) *RecurrenceManager_CreateRecurrence_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRecurrence provides a mock function for the type RecurrenceManager
func (_mock *RecurrenceManager) DeleteRecurrence(ctx context.Context, templateID string, version int64) error {
	ret := _mock.Called(ctx, templateID, version)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRecurrence")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) error); ok {
		r0 = returnFunc(ctx, templateID, version)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RecurrenceManager_DeleteRecurrence_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRecurrence'
type RecurrenceManager_DeleteRecurrence_Call struct {
	*mock.Call
}

// DeleteRecurrence is a helper method to define mock.On call
//   - ctx context.Context
//   - templateID string
//   - version int64
func (_e *RecurrenceManager_Expecter) DeleteRecurrence(ctx any, templateID any, version any) *RecurrenceManager_DeleteRecurrence_Call {
	return &RecurrenceManager_DeleteRecurrence_Call{Call: _e.mock.On("DeleteRecurrence", ctx, templateID, version)}
}

func (_c *RecurrenceManager_DeleteRecurrence_Call) Run(run func(ctx context.Context, templateID string, version int64)) *RecurrenceManager_DeleteRecurrence_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RecurrenceManager_DeleteRecurrence_Call) Return(err error) *RecurrenceManager_DeleteRecurrence_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RecurrenceManager_DeleteRecurrence_Call) RunAndReturn(run func(ctx context.Context, templateID string, version int64) error) *RecurrenceManager_DeleteRecurrence_Call {
	_c.Call.Return(run)
	return _c
}

// ListRecurrences provides a mock function for the type RecurrenceManager
func (_mock *RecurrenceManager) ListRecurrences(ctx context.Context, activeOnly bool, cursor string, limit int) ([]interfaces.Recurrence, error) {
	ret := _mock.Called(ctx, activeOnly, cursor, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListRecurrences")
	}

	var r0 []interfaces.Recurrence
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool, string, int) ([]interfaces.Recurrence, error)); ok {
		return returnFunc(ctx, activeOnly, cursor, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool, string, int) []interfaces.Recurrence); ok {
		r0 = returnFunc(ctx, activeOnly, cursor, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interfaces.Recurrence)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bool, string, int) error); ok {
		r1 = returnFunc(ctx, activeOnly, cursor, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RecurrenceManager_ListRecurrences_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRecurrences'
type RecurrenceManager_ListRecurrences_Call struct {
	*mock.Call
}

// ListRecurrences is a helper method to define mock.On call
//   - ctx context.Context
//   - activeOnly bool
//   - cursor string
//   - limit int
func (_e *RecurrenceManager_Expecter) ListRecurrences(ctx any, activeOnly any, cursor any, limit any) *RecurrenceManager_ListRecurrences_Call {
	return &RecurrenceManager_ListRecurrences_Call{Call: _e.mock.On("ListRecurrences", ctx, activeOnly, cursor, limit)}
}

func (_c *RecurrenceManager_ListRecurrences_Call) Run(run func(ctx context.Context, activeOnly bool, cursor string, limit int)) *RecurrenceManager_ListRecurrences_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *RecurrenceManager_ListRecurrences_Call) Return(recurrences []interfaces.Recurrence, err error) *RecurrenceManager_ListRecurrences_Call {
	_c.Call.Return(recurrences, err)
	return _c
}

func (_c *RecurrenceManager_ListRecurrences_Call) RunAndReturn(run func(ctx context.Context, activeOnly bool, cursor string, limit int) ([]interfaces.Recurrence, error)) *RecurrenceManager_ListRecurrences_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRecurrence provides a mock function for the type RecurrenceManager
func (_mock *RecurrenceManager) UpdateRecurrence(ctx context.Context, templateID string, in interfaces.RawUpdateRecurrence) (interfaces.EntryRef, error) {
	ret := _mock.Called(ctx, templateID, in)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRecurrence")
	}

	var r0 interfaces.EntryRef
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, interfaces.RawUpdateRecurrence) (interfaces.EntryRef, error)); ok {
		return returnFunc(ctx, templateID, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, interfaces.RawUpdateRecurrence) interfaces.EntryRef); ok {
		r0 = returnFunc(ctx, templateID, in)
	} else {
		r0 = ret.Get(0).(interfaces.EntryRef)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, interfaces.RawUpdateRecurrence) error); ok {
		r1 = returnFunc(ctx, templateID, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RecurrenceManager_UpdateRecurrence_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRecurrence'
type RecurrenceManager_UpdateRecurrence_Call struct {
	*mock.Call
}

// UpdateRecurrence is a helper method to define mock.On call
//   - ctx context.Context
//   - templateID string
//   - in interfaces.RawUpdateRecurrence
func (_e *RecurrenceManager_Expecter) UpdateRecurrence(ctx any, templateID any, in any) *RecurrenceManager_UpdateRecurrence_Call {
	return &RecurrenceManager_UpdateRecurrence_Call{Call: _e.mock.On("UpdateRecurrence", ctx, templateID, in)}
}

func (_c *RecurrenceManager_UpdateRecurrence_Call) Run(run func(ctx context.Context, templateID string, in interfaces.RawUpdateRecurrence)) *RecurrenceManager_UpdateRecurrence_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 interfaces.RawUpdateRecurrence
		if args[2] != nil {
			arg2 = args[2].(interfaces.RawUpdateRecurrence)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RecurrenceManager_UpdateRecurrence_Call) Return(entryRef interfaces.EntryRef, err error) *RecurrenceManager_UpdateRecurrence_Call {
	_c.Call.Return(entryRef, err)
	return _c
}

func (_c *RecurrenceManager_UpdateRecurrence_Call) RunAndReturn(run func(ctx context.Context, templateID string, in interfaces.RawUpdateRecurrence) (interfaces.EntryRef, error)) *RecurrenceManager_UpdateRecurrence_Call {
	_c.Call.Return(run)
	return _c
}
