// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/LimaTeixeiraTecnologia/mecontrola/internal/agents/application/interfaces"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewTransactionsLedger creates a new instance of TransactionsLedger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionsLedger(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionsLedger {
	mock := &TransactionsLedger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TransactionsLedger is an autogenerated mock type for the TransactionsLedger type
type TransactionsLedger struct {
	mock.Mock
}

type TransactionsLedger_Expecter struct {
	mock *mock.Mock
}

func (_m *TransactionsLedger) EXPECT() *TransactionsLedger_Expecter {
	return &TransactionsLedger_Expecter{mock: &_m.Mock}
}

// CreateTransaction provides a mock function for the type TransactionsLedger
func (_mock *TransactionsLedger) CreateTransaction(ctx context.Context, in interfaces.RawTransaction) (interfaces.EntryRef, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for CreateTransaction")
	}

	var r0 interfaces.EntryRef
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interfaces.RawTransaction) (interfaces.EntryRef, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, interfaces.RawTransaction) interfaces.EntryRef); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(interfaces.EntryRef)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, interfaces.RawTransaction) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TransactionsLedger_CreateTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTransaction'
type TransactionsLedger_CreateTransaction_Call struct {
	*mock.Call
}

// CreateTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - in interfaces.RawTransaction
func (_e *TransactionsLedger_Expecter) CreateTransaction(ctx any, in any) *TransactionsLedger_CreateTransaction_Call {
	return &TransactionsLedger_CreateTransaction_Call{Call: _e.mock.On("CreateTransaction", ctx, in)}
}

func (_c *TransactionsLedger_CreateTransaction_Call) Run(run func(ctx context.Context, in interfaces.RawTransaction)) *TransactionsLedger_CreateTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interfaces.RawTransaction
		if args[1] != nil {
			arg1 = args[1].(interfaces.RawTransaction)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TransactionsLedger_CreateTransaction_Call) Return(entryRef interfaces.EntryRef, err error) *TransactionsLedger_CreateTransaction_Call {
	_c.Call.Return(entryRef, err)
	return _c
}

func (_c *TransactionsLedger_CreateTransaction_Call) RunAndReturn(run func(ctx context.Context, in interfaces.RawTransaction) (interfaces.EntryRef, error)) *TransactionsLedger_CreateTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTransaction provides a mock function for the type TransactionsLedger
func (_mock *TransactionsLedger) DeleteTransaction(ctx context.Context, ref interfaces.EntryRef, version int64) error {
	ret := _mock.Called(ctx, ref, version)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interfaces.EntryRef, int64) error); ok {
		r0 = returnFunc(ctx, ref, version)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TransactionsLedger_DeleteTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTransaction'
type TransactionsLedger_DeleteTransaction_Call struct {
	*mock.Call
}

// DeleteTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - ref interfaces.EntryRef
//   - version int64
func (_e *TransactionsLedger_Expecter) DeleteTransaction(ctx any, ref any, version any) *TransactionsLedger_DeleteTransaction_Call {
	return &TransactionsLedger_DeleteTransaction_Call{Call: _e.mock.On("DeleteTransaction", ctx, ref, version)}
}

func (_c *TransactionsLedger_DeleteTransaction_Call) Run(run func(ctx context.Context, ref interfaces.EntryRef, version int64)) *TransactionsLedger_DeleteTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interfaces.EntryRef
		if args[1] != nil {
			arg1 = args[1].(interfaces.EntryRef)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TransactionsLedger_DeleteTransaction_Call) Return(err error) *TransactionsLedger_DeleteTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TransactionsLedger_DeleteTransaction_Call) RunAndReturn(run func(ctx context.Context, ref interfaces.EntryRef, version int64) error) *TransactionsLedger_DeleteTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// GetCardInvoice provides a mock function for the type TransactionsLedger
func (_mock *TransactionsLedger) GetCardInvoice(ctx context.Context, cardID uuid.UUID, refMonth string) (interfaces.CardInvoice, error) {
	ret := _mock.Called(ctx, cardID, refMonth)

	if len(ret) == 0 {
		panic("no return value specified for GetCardInvoice")
	}

	var r0 interfaces.CardInvoice
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (interfaces.CardInvoice, error)); ok {
		return returnFunc(ctx, cardID, refMonth)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) interfaces.CardInvoice); ok {
		r0 = returnFunc(ctx, cardID, refMonth)
	} else {
		r0 = ret.Get(0).(interfaces.CardInvoice)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, cardID, refMonth)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TransactionsLedger_GetCardInvoice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCardInvoice'
type TransactionsLedger_GetCardInvoice_Call struct {
	*mock.Call
}

// GetCardInvoice is a helper method to define mock.On call
//   - ctx context.Context
//   - cardID uuid.UUID
//   - refMonth string
func (_e *TransactionsLedger_Expecter) GetCardInvoice(ctx any, cardID any, refMonth any) *TransactionsLedger_GetCardInvoice_Call {
	return &TransactionsLedger_GetCardInvoice_Call{Call: _e.mock.On("GetCardInvoice", ctx, cardID, refMonth)}
}

func (_c *TransactionsLedger_GetCardInvoice_Call) Run(run func(ctx context.Context, cardID uuid.UUID, refMonth string)) *TransactionsLedger_GetCardInvoice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TransactionsLedger_GetCardInvoice_Call) Return(cardInvoice interfaces.CardInvoice, err error) *TransactionsLedger_GetCardInvoice_Call {
	_c.Call.Return(cardInvoice, err)
	return _c
}

func (_c *TransactionsLedger_GetCardInvoice_Call) RunAndReturn(run func(ctx context.Context, cardID uuid.UUID, refMonth string) (interfaces.CardInvoice, error)) *TransactionsLedger_GetCardInvoice_Call {
	_c.Call.Return(run)
	return _c
}

// GetMonthlySummary provides a mock function for the type TransactionsLedger
func (_mock *TransactionsLedger) GetMonthlySummary(ctx context.Context, userID uuid.UUID, refMonth string) (interfaces.MonthlySummary, error) {
	ret := _mock.Called(ctx, userID, refMonth)

	if len(ret) == 0 {
		panic("no return value specified for GetMonthlySummary")
	}

	var r0 interfaces.MonthlySummary
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (interfaces.MonthlySummary, error)); ok {
		return returnFunc(ctx, userID, refMonth)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) interfaces.MonthlySummary); ok {
		r0 = returnFunc(ctx, userID, refMonth)
	} else {
		r0 = ret.Get(0).(interfaces.MonthlySummary)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, userID, refMonth)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TransactionsLedger_GetMonthlySummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMonthlySummary'
type TransactionsLedger_GetMonthlySummary_Call struct {
	*mock.Call
}

// GetMonthlySummary is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - refMonth string
func (_e *TransactionsLedger_Expecter) GetMonthlySummary(ctx any, userID any, refMonth any) *TransactionsLedger_GetMonthlySummary_Call {
	return &TransactionsLedger_GetMonthlySummary_Call{Call: _e.mock.On("GetMonthlySummary", ctx, userID, refMonth)}
}

func (_c *TransactionsLedger_GetMonthlySummary_Call) Run(run func(ctx context.Context, userID uuid.UUID, refMonth string)) *TransactionsLedger_GetMonthlySummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TransactionsLedger_GetMonthlySummary_Call) Return(monthlySummary interfaces.MonthlySummary, err error) *TransactionsLedger_GetMonthlySummary_Call {
	_c.Call.Return(monthlySummary, err)
	return _c
}

func (_c *TransactionsLedger_GetMonthlySummary_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, refMonth string) (interfaces.MonthlySummary, error)) *TransactionsLedger_GetMonthlySummary_Call {
	_c.Call.Return(run)
	return _c
}

// GetTransaction provides a mock function for the type TransactionsLedger
func (_mock *TransactionsLedger) GetTransaction(ctx context.Context, txID string) (interfaces.Entry, error) {
	ret := _mock.Called(ctx, txID)

	if len(ret) == 0 {
		panic("no return value specified for GetTransaction")
	}

	var r0 interfaces.Entry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (interfaces.Entry, error)); ok {
		return returnFunc(ctx, txID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) interfaces.Entry); ok {
		r0 = returnFunc(ctx, txID)
	} else {
		r0 = ret.Get(0).(interfaces.Entry)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, txID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TransactionsLedger_GetTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransaction'
type TransactionsLedger_GetTransaction_Call struct {
	*mock.Call
}

// GetTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - txID string
func (_e *TransactionsLedger_Expecter) GetTransaction(ctx any, txID any) *TransactionsLedger_GetTransaction_Call {
	return &TransactionsLedger_GetTransaction_Call{Call: _e.mock.On("GetTransaction", ctx, txID)}
}

func (_c *TransactionsLedger_GetTransaction_Call) Run(run func(ctx context.Context, txID string)) *TransactionsLedger_GetTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TransactionsLedger_GetTransaction_Call) Return(entry interfaces.Entry, err error) *TransactionsLedger_GetTransaction_Call {
	_c.Call.Return(entry, err)
	return _c
}

func (_c *TransactionsLedger_GetTransaction_Call) RunAndReturn(run func(ctx context.Context, txID string) (interfaces.Entry, error)) *TransactionsLedger_GetTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// ListMonthlyEntries provides a mock function for the type TransactionsLedger
func (_mock *TransactionsLedger) ListMonthlyEntries(ctx context.Context, userID uuid.UUID, refMonth string, cursor string, limit int) ([]interfaces.MonthlyEntry, error) {
	ret := _mock.Called(ctx, userID, refMonth, cursor, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListMonthlyEntries")
	}

	var r0 []interfaces.MonthlyEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, int) ([]interfaces.MonthlyEntry, error)); ok {
		return returnFunc(ctx, userID, refMonth, cursor, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, int) []interfaces.MonthlyEntry); ok {
		r0 = returnFunc(ctx, userID, refMonth, cursor, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interfaces.MonthlyEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string, int) error); ok {
		r1 = returnFunc(ctx, userID, refMonth, cursor, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TransactionsLedger_ListMonthlyEntries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMonthlyEntries'
type TransactionsLedger_ListMonthlyEntries_Call struct {
	*mock.Call
}

// ListMonthlyEntries is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - refMonth string
//   - cursor string
//   - limit int
func (_e *TransactionsLedger_Expecter) ListMonthlyEntries(ctx any, userID any, refMonth any, cursor any, limit any) *TransactionsLedger_ListMonthlyEntries_Call {
	return &TransactionsLedger_ListMonthlyEntries_Call{Call: _e.mock.On("ListMonthlyEntries", ctx, userID, refMonth, cursor, limit)}
}

func (_c *TransactionsLedger_ListMonthlyEntries_Call) Run(run func(ctx context.Context, userID uuid.UUID, refMonth string, cursor string, limit int)) *TransactionsLedger_ListMonthlyEntries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *TransactionsLedger_ListMonthlyEntries_Call) Return(monthlyEntrys []interfaces.MonthlyEntry, err error) *TransactionsLedger_ListMonthlyEntries_Call {
	_c.Call.Return(monthlyEntrys, err)
	return _c
}

func (_c *TransactionsLedger_ListMonthlyEntries_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, refMonth string, cursor string, limit int) ([]interfaces.MonthlyEntry, error)) *TransactionsLedger_ListMonthlyEntries_Call {
	_c.Call.Return(run)
	return _c
}

// SearchTransactions provides a mock function for the type TransactionsLedger
func (_mock *TransactionsLedger) SearchTransactions(ctx context.Context, userID uuid.UUID, query string, refMonth string, limit int) ([]interfaces.Entry, error) {
	ret := _mock.Called(ctx, userID, query, refMonth, limit)

	if len(ret) == 0 {
		panic("no return value specified for SearchTransactions")
	}

	var r0 []interfaces.Entry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, int) ([]interfaces.Entry, error)); ok {
		return returnFunc(ctx, userID, query, refMonth, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, int) []interfaces.Entry); ok {
		r0 = returnFunc(ctx, userID, query, refMonth, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interfaces.Entry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string, int) error); ok {
		r1 = returnFunc(ctx, userID, query, refMonth, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TransactionsLedger_SearchTransactions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchTransactions'
type TransactionsLedger_SearchTransactions_Call struct {
	*mock.Call
}

// SearchTransactions is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - query string
//   - refMonth string
//   - limit int
func (_e *TransactionsLedger_Expecter) SearchTransactions(ctx any, userID any, query any, refMonth any, limit any) *TransactionsLedger_SearchTransactions_Call {
	return &TransactionsLedger_SearchTransactions_Call{Call: _e.mock.On("SearchTransactions", ctx, userID, query, refMonth, limit)}
}

func (_c *TransactionsLedger_SearchTransactions_Call) Run(run func(ctx context.Context, userID uuid.UUID, query string, refMonth string, limit int)) *TransactionsLedger_SearchTransactions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *TransactionsLedger_SearchTransactions_Call) Return(entrys []interfaces.Entry, err error) *TransactionsLedger_SearchTransactions_Call {
	_c.Call.Return(entrys, err)
	return _c
}

func (_c *TransactionsLedger_SearchTransactions_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, query string, refMonth string, limit int) ([]interfaces.Entry, error)) *TransactionsLedger_SearchTransactions_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTransaction provides a mock function for the type TransactionsLedger
func (_mock *TransactionsLedger) UpdateTransaction(ctx context.Context, in interfaces.RawUpdateTransaction) (interfaces.EntryRef, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTransaction")
	}

	var r0 interfaces.EntryRef
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interfaces.RawUpdateTransaction) (interfaces.EntryRef, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, interfaces.RawUpdateTransaction) interfaces.EntryRef); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(interfaces.EntryRef)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, interfaces.RawUpdateTransaction) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TransactionsLedger_UpdateTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTransaction'
type TransactionsLedger_UpdateTransaction_Call struct {
	*mock.Call
}

// UpdateTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - in interfaces.RawUpdateTransaction
func (_e *TransactionsLedger_Expecter) UpdateTransaction(ctx any, in any) *TransactionsLedger_UpdateTransaction_Call {
	return &TransactionsLedger_UpdateTransaction_Call{Call: _e.mock.On("UpdateTransaction", ctx, in)}
}

func (_c *TransactionsLedger_UpdateTransaction_Call) Run(run func(ctx context.Context, in interfaces.RawUpdateTransaction)) *TransactionsLedger_UpdateTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interfaces.RawUpdateTransaction
		if args[1] != nil {
			arg1 = args[1].(interfaces.RawUpdateTransaction)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TransactionsLedger_UpdateTransaction_Call) Return(entryRef interfaces.EntryRef, err error) *TransactionsLedger_UpdateTransaction_Call {
	_c.Call.Return(entryRef, err)
	return _c
}

func (_c *TransactionsLedger_UpdateTransaction_Call) RunAndReturn(run func(ctx context.Context, in interfaces.RawUpdateTransaction) (interfaces.EntryRef, error)) *TransactionsLedger_UpdateTransaction_Call {
	_c.Call.Return(run)
	return _c
}
