// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"database/sql"

	mock "github.com/stretchr/testify/mock"
)

func NewMockDBTX(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDBTX {
	mock := &MockDBTX{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

type MockDBTX struct {
	mock.Mock
}

type MockDBTX_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDBTX) EXPECT() *MockDBTX_Expecter {
	return &MockDBTX_Expecter{mock: &_m.Mock}
}

func (_mock *MockDBTX) PrepareContext(ctx context.Context, query string) (*sql.Stmt, error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for PrepareContext")
	}

	var r0 *sql.Stmt
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*sql.Stmt, error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *sql.Stmt); ok {
		r0 = returnFunc(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Stmt)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type MockDBTX_PrepareContext_Call struct {
	*mock.Call
}

func (_e *MockDBTX_Expecter) PrepareContext(ctx interface{}, query interface{}) *MockDBTX_PrepareContext_Call {
	return &MockDBTX_PrepareContext_Call{Call: _e.mock.On("PrepareContext", ctx, query)}
}

func (_c *MockDBTX_PrepareContext_Call) Run(run func(ctx context.Context, query string)) *MockDBTX_PrepareContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDBTX_PrepareContext_Call) Return(stmt *sql.Stmt, err error) *MockDBTX_PrepareContext_Call {
	_c.Call.Return(stmt, err)
	return _c
}

func (_c *MockDBTX_PrepareContext_Call) RunAndReturn(run func(ctx context.Context, query string) (*sql.Stmt, error)) *MockDBTX_PrepareContext_Call {
	_c.Call.Return(run)
	return _c
}

func (_mock *MockDBTX) QueryRowContext(ctx context.Context, query string, args ...any) *sql.Row {
	var tmpRet mock.Arguments
	var varArgs []interface{}
	varArgs = append(varArgs, ctx, query)
	varArgs = append(varArgs, args...)
	tmpRet = _mock.Called(varArgs...)
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for QueryRowContext")
	}

	var r0 *sql.Row
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) *sql.Row); ok {
		r0 = returnFunc(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Row)
		}
	}
	return r0
}

type MockDBTX_QueryRowContext_Call struct {
	*mock.Call
}

func (_e *MockDBTX_Expecter) QueryRowContext(ctx interface{}, query interface{}, args ...interface{}) *MockDBTX_QueryRowContext_Call {
	return &MockDBTX_QueryRowContext_Call{Call: _e.mock.On("QueryRowContext",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *MockDBTX_QueryRowContext_Call) Run(run func(ctx context.Context, query string, args ...any)) *MockDBTX_QueryRowContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			variadicArgs[i] = a
		}
		run(arg0, arg1, variadicArgs...)
	})
	return _c
}

func (_c *MockDBTX_QueryRowContext_Call) Return(row *sql.Row) *MockDBTX_QueryRowContext_Call {
	_c.Call.Return(row)
	return _c
}

func (_c *MockDBTX_QueryRowContext_Call) RunAndReturn(run func(ctx context.Context, query string, args ...any) *sql.Row) *MockDBTX_QueryRowContext_Call {
	_c.Call.Return(run)
	return _c
}

func (_mock *MockDBTX) QueryContext(ctx context.Context, query string, args ...any) (*sql.Rows, error) {
	var tmpRet mock.Arguments
	var varArgs []interface{}
	varArgs = append(varArgs, ctx, query)
	varArgs = append(varArgs, args...)
	tmpRet = _mock.Called(varArgs...)
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for QueryContext")
	}

	var r0 *sql.Rows
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) (*sql.Rows, error)); ok {
		return returnFunc(ctx, query, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) *sql.Rows); ok {
		r0 = returnFunc(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Rows)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = returnFunc(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type MockDBTX_QueryContext_Call struct {
	*mock.Call
}

func (_e *MockDBTX_Expecter) QueryContext(ctx interface{}, query interface{}, args ...interface{}) *MockDBTX_QueryContext_Call {
	return &MockDBTX_QueryContext_Call{Call: _e.mock.On("QueryContext",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *MockDBTX_QueryContext_Call) Run(run func(ctx context.Context, query string, args ...any)) *MockDBTX_QueryContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			variadicArgs[i] = a
		}
		run(arg0, arg1, variadicArgs...)
	})
	return _c
}

func (_c *MockDBTX_QueryContext_Call) Return(rows *sql.Rows, err error) *MockDBTX_QueryContext_Call {
	_c.Call.Return(rows, err)
	return _c
}

func (_c *MockDBTX_QueryContext_Call) RunAndReturn(run func(ctx context.Context, query string, args ...any) (*sql.Rows, error)) *MockDBTX_QueryContext_Call {
	_c.Call.Return(run)
	return _c
}

func (_mock *MockDBTX) ExecContext(ctx context.Context, query string, args ...any) (sql.Result, error) {
	var tmpRet mock.Arguments
	var varArgs []interface{}
	varArgs = append(varArgs, ctx, query)
	varArgs = append(varArgs, args...)
	tmpRet = _mock.Called(varArgs...)
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ExecContext")
	}

	var r0 sql.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) (sql.Result, error)); ok {
		return returnFunc(ctx, query, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) sql.Result); ok {
		r0 = returnFunc(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = returnFunc(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type MockDBTX_ExecContext_Call struct {
	*mock.Call
}

func (_e *MockDBTX_Expecter) ExecContext(ctx interface{}, query interface{}, args ...interface{}) *MockDBTX_ExecContext_Call {
	return &MockDBTX_ExecContext_Call{Call: _e.mock.On("ExecContext",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *MockDBTX_ExecContext_Call) Run(run func(ctx context.Context, query string, args ...any)) *MockDBTX_ExecContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			variadicArgs[i] = a
		}
		run(arg0, arg1, variadicArgs...)
	})
	return _c
}

func (_c *MockDBTX_ExecContext_Call) Return(result sql.Result, err error) *MockDBTX_ExecContext_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockDBTX_ExecContext_Call) RunAndReturn(run func(ctx context.Context, query string, args ...any) (sql.Result, error)) *MockDBTX_ExecContext_Call {
	_c.Call.Return(run)
	return _c
}
