// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/LimaTeixeiraTecnologia/mecontrola/internal/identity/application/dtos/input"
	mock "github.com/stretchr/testify/mock"
)

// newProjectAuthEventUseCase creates a new instance of projectAuthEventUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newProjectAuthEventUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *projectAuthEventUseCase {
	mock := &projectAuthEventUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// projectAuthEventUseCase is an autogenerated mock type for the projectAuthEventUseCase type
type projectAuthEventUseCase struct {
	mock.Mock
}

type projectAuthEventUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *projectAuthEventUseCase) EXPECT() *projectAuthEventUseCase_Expecter {
	return &projectAuthEventUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type projectAuthEventUseCase
func (_mock *projectAuthEventUseCase) Execute(ctx context.Context, in input.ProjectAuthEvent) error {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, input.ProjectAuthEvent) error); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// projectAuthEventUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type projectAuthEventUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - in input.ProjectAuthEvent
func (_e *projectAuthEventUseCase_Expecter) Execute(ctx interface{}, in interface{}) *projectAuthEventUseCase_Execute_Call {
	return &projectAuthEventUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, in)}
}

func (_c *projectAuthEventUseCase_Execute_Call) Run(run func(ctx context.Context, in input.ProjectAuthEvent)) *projectAuthEventUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 input.ProjectAuthEvent
		if args[1] != nil {
			arg1 = args[1].(input.ProjectAuthEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *projectAuthEventUseCase_Execute_Call) Return(err error) *projectAuthEventUseCase_Execute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *projectAuthEventUseCase_Execute_Call) RunAndReturn(run func(ctx context.Context, in input.ProjectAuthEvent) error) *projectAuthEventUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
